//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.11 at 05:02:02 PM ICT 
//


package com.ws.gateway.cic;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dsKhachHang complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dsKhachHang">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dskhachHang" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dsKhachHang", propOrder = {
    "dskhachHang"
})
public class DsKhachHang {

    protected String dskhachHang;

    /**
     * Gets the value of the dskhachHang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDskhachHang() {
        return dskhachHang;
    }

    /**
     * Sets the value of the dskhachHang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDskhachHang(String value) {
        this.dskhachHang = value;
    }

}
