//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.19 at 03:05:43 PM ICT 
//


package com.ws.gateway.cic;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TimKiemKH complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TimKiemKH">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="loaikh" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="macic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tenkh" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="diachi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dkkd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="msthue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="socmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="matctd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="makh" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimKiemKH", propOrder = {
    "username",
    "loaikh",
    "macic",
    "tenkh",
    "diachi",
    "dkkd",
    "msthue",
    "socmt",
    "matctd",
    "makh"
})
public class TimKiemKH {

    protected String username;
    protected String loaikh;
    protected String macic;
    protected String tenkh;
    protected String diachi;
    protected String dkkd;
    protected String msthue;
    protected String socmt;
    protected String matctd;
    protected String makh;

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the loaikh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoaikh() {
        return loaikh;
    }

    /**
     * Sets the value of the loaikh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoaikh(String value) {
        this.loaikh = value;
    }

    /**
     * Gets the value of the macic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMacic() {
        return macic;
    }

    /**
     * Sets the value of the macic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMacic(String value) {
        this.macic = value;
    }

    /**
     * Gets the value of the tenkh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenkh() {
        return tenkh;
    }

    /**
     * Sets the value of the tenkh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenkh(String value) {
        this.tenkh = value;
    }

    /**
     * Gets the value of the diachi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiachi() {
        return diachi;
    }

    /**
     * Sets the value of the diachi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiachi(String value) {
        this.diachi = value;
    }

    /**
     * Gets the value of the dkkd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDkkd() {
        return dkkd;
    }

    /**
     * Sets the value of the dkkd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDkkd(String value) {
        this.dkkd = value;
    }

    /**
     * Gets the value of the msthue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsthue() {
        return msthue;
    }

    /**
     * Sets the value of the msthue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsthue(String value) {
        this.msthue = value;
    }

    /**
     * Gets the value of the socmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSocmt() {
        return socmt;
    }

    /**
     * Sets the value of the socmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSocmt(String value) {
        this.socmt = value;
    }

    /**
     * Gets the value of the matctd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatctd() {
        return matctd;
    }

    /**
     * Sets the value of the matctd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatctd(String value) {
        this.matctd = value;
    }

    /**
     * Gets the value of the makh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMakh() {
        return makh;
    }

    /**
     * Sets the value of the makh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMakh(String value) {
        this.makh = value;
    }

}
