//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.19 at 03:05:43 PM ICT 
//


package vn.org.intergration.ws.endpoint.cicqa;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import vn.org.intergration.ws.endpoint.cicqaprod.KhachHang;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="KhachHang" type="{http://www.endpoint.ws.intergration.org.vn/cicqaProd}KhachHang"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "khachHang"
})
@XmlRootElement(name = "HoiTin")
public class HoiTin {

    @XmlElement(name = "KhachHang", required = true)
    protected KhachHang khachHang;

    /**
     * Gets the value of the khachHang property.
     * 
     * @return
     *     possible object is
     *     {@link KhachHang }
     *     
     */
    public KhachHang getKhachHang() {
        return khachHang;
    }

    /**
     * Sets the value of the khachHang property.
     * 
     * @param value
     *     allowed object is
     *     {@link KhachHang }
     *     
     */
    public void setKhachHang(KhachHang value) {
        this.khachHang = value;
    }

}
