//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.19 at 03:05:43 PM ICT 
//


package vn.org.intergration.ws.endpoint.cicqa;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import vn.org.intergration.ws.endpoint.cicqaprod.DSKhachHangKQ;
import vn.org.intergration.ws.endpoint.cicqaprod.TTPhanHoi;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TTPhanHoi" type="{http://www.endpoint.ws.intergration.org.vn/cicqaProd}TTPhanHoi"/>
 *         &lt;element name="DSKhachHangKQ" type="{http://www.endpoint.ws.intergration.org.vn/cicqaProd}DSKhachHangKQ"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ttPhanHoi",
    "dsKhachHangKQ"
})
@XmlRootElement(name = "PHVanTinDSPhieu")
public class PHVanTinDSPhieu {

    @XmlElement(name = "TTPhanHoi", required = true)
    protected TTPhanHoi ttPhanHoi;
    @XmlElement(name = "DSKhachHangKQ", required = true)
    protected DSKhachHangKQ dsKhachHangKQ;

    /**
     * Gets the value of the ttPhanHoi property.
     * 
     * @return
     *     possible object is
     *     {@link TTPhanHoi }
     *     
     */
    public TTPhanHoi getTTPhanHoi() {
        return ttPhanHoi;
    }

    /**
     * Sets the value of the ttPhanHoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTPhanHoi }
     *     
     */
    public void setTTPhanHoi(TTPhanHoi value) {
        this.ttPhanHoi = value;
    }

    /**
     * Gets the value of the dsKhachHangKQ property.
     * 
     * @return
     *     possible object is
     *     {@link DSKhachHangKQ }
     *     
     */
    public DSKhachHangKQ getDSKhachHangKQ() {
        return dsKhachHangKQ;
    }

    /**
     * Sets the value of the dsKhachHangKQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link DSKhachHangKQ }
     *     
     */
    public void setDSKhachHangKQ(DSKhachHangKQ value) {
        this.dsKhachHangKQ = value;
    }

}
