//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.19 at 03:05:43 PM ICT 
//


package vn.org.intergration.ws.endpoint.cicqa;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import vn.org.intergration.ws.endpoint.cicqaprod.DSMaSoPhieu;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DSMaSoPhieu" type="{http://www.endpoint.ws.intergration.org.vn/cicqaProd}DSMaSoPhieu"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dsMaSoPhieu"
})
@XmlRootElement(name = "VanTinDSPhieu")
public class VanTinDSPhieu {

    @XmlElement(name = "DSMaSoPhieu", required = true)
    protected DSMaSoPhieu dsMaSoPhieu;

    /**
     * Gets the value of the dsMaSoPhieu property.
     * 
     * @return
     *     possible object is
     *     {@link DSMaSoPhieu }
     *     
     */
    public DSMaSoPhieu getDSMaSoPhieu() {
        return dsMaSoPhieu;
    }

    /**
     * Sets the value of the dsMaSoPhieu property.
     * 
     * @param value
     *     allowed object is
     *     {@link DSMaSoPhieu }
     *     
     */
    public void setDSMaSoPhieu(DSMaSoPhieu value) {
        this.dsMaSoPhieu = value;
    }

}
