//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.19 at 03:05:43 PM ICT 
//


package vn.org.intergration.ws.endpoint.cicqa;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TuyChon" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NgayHT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tuyChon",
    "ngayHT"
})
@XmlRootElement(name = "VanTin")
public class VanTin {

    @XmlElement(name = "TuyChon", required = true)
    protected String tuyChon;
    @XmlElement(name = "NgayHT", required = true)
    protected String ngayHT;

    /**
     * Gets the value of the tuyChon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTuyChon() {
        return tuyChon;
    }

    /**
     * Sets the value of the tuyChon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTuyChon(String value) {
        this.tuyChon = value;
    }

    /**
     * Gets the value of the ngayHT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNgayHT() {
        return ngayHT;
    }

    /**
     * Sets the value of the ngayHT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNgayHT(String value) {
        this.ngayHT = value;
    }

}
