//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.16 at 10:30:23 AM ICT 
//


package vn.com.cmc.ws.cicReport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Loi complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Loi"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MaChiTieu" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Ma" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MoTa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Loai" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DongBatDau" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Loi", propOrder = {
    "maChiTieu",
    "ma",
    "moTa",
    "loai",
    "dongBatDau"
})
public class Loi {

    @XmlElement(name = "MaChiTieu", required = true)
    protected String maChiTieu;
    @XmlElement(name = "Ma", required = true)
    protected String ma;
    @XmlElement(name = "MoTa", required = true)
    protected String moTa;
    @XmlElement(name = "Loai", required = true)
    protected String loai;
    @XmlElement(name = "DongBatDau", required = true)
    protected String dongBatDau;

    /**
     * Gets the value of the maChiTieu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaChiTieu() {
        return maChiTieu;
    }

    /**
     * Sets the value of the maChiTieu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaChiTieu(String value) {
        this.maChiTieu = value;
    }

    /**
     * Gets the value of the ma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMa() {
        return ma;
    }

    /**
     * Sets the value of the ma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMa(String value) {
        this.ma = value;
    }

    /**
     * Gets the value of the moTa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoTa() {
        return moTa;
    }

    /**
     * Sets the value of the moTa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoTa(String value) {
        this.moTa = value;
    }

    /**
     * Gets the value of the loai property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoai() {
        return loai;
    }

    /**
     * Sets the value of the loai property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoai(String value) {
        this.loai = value;
    }

    /**
     * Gets the value of the dongBatDau property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDongBatDau() {
        return dongBatDau;
    }

    /**
     * Sets the value of the dongBatDau property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDongBatDau(String value) {
        this.dongBatDau = value;
    }

}
