//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.16 at 10:30:23 AM ICT 
//


package vn.com.cmc.ws.cicReport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TenTep" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="NoiDungTep" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TenTepDinhKem" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="NoiDungTepDinhKem" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="NguoiYC" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tenTep",
    "noiDungTep",
    "tenTepDinhKem",
    "noiDungTepDinhKem",
    "nguoiYC"
})
@XmlRootElement(name = "TepBaoCao")
public class TepBaoCao {

    @XmlElement(name = "TenTep", required = true)
    protected String tenTep;
    @XmlElement(name = "NoiDungTep", required = true)
    protected String noiDungTep;
    @XmlElement(name = "TenTepDinhKem", required = true)
    protected String tenTepDinhKem;
    @XmlElement(name = "NoiDungTepDinhKem", required = true)
    protected String noiDungTepDinhKem;
    @XmlElement(name = "NguoiYC", required = true)
    protected String nguoiYC;

    /**
     * Gets the value of the tenTep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenTep() {
        return tenTep;
    }

    /**
     * Sets the value of the tenTep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenTep(String value) {
        this.tenTep = value;
    }

    /**
     * Gets the value of the noiDungTep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoiDungTep() {
        return noiDungTep;
    }

    /**
     * Sets the value of the noiDungTep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoiDungTep(String value) {
        this.noiDungTep = value;
    }

    /**
     * Gets the value of the tenTepDinhKem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenTepDinhKem() {
        return tenTepDinhKem;
    }

    /**
     * Sets the value of the tenTepDinhKem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenTepDinhKem(String value) {
        this.tenTepDinhKem = value;
    }

    /**
     * Gets the value of the noiDungTepDinhKem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoiDungTepDinhKem() {
        return noiDungTepDinhKem;
    }

    /**
     * Sets the value of the noiDungTepDinhKem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoiDungTepDinhKem(String value) {
        this.noiDungTepDinhKem = value;
    }

    /**
     * Gets the value of the nguoiYC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNguoiYC() {
        return nguoiYC;
    }

    /**
     * Sets the value of the nguoiYC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNguoiYC(String value) {
        this.nguoiYC = value;
    }

}
