//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.04 at 10:59:48 AM ICT 
//


package vn.org.cic.h2h.ws.endpoint.cicreport;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TTPhanHoi" type="{http://www.endpoint.ws.h2h.cic.org.vn/cicreport}TTPhanHoi"/&gt;
 *         &lt;element name="DSLoi" type="{http://www.endpoint.ws.h2h.cic.org.vn/cicreport}DSLoi"/&gt;
 *         &lt;element name="DongKQ" type="{http://www.endpoint.ws.h2h.cic.org.vn/cicreport}DongKQ" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ttPhanHoi",
    "dsLoi",
    "dongKQ"
})
@XmlRootElement(name = "PHDanhSachTepPhiCauTruc")
public class PHDanhSachTepPhiCauTruc {

    @XmlElement(name = "TTPhanHoi", required = true)
    protected TTPhanHoi ttPhanHoi;
    @XmlElement(name = "DSLoi", required = true)
    protected DSLoi dsLoi;
    @XmlElement(name = "DongKQ")
    protected List<DongKQ> dongKQ;

    /**
     * Gets the value of the ttPhanHoi property.
     * 
     * @return
     *     possible object is
     *     {@link TTPhanHoi }
     *     
     */
    public TTPhanHoi getTTPhanHoi() {
        return ttPhanHoi;
    }

    /**
     * Sets the value of the ttPhanHoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTPhanHoi }
     *     
     */
    public void setTTPhanHoi(TTPhanHoi value) {
        this.ttPhanHoi = value;
    }

    /**
     * Gets the value of the dsLoi property.
     * 
     * @return
     *     possible object is
     *     {@link DSLoi }
     *     
     */
    public DSLoi getDSLoi() {
        return dsLoi;
    }

    /**
     * Sets the value of the dsLoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link DSLoi }
     *     
     */
    public void setDSLoi(DSLoi value) {
        this.dsLoi = value;
    }

    /**
     * Gets the value of the dongKQ property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dongKQ property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDongKQ().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DongKQ }
     * 
     * 
     */
    public List<DongKQ> getDongKQ() {
        if (dongKQ == null) {
            dongKQ = new ArrayList<DongKQ>();
        }
        return this.dongKQ;
    }

}
