//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.04 at 10:59:48 AM ICT 
//


package vn.org.cic.h2h.ws.endpoint.cicreport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TTPhanHoi complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TTPhanHoi"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TrangThai" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DSLoi" type="{http://www.endpoint.ws.h2h.cic.org.vn/cicreport}DSLoi"/&gt;
 *         &lt;element name="Ma" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MoTa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="GuiLaiTep" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TTPhanHoi", propOrder = {
    "trangThai",
    "dsLoi",
    "ma",
    "moTa",
    "guiLaiTep"
})
public class TTPhanHoi {

    @XmlElement(name = "TrangThai", required = true)
    protected String trangThai;
    @XmlElement(name = "DSLoi", required = true)
    protected DSLoi dsLoi;
    @XmlElement(name = "Ma", required = true)
    protected String ma;
    @XmlElement(name = "MoTa", required = true)
    protected String moTa;
    @XmlElement(name = "GuiLaiTep")
    protected Integer guiLaiTep;

    /**
     * Gets the value of the trangThai property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrangThai() {
        return trangThai;
    }

    /**
     * Sets the value of the trangThai property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrangThai(String value) {
        this.trangThai = value;
    }

    /**
     * Gets the value of the dsLoi property.
     * 
     * @return
     *     possible object is
     *     {@link DSLoi }
     *     
     */
    public DSLoi getDSLoi() {
        return dsLoi;
    }

    /**
     * Sets the value of the dsLoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link DSLoi }
     *     
     */
    public void setDSLoi(DSLoi value) {
        this.dsLoi = value;
    }

    /**
     * Gets the value of the ma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMa() {
        return ma;
    }

    /**
     * Sets the value of the ma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMa(String value) {
        this.ma = value;
    }

    /**
     * Gets the value of the moTa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoTa() {
        return moTa;
    }

    /**
     * Sets the value of the moTa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoTa(String value) {
        this.moTa = value;
    }

    /**
     * Gets the value of the guiLaiTep property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGuiLaiTep() {
        return guiLaiTep;
    }

    /**
     * Sets the value of the guiLaiTep property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGuiLaiTep(Integer value) {
        this.guiLaiTep = value;
    }

}
