//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.23 at 09:19:37 AM ICT 
//


package vn.com.cmc.ws.endpoint.cicreport;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DongKQ" type="{http://www.endpoint.ws.cmc.com.vn/cicreport}DongKQ" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DSLoi" type="{http://www.endpoint.ws.cmc.com.vn/cicreport}DSLoi"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dongKQ",
    "dsLoi"
})
@XmlRootElement(name = "PHDanhSachTepBaoCao")
public class PHDanhSachTepBaoCao {

    @XmlElement(name = "DongKQ")
    protected List<DongKQ> dongKQ;
    @XmlElement(name = "DSLoi", required = true)
    protected DSLoi dsLoi;

    /**
     * Gets the value of the dongKQ property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dongKQ property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDongKQ().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DongKQ }
     * 
     * 
     */
    public List<DongKQ> getDongKQ() {
        if (dongKQ == null) {
            dongKQ = new ArrayList<DongKQ>();
        }
        return this.dongKQ;
    }

    /**
     * Gets the value of the dsLoi property.
     * 
     * @return
     *     possible object is
     *     {@link DSLoi }
     *     
     */
    public DSLoi getDSLoi() {
        return dsLoi;
    }

    /**
     * Sets the value of the dsLoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link DSLoi }
     *     
     */
    public void setDSLoi(DSLoi value) {
        this.dsLoi = value;
    }

}
