//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.23 at 09:19:37 AM ICT 
//


package vn.com.cmc.ws.endpoint.cicreport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TTPhanHoi" type="{http://www.endpoint.ws.cmc.com.vn/cicreport}TTPhanHoi"/>
 *         &lt;element name="TepTraLoi" type="{http://www.endpoint.ws.cmc.com.vn/cicreport}TepTraLoi"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ttPhanHoi",
    "tepTraLoi"
})
@XmlRootElement(name = "PHTepBaoCaoVanTin")
public class PHTepBaoCaoVanTin {

    @XmlElement(name = "TTPhanHoi", required = true)
    protected TTPhanHoi ttPhanHoi;
    @XmlElement(name = "TepTraLoi", required = true)
    protected TepTraLoi tepTraLoi;

    /**
     * Gets the value of the ttPhanHoi property.
     * 
     * @return
     *     possible object is
     *     {@link TTPhanHoi }
     *     
     */
    public TTPhanHoi getTTPhanHoi() {
        return ttPhanHoi;
    }

    /**
     * Sets the value of the ttPhanHoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTPhanHoi }
     *     
     */
    public void setTTPhanHoi(TTPhanHoi value) {
        this.ttPhanHoi = value;
    }

    /**
     * Gets the value of the tepTraLoi property.
     * 
     * @return
     *     possible object is
     *     {@link TepTraLoi }
     *     
     */
    public TepTraLoi getTepTraLoi() {
        return tepTraLoi;
    }

    /**
     * Sets the value of the tepTraLoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link TepTraLoi }
     *     
     */
    public void setTepTraLoi(TepTraLoi value) {
        this.tepTraLoi = value;
    }

}
