//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.23 at 09:19:37 AM ICT 
//


package vn.com.cmc.ws.endpoint.cicreport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TrangThai" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DSLoi" type="{http://www.endpoint.ws.cmc.com.vn/cicreport}DSLoi"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trangThai",
    "dsLoi"
})
@XmlRootElement(name = "PHTepPhiCauTruc")
public class PHTepPhiCauTruc {

    @XmlElement(name = "TrangThai", required = true)
    protected String trangThai;
    @XmlElement(name = "DSLoi", required = true)
    protected DSLoi dsLoi;

    /**
     * Gets the value of the trangThai property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrangThai() {
        return trangThai;
    }

    /**
     * Sets the value of the trangThai property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrangThai(String value) {
        this.trangThai = value;
    }

    /**
     * Gets the value of the dsLoi property.
     * 
     * @return
     *     possible object is
     *     {@link DSLoi }
     *     
     */
    public DSLoi getDSLoi() {
        return dsLoi;
    }

    /**
     * Sets the value of the dsLoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link DSLoi }
     *     
     */
    public void setDSLoi(DSLoi value) {
        this.dsLoi = value;
    }

}
