//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.23 at 09:19:37 AM ICT 
//


package vn.com.cmc.ws.endpoint.cicreport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TepTraLoi complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TepTraLoi">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element name="TTChung" type="{http://www.endpoint.ws.cmc.com.vn/cicreport}TTChung"/>
 *           &lt;element name="TTLoi" type="{http://www.endpoint.ws.cmc.com.vn/cicreport}TTLoi"/>
 *           &lt;element name="DSChiNhanh" type="{http://www.endpoint.ws.cmc.com.vn/cicreport}DSChiNhanh"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TepTraLoi", propOrder = {
    "ttChung",
    "ttLoi",
    "dsChiNhanh"
})
public class TepTraLoi {

    @XmlElement(name = "TTChung", required = true)
    protected TTChung ttChung;
    @XmlElement(name = "TTLoi", required = true)
    protected TTLoi ttLoi;
    @XmlElement(name = "DSChiNhanh", required = true)
    protected DSChiNhanh dsChiNhanh;

    /**
     * Gets the value of the ttChung property.
     * 
     * @return
     *     possible object is
     *     {@link TTChung }
     *     
     */
    public TTChung getTTChung() {
        return ttChung;
    }

    /**
     * Sets the value of the ttChung property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTChung }
     *     
     */
    public void setTTChung(TTChung value) {
        this.ttChung = value;
    }

    /**
     * Gets the value of the ttLoi property.
     * 
     * @return
     *     possible object is
     *     {@link TTLoi }
     *     
     */
    public TTLoi getTTLoi() {
        return ttLoi;
    }

    /**
     * Sets the value of the ttLoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTLoi }
     *     
     */
    public void setTTLoi(TTLoi value) {
        this.ttLoi = value;
    }

    /**
     * Gets the value of the dsChiNhanh property.
     * 
     * @return
     *     possible object is
     *     {@link DSChiNhanh }
     *     
     */
    public DSChiNhanh getDSChiNhanh() {
        return dsChiNhanh;
    }

    /**
     * Sets the value of the dsChiNhanh property.
     * 
     * @param value
     *     allowed object is
     *     {@link DSChiNhanh }
     *     
     */
    public void setDSChiNhanh(DSChiNhanh value) {
        this.dsChiNhanh = value;
    }

}
