//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.10 at 01:47:40 PM ICT 
//


package vn.com.cmc.ws.cicStatisticalReport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DongKQ complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DongKQ"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MaBaoCao" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TuNgay" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DenNgay" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="NoiDung" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DongKQ", propOrder = {
    "maBaoCao",
    "tuNgay",
    "denNgay",
    "noiDung"
})
public class DongKQ {

    @XmlElement(name = "MaBaoCao", required = true)
    protected String maBaoCao;
    @XmlElement(name = "TuNgay", required = true)
    protected String tuNgay;
    @XmlElement(name = "DenNgay", required = true)
    protected String denNgay;
    @XmlElement(name = "NoiDung", required = true)
    protected String noiDung;

    /**
     * Gets the value of the maBaoCao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaBaoCao() {
        return maBaoCao;
    }

    /**
     * Sets the value of the maBaoCao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaBaoCao(String value) {
        this.maBaoCao = value;
    }

    /**
     * Gets the value of the tuNgay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTuNgay() {
        return tuNgay;
    }

    /**
     * Sets the value of the tuNgay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTuNgay(String value) {
        this.tuNgay = value;
    }

    /**
     * Gets the value of the denNgay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDenNgay() {
        return denNgay;
    }

    /**
     * Sets the value of the denNgay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDenNgay(String value) {
        this.denNgay = value;
    }

    /**
     * Gets the value of the noiDung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoiDung() {
        return noiDung;
    }

    /**
     * Sets the value of the noiDung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoiDung(String value) {
        this.noiDung = value;
    }

}
