//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.10 at 01:47:40 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.endpoint.ws.h2h.core.cic.org.vn/cicstatisticalreport", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package vn.com.cmc.ws.cicStatisticalReport;
