package entity.frwk;

//Generated Nov 13, 2019 6:00:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name = "COMPANY", uniqueConstraints = @UniqueConstraint(columnNames = { "CODE", "PARENT" }))
public class Company implements java.io.Serializable {

	private String id;
	private Company company;
	private String code;
	private String sortName;
	private String name;
	private String intcde;
	private Boolean status;
	private String phone;
	private Date modifyTime;
	private String email;
	private Byte cqlevel;
	private String path;
	private String address;
	private String branchCd;
	private String city;
	private String nation;
	private String bssregcert;
	private String flagPgd;
	private String fax;
	private Set<Company> companies = new HashSet(0);
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "company")
	public Set<Company> getCompanies() {
		return companies;
	}

	public void setCompanies(Set<Company> companies) {
		this.companies = companies;
	}
	
	@Transient
	private String parentId;
	
	@Transient
	private SysUsers creator, modifier;
	
	@Transient
	public SysUsers getCreator() {
		return creator;
	}

	public void setCreator(SysUsers creator) {
		this.creator = creator;
	}
	
	@Transient
	public SysUsers getModifier() {
		return modifier;
	}

	public void setModifier(SysUsers modifier) {
		this.modifier = modifier;
	}

	@JsonIgnore
	private Company parent;

	public Company() {
	}

	public Company(String id) {
		this.id = id;
	}
	
	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 40)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARENT")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "CODE", length = 40)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "SORT_NAME", length = 900)
	public String getSortName() {
		return this.sortName;
	}

	public void setSortName(String sortName) {
		this.sortName = sortName;
	}

	@Column(name = "NAME", length = 900)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "INTCDE", length = 40)
	public String getIntcde() {
		return this.intcde;
	}

	public void setIntcde(String intcde) {
		this.intcde = intcde;
	}

	@Column(name = "STATUS", precision = 1, scale = 0)
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "PHONE", length = 40)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFY_TIME", length = 7)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "EMAIL", length = 40)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "CQLEVEL", precision = 2, scale = 0)
	public Byte getCqlevel() {
		return this.cqlevel;
	}

	public void setCqlevel(Byte cqlevel) {
		this.cqlevel = cqlevel;
	}

	@Column(name = "PATH", length = 40)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "ADDRESS", length = 1500)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "BRANCH_CD", length = 40)
	public String getBranchCd() {
		return this.branchCd;
	}

	public void setBranchCd(String branchCd) {
		this.branchCd = branchCd;
	}

	@Column(name = "CITY", length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "NATION", length = 50)
	public String getNation() {
		return this.nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	@Column(name = "BSSREGCERT", length = 200)
	public String getBssregcert() {
		return this.bssregcert;
	}

	public void setBssregcert(String bssregcert) {
		this.bssregcert = bssregcert;
	}

	@Column(name = "FLAG_PGD", length = 1)
	public String getFlagPgd() {
		return this.flagPgd;
	}

	public void setFlagPgd(String flagPgd) {
		this.flagPgd = flagPgd;
	}

	@Column(name = "FAX", length = 200)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	
	public void setParentId(String parentId) {
		this.parentId = parentId;
		this.parent = new Company(parentId);
	}
	
	@Transient
	public String getParentId() {
		return parentId;
	}

	public void setParent(Company parent) {
		this.parent = parent;
		if (this.parent != null)
			this.parentId = this.parent.getId();
	}

	public Company getParent() {
		return parent;
	}
}