package entity.frwk;

//Generated Nov 13, 2019 6:00:05 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * JobcodeRole generated by hbm2java
 */
@Entity
@Table(name = "JOBCODE_ROLE", uniqueConstraints = @UniqueConstraint(columnNames = { "JOBCODE",
		"ROLE" }))
public class JobcodeRole implements java.io.Serializable {

	private String id;
	private String jobcode;
	private String role;
	private String ibsyDescr250;
	private String descrshort;

	public JobcodeRole() {
	}

	public JobcodeRole(String id, String jobcode, String role) {
		this.id = id;
		this.jobcode = jobcode;
		this.role = role;
	}

	public JobcodeRole(String id, String jobcode, String role, String ibsyDescr250, String descrshort) {
		this.id = id;
		this.jobcode = jobcode;
		this.role = role;
		this.ibsyDescr250 = ibsyDescr250;
		this.descrshort = descrshort;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 40)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "JOBCODE", nullable = false, length = 100)
	public String getJobcode() {
		return this.jobcode;
	}

	public void setJobcode(String jobcode) {
		this.jobcode = jobcode;
	}

	@Column(name = "ROLE", nullable = false, length = 300)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "IBSY_DESCR250", length = 3000)
	public String getIbsyDescr250() {
		return this.ibsyDescr250;
	}

	public void setIbsyDescr250(String ibsyDescr250) {
		this.ibsyDescr250 = ibsyDescr250;
	}

	@Column(name = "DESCRSHORT", length = 1500)
	public String getDescrshort() {
		return this.descrshort;
	}

	public void setDescrshort(String descrshort) {
		this.descrshort = descrshort;
	}

}
