package entity.frwk;

import java.util.ArrayList;

// Generated Nov 13, 2019 6:00:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

import com.fasterxml.jackson.annotation.JsonIgnore;

import entity.SysObjAppFlow;

/**
 * SysObjects generated by hbm2java
 */
@Entity
@Table(name = "SYS_OBJECTS")
public class SysObjects implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	@Column(name = "ID")
	private String id;
	@Column(name = "NAME")
	private String name;
	@Column(name = "ACTION")
	private String action;
	@Column(name = "OBJECT_ID")
	private String objectId;
	@Column(name = "ORDER_COLUMN")
	private Short orderColumn;
	@Column(name = "MODIFY_TIME")
	@Temporal(TemporalType.TIMESTAMP)
	private Date modifyTime;
	@Column(name = "IS_AUDIT")
	private Short isAudit;
	@Column(name = "NAME_EN")
	private String nameEn;
	@Column(name = "ACTIVE")
	private Short active;
	@Column(name = "USEDBYPARTNER")
	private Short usedbypartner;
	@JsonIgnore
	@OneToMany(cascade = CascadeType.ALL, mappedBy = "sysObjId")
	private Set<SysObjAppFlow> sysObjAppFlows = new HashSet<SysObjAppFlow>(0);
	@Transient
	private ArrayList<SysObjAppFlow> sysObjAppFlowArrayList;
	@OneToMany(mappedBy = "sysObjects")
	@JsonIgnore
	private Set<SysObjects> sysObjectses;
	@JoinColumn(name = "PARENT_ID", referencedColumnName = "ID")
	@ManyToOne
	private SysObjects sysObjects;
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysObjects", cascade = CascadeType.ALL)
	private List<SysRights> sysRightses = new ArrayList<SysRights>();

	public SysObjects() {
	}

	public SysObjects(String id) {
		this.id = id;
	}

	public SysObjects(String id, String name) {
		this.id = id;
		this.name = name;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getObjectId() {
		return objectId;
	}

	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}

	public Short getOrderColumn() {
		return orderColumn;
	}

	public void setOrderColumn(Short orderColumn) {
		this.orderColumn = orderColumn;
	}

	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public Short getIsAudit() {
		return isAudit;
	}

	public void setIsAudit(Short isAudit) {
		this.isAudit = isAudit;
	}

	public String getNameEn() {
		return nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	public Short getActive() {
		return active;
	}

	public void setActive(Short active) {
		this.active = active;
	}

	public Short getUsedbypartner() {
		return usedbypartner;
	}

	public void setUsedbypartner(Short usedbypartner) {
		this.usedbypartner = usedbypartner;
	}

	public Set<SysObjAppFlow> getSysObjAppFlows() {
		return sysObjAppFlows;
	}

	public void setSysObjAppFlows(Set<SysObjAppFlow> sysObjAppFlows) {
		this.sysObjAppFlows = sysObjAppFlows;
		this.sysObjAppFlowArrayList = new ArrayList<SysObjAppFlow>(sysObjAppFlows);
	}

	public ArrayList<SysObjAppFlow> getSysObjAppFlowArrayList() {
		return sysObjAppFlowArrayList;
	}

	public void setSysObjAppFlowArrayList(ArrayList<SysObjAppFlow> sysObjAppFlowArrayList) {
		this.sysObjAppFlowArrayList = sysObjAppFlowArrayList;
		this.sysObjAppFlows.addAll(sysObjAppFlowArrayList);
	}

	public Set<SysObjects> getSysObjectses() {
		return sysObjectses;
	}

	public void setSysObjectses(Set<SysObjects> sysObjectses) {
		this.sysObjectses = sysObjectses;
	}

	public SysObjects getSysObjects() {
		return sysObjects;
	}

	public void setSysObjects(SysObjects sysObjects) {
		this.sysObjects = sysObjects;
	}
	
	public List<SysRights> getSysRightses() {
		return this.sysRightses;
	}

	public void setSysRightses(List<SysRights> sysRightses) {
		this.sysRightses = sysRightses;
	}
	
	public Boolean isOffSpring(SysObjects so) {
		if (this.getId().equals(so.getId()))
			return Boolean.TRUE;
		for (SysObjects child : so.getSysObjectses()) {
			if (isOffSpring(child))
				return true;
		}
		return Boolean.FALSE;
	}
//	private String id;
//	private SysObjects sysObjects;
//	private String name;
//	private String action;
//	private String objectId;
//	private Short orderColumn;
//	private Date modifyTime;
//	private Boolean isAudit;
//	private String nameEn;
//	private Boolean active;
//	private Boolean usedbypartner;
//	@JsonIgnore
//	private Set<SysObjects> sysObjectses = new HashSet(0);
//	
//	private List<SysRights> sysRightses = new ArrayList<SysRights>();
//	@JsonIgnore
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysObjects", cascade = CascadeType.ALL)
//	public List<SysRights> getSysRightses() {
//		return this.sysRightses;
//	}
//
//	public void setSysRightses(List<SysRights> sysRightses) {
//		this.sysRightses = sysRightses;
//	}
//	
//	private Set<SysObjAppFlow> sysObjAppFlows = new HashSet<SysObjAppFlow>(0);
//
//	public SysObjects() {
//	}
//
//	public SysObjects(String id, String name) {
//		this.id = id;
//		this.name = name;
//	}
//
//	public SysObjects(String id, SysObjects sysObjects, String name, String action, String objectId, Short orderColumn,
//			Date modifyTime, Boolean isAudit, String nameEn, Boolean active, Boolean usedbypartner, Set sysObjectses,
//			List<SysRights> sysRightses) {
//		this.id = id;
//		this.sysObjects = sysObjects;
//		this.name = name;
//		this.action = action;
//		this.objectId = objectId;
//		this.orderColumn = orderColumn;
//		this.modifyTime = modifyTime;
//		this.isAudit = isAudit;
//		this.nameEn = nameEn;
//		this.active = active;
//		this.usedbypartner = usedbypartner;
//		this.sysObjectses = sysObjectses;
//		this.sysRightses = sysRightses;
//	}
//
//	@Id
//	@Column(name = "ID", unique = true, nullable = false, length = 40)
//	@GeneratedValue(generator = "uuid")
//	@GenericGenerator(name = "uuid", strategy = "uuid")
//	public String getId() {
//		return this.id;
//	}
//
//	public void setId(String id) {
//		this.id = id;
//	}
//
//	@ManyToOne(fetch = FetchType.EAGER)
//	@JoinColumn(name = "PARENT_ID")
//	public SysObjects getSysObjects() {
//		return this.sysObjects;
//	}
//
//	public void setSysObjects(SysObjects sysObjects) {
//		this.sysObjects = sysObjects;
//	}
//
//	@Column(name = "NAME", nullable = false, length = 3000)
//	public String getName() {
//		return this.name;
//	}
//
//	public void setName(String name) {
//		this.name = name;
//	}
//
//	@Column(name = "ACTION", length = 3000)
//	public String getAction() {
//		return this.action;
//	}
//
//	public void setAction(String action) {
//		this.action = action;
//	}
//
//	@Column(name = "OBJECT_ID", length = 40)
//	public String getObjectId() {
//		return this.objectId;
//	}
//
//	public void setObjectId(String objectId) {
//		this.objectId = objectId;
//	}
//
//	@Column(name = "ORDER_COLUMN", precision = 3, scale = 0)
//	public Short getOrderColumn() {
//		return this.orderColumn;
//	}
//
//	public void setOrderColumn(Short orderColumn) {
//		this.orderColumn = orderColumn;
//	}
//
//	@Temporal(TemporalType.DATE)
//	@Column(name = "MODIFY_TIME", length = 7)
//	public Date getModifyTime() {
//		return this.modifyTime;
//	}
//
//	public void setModifyTime(Date modifyTime) {
//		this.modifyTime = modifyTime;
//	}
//
//	@Column(name = "IS_AUDIT", precision = 1, scale = 0)
//	public Boolean getIsAudit() {
//		return this.isAudit;
//	}
//
//	public void setIsAudit(Boolean isAudit) {
//		this.isAudit = isAudit;
//	}
//
//	@Column(name = "NAME_EN", length = 3000)
//	public String getNameEn() {
//		return this.nameEn;
//	}
//
//	public void setNameEn(String nameEn) {
//		this.nameEn = nameEn;
//	}
//
//	@Column(name = "ACTIVE", precision = 1, scale = 0)
//	public Boolean getActive() {
//		return this.active;
//	}
//
//	public void setActive(Boolean active) {
//		this.active = active;
//	}
//
//	@Column(name = "USEDBYPARTNER", precision = 1, scale = 0)
//	public Boolean getUsedbypartner() {
//		return this.usedbypartner;
//	}
//
//	public void setUsedbypartner(Boolean usedbypartner) {
//		this.usedbypartner = usedbypartner;
//	}
//
//	@JsonIgnore
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysObjects")
//	public Set<SysObjects> getSysObjectses() {
//		return this.sysObjectses;
//	}
//
//	public void setSysObjectses(Set<SysObjects> sysObjectses) {
//		this.sysObjectses = sysObjectses;
//	}
//	
//	@JsonIgnore
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysObjId")
//	public Set<SysObjAppFlow> getSysObjAppFlows() {
//		return sysObjAppFlows;
//	}
//
//	public void setSysObjAppFlows(Set<SysObjAppFlow> sysObjAppFlows) {
//		this.sysObjAppFlows = sysObjAppFlows;
//	}
//
//	public Boolean isOffSpring(SysObjects so) {
//		if (this.getId().equals(so.getId()))
//			return Boolean.TRUE;
//		for (SysObjects child : so.getSysObjectses()) {
//			if (isOffSpring(child))
//				return true;
//		}
//		return Boolean.FALSE;
//	}

}
