package entity.frwk;

// Generated Nov 13, 2019 6:00:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * SysRolesUsers generated by hbm2java
 */
@Entity
@Table(name = "SYS_ROLES_USERS")
public class SysRolesUsers implements java.io.Serializable {

	private SysRolesUsersId id;
	@JsonIgnore
	private SysUsers sysUsers;
	@JsonIgnore
	private SysRoles sysRoles;
	private Date modifyTime;

	public SysRolesUsers() {
	}
    public SysRolesUsers(SysUsers sysUsers, SysRoles sysRoles) {
        this.sysUsers = sysUsers;
        this.sysRoles = sysRoles;
        this.id = new SysRolesUsersId(sysUsers.getId(), sysRoles == null ? null : sysRoles.getId());
    }
	public SysRolesUsers(SysRolesUsersId id, SysUsers sysUsers, SysRoles sysRoles) {
		this.id = id;
		this.sysUsers = sysUsers;
		this.sysRoles = sysRoles;
	}

	public SysRolesUsers(SysRolesUsersId id, SysUsers sysUsers, SysRoles sysRoles, Date modifyTime) {
		this.id = id;
		this.sysUsers = sysUsers;
		this.sysRoles = sysRoles;
		this.modifyTime = modifyTime;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false, length = 40)),
			@AttributeOverride(name = "roleId", column = @Column(name = "ROLE_ID", nullable = false, length = 40)) })
	public SysRolesUsersId getId() {
		return this.id;
	}

	public void setId(SysRolesUsersId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false, insertable = false, updatable = false)
	public SysUsers getSysUsers() {
		return this.sysUsers;
	}

	public void setSysUsers(SysUsers sysUsers) {
		this.sysUsers = sysUsers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLE_ID", nullable = false, insertable = false, updatable = false)
	public SysRoles getSysRoles() {
		return this.sysRoles;
	}

	public void setSysRoles(SysRoles sysRoles) {
		this.sysRoles = sysRoles;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFY_TIME", length = 7)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

}
