package entity.frwk;

// Generated Nov 13, 2019 6:00:05 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysRightsId generated by hbm2java
 */
@Embeddable
public class SysRightsId implements java.io.Serializable {

	private String roleId;
	private String objectId;

	public SysRightsId() {
	}

	public SysRightsId(String roleId, String objectId) {
		this.roleId = roleId;
		this.objectId = objectId;
	}

	@Column(name = "ROLE_ID", nullable = false, length = 40)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "OBJECT_ID", nullable = false, length = 40)
	public String getObjectId() {
		return this.objectId;
	}

	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SysRightsId))
			return false;
		SysRightsId castOther = (SysRightsId) other;

		return ((this.getRoleId() == castOther.getRoleId()) || (this.getRoleId() != null
				&& castOther.getRoleId() != null && this.getRoleId().equals(castOther.getRoleId())))
				&& ((this.getObjectId() == castOther.getObjectId()) || (this.getObjectId() != null
						&& castOther.getObjectId() != null && this.getObjectId().equals(castOther.getObjectId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRoleId() == null ? 0 : this.getRoleId().hashCode());
		result = 37 * result + (getObjectId() == null ? 0 : this.getObjectId().hashCode());
		return result;
	}

}
