package entity.frwk;

// Generated Nov 13, 2019 6:00:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysRights generated by hbm2java
 */
@Entity
@Table(name = "SYS_RIGHTS")
public class SysRights implements java.io.Serializable {

	private SysRightsId id;
	private SysObjects sysObjects;
	private SysRoles sysRoles;
	private Date modifyTime;

	public SysRights() {
	}

	public SysRights(SysRightsId id, SysObjects sysObjects, SysRoles sysRoles) {
		this.id = id;
		this.sysObjects = sysObjects;
		this.sysRoles = sysRoles;
	}

	public SysRights(SysObjects sysObjects, SysRoles sysRoles) {
		this.id = new SysRightsId(sysRoles.getId(), sysObjects.getId());
		this.sysObjects = sysObjects;
		this.sysRoles = sysRoles;
	}

	public SysRights(SysRightsId id, SysObjects sysObjects, SysRoles sysRoles, Date modifyTime) {
		this.id = id;
		this.sysObjects = sysObjects;
		this.sysRoles = sysRoles;
		this.modifyTime = modifyTime;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "roleId", column = @Column(name = "ROLE_ID", nullable = false, length = 40)),
			@AttributeOverride(name = "objectId", column = @Column(name = "OBJECT_ID", nullable = false, length = 40)) })
	public SysRightsId getId() {
		return this.id;
	}

	public void setId(SysRightsId id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFY_TIME", length = 7)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OBJECT_ID", nullable = false, insertable = false, updatable = false)
	public SysObjects getSysObjects() {
		return sysObjects;
	}

	public void setSysObjects(SysObjects sysObjects) {
		this.sysObjects = sysObjects;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLE_ID", nullable = false, insertable = false, updatable = false)
	public SysRoles getSysRoles() {
		return this.sysRoles;
	}

	public void setSysRoles(SysRoles sysRoles) {
		this.sysRoles = sysRoles;
	}
}
