//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.18 at 06:17:47 PM ICT 
//


package vn.org.cic.h2h.ws.endpoint.cicauthen;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TenDangNhap" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MatKhau" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tenDangNhap",
    "matKhau"
})
@XmlRootElement(name = "DangNhap")
public class DangNhap {

    @XmlElement(name = "TenDangNhap", required = true)
    protected String tenDangNhap;
    @XmlElement(name = "MatKhau", required = true)
    protected String matKhau;

    /**
     * Gets the value of the tenDangNhap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenDangNhap() {
        return tenDangNhap;
    }

    /**
     * Sets the value of the tenDangNhap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenDangNhap(String value) {
        this.tenDangNhap = value;
    }

    /**
     * Gets the value of the matKhau property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatKhau() {
        return matKhau;
    }

    /**
     * Sets the value of the matKhau property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatKhau(String value) {
        this.matKhau = value;
    }

}
