//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.18 at 06:17:47 PM ICT 
//


package vn.org.cic.h2h.ws.endpoint.cicauthen;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Token" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ThoiGianBatDau" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TokenHetHan" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Ma" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MoTa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MatKhauHetHan" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "token",
    "thoiGianBatDau",
    "tokenHetHan",
    "ma",
    "moTa",
    "matKhauHetHan"
})
@XmlRootElement(name = "PHDangNhap")
public class PHDangNhap {

    @XmlElement(name = "Token", required = true)
    protected String token;
    @XmlElement(name = "ThoiGianBatDau", required = true)
    protected String thoiGianBatDau;
    @XmlElement(name = "TokenHetHan", required = true)
    protected BigInteger tokenHetHan;
    @XmlElement(name = "Ma", required = true)
    protected String ma;
    @XmlElement(name = "MoTa", required = true)
    protected String moTa;
    @XmlElement(name = "MatKhauHetHan", required = true)
    protected BigInteger matKhauHetHan;

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToken(String value) {
        this.token = value;
    }

    /**
     * Gets the value of the thoiGianBatDau property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThoiGianBatDau() {
        return thoiGianBatDau;
    }

    /**
     * Sets the value of the thoiGianBatDau property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThoiGianBatDau(String value) {
        this.thoiGianBatDau = value;
    }

    /**
     * Gets the value of the tokenHetHan property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTokenHetHan() {
        return tokenHetHan;
    }

    /**
     * Sets the value of the tokenHetHan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTokenHetHan(BigInteger value) {
        this.tokenHetHan = value;
    }

    /**
     * Gets the value of the ma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMa() {
        return ma;
    }

    /**
     * Sets the value of the ma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMa(String value) {
        this.ma = value;
    }

    /**
     * Gets the value of the moTa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoTa() {
        return moTa;
    }

    /**
     * Sets the value of the moTa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoTa(String value) {
        this.moTa = value;
    }

    /**
     * Gets the value of the matKhauHetHan property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMatKhauHetHan() {
        return matKhauHetHan;
    }

    /**
     * Sets the value of the matKhauHetHan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMatKhauHetHan(BigInteger value) {
        this.matKhauHetHan = value;
    }

}
