package entity;

import java.lang.reflect.InvocationTargetException;

// Generated Jan 6, 2021 10:10:52 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.regex.*;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.hibernate.annotations.GenericGenerator;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import common.util.Formater;
import common.util.ResourceException;
import common.util.Util;
import entity.frwk.SysDictParam;
import entity.frwk.SysDictType;

/**
 * DictTemp generated by hbm2java
 */
@Entity
@Table(name = "DICT_TEMP", schema = "POC")
public class DictTemp implements java.io.Serializable {

	private String id;
	private Templates templates;
	@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
	private DictMeasure dictMeasure;
	private String columnCode;
	private BigDecimal columnPosition;
	private String groupName;
	private Boolean mandatory;
	private String tblPath;
	private String columnField;
	private String objectId;
	private BigDecimal objectLevel;
	private String objectType;
	private String objectDesc;
	private String objPath;
	private String columnDesc;
	private Boolean parentCtrl;
	private String columnKey;
	private String updBy;
	private Date updDt;
	private String action;
	private String ctype;
	@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
	private SysDictType dictType;
	private Byte grpLevel;
	private String realGroupName;
	private String groupClass;
	private String controlType;
	private Boolean displayInOneLine;
	private String label, title, sclass;
	private String maxlength;
	@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
	private SysDictParam ctrType;
	private String realControlType;

	public DictTemp() {
	}

	public DictTemp(String id) {
		this.id = id;
	}

	@Id
	@Column(name = "ID")
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TEMP_ID")
	public Templates getTemplates() {
		return this.templates;
	}

	public void setTemplates(Templates templates) {
		this.templates = templates;
	}

	@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEASURE_ID")
	public DictMeasure getDictMeasure() {
		return this.dictMeasure;
	}

	public void setDictMeasure(DictMeasure dictMeasure) {
		this.dictMeasure = dictMeasure;
	}

	@Column(name = "COLUMN_CODE", length = 100)
	public String getColumnCode() {
		return this.columnCode;
	}

	public void setColumnCode(String columnCode) {
		this.columnCode = columnCode;
	}

	@Column(name = "COLUMN_POSITION", precision = 22, scale = 0)
	public BigDecimal getColumnPosition() {
		return this.columnPosition;
	}

	public void setColumnPosition(BigDecimal columnPosition) {
		this.columnPosition = columnPosition;
	}

	@Column(name = "GROUP_NAME", length = 500)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "MANDATORY", precision = 1, scale = 0)
	public Boolean getMandatory() {
		return this.mandatory;
	}

	public void setMandatory(Boolean mandatory) {
		this.mandatory = mandatory;
	}

	@Column(name = "TBL_PATH", length = 3200)
	public String getTblPath() {
		return this.tblPath;
	}

	public void setTblPath(String tblPath) {
		this.tblPath = tblPath;
	}

	@Column(name = "COLUMN_FIELD", length = 100)
	public String getColumnField() {
		return this.columnField;
	}

	public void setColumnField(String columnField) {
		this.columnField = columnField;
	}

	@Column(name = "OBJECT_ID", length = 20)
	public String getObjectId() {
		return this.objectId;
	}

	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}

	@Column(name = "OBJECT_LEVEL", precision = 22, scale = 0)
	public BigDecimal getObjectLevel() {
		return this.objectLevel;
	}

	public void setObjectLevel(BigDecimal objectLevel) {
		this.objectLevel = objectLevel;
	}

	@Column(name = "OBJECT_TYPE", length = 20)
	public String getObjectType() {
		return this.objectType;
	}

	public void setObjectType(String objectType) {
		this.objectType = objectType;
	}

	@Column(name = "OBJECT_DESC", length = 100)
	public String getObjectDesc() {
		return this.objectDesc;
	}

	public void setObjectDesc(String objectDesc) {
		this.objectDesc = objectDesc;
	}

	@Column(name = "OBJ_PATH", length = 2000)
	public String getObjPath() {
		return this.objPath;
	}

	public void setObjPath(String objPath) {
		this.objPath = objPath;
	}

	@Column(name = "COLUMN_DESC", length = 2000)
	public String getColumnDesc() {
		return this.columnDesc;
	}

	public void setColumnDesc(String columnDesc) {
		this.columnDesc = columnDesc;
	}

	@Column(name = "COLUMN_KEY", length = 50)
	public String getColumnKey() {
		return this.columnKey;
	}

	public void setColumnKey(String columnKey) {
		this.columnKey = columnKey;
	}

	@Column(name = "UPD_BY", length = 50)
	public String getUpdBy() {
		return this.updBy;
	}

	public void setUpdBy(String updBy) {
		this.updBy = updBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPD_DT", length = 7)
	public Date getUpdDt() {
		return this.updDt;
	}

	public void setUpdDt(Date updDt) {
		this.updDt = updDt;
	}

	@Column(name = "ACTION", length = 100)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "CTYPE", length = 50)
	public String getCtype() {
		return this.ctype;
	}

	public void setCtype(String ctype) {
		this.ctype = ctype;
	}

	@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
	@JoinColumn(name = "DICT_TYPE", referencedColumnName = "ID")
	@ManyToOne(optional = true, fetch = FetchType.LAZY)
	public SysDictType getDictType() {
		return this.dictType;
	}

	public void setDictType(SysDictType dictType) {
		this.dictType = dictType;
	}

	@Column(name = "GROUP_LEVEL")
	public Byte getGrpLevel() {
		return grpLevel;
	}

	public void setGrpLevel(Byte grpLevel) {
		this.grpLevel = grpLevel;
	}
	
	@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
	@JoinColumn(name = "CONTROL_TYPE", referencedColumnName = "ID")
	@ManyToOne(optional = true, fetch = FetchType.LAZY)
	public SysDictParam getCtrType() {
		return ctrType;
	}

	public void setCtrType(SysDictParam ctrType) {
		this.ctrType = ctrType;
	}

	@Transient
	public String getRealGroupName() {
		return realGroupName;
	}

	public void setRealGroupName(String realGroupName) {
		this.realGroupName = realGroupName;
	}

	@Transient
	public String getGroupClass() {
		return groupClass;
	}

	public void setGroupClass(String groupClass) {
		this.groupClass = groupClass;
	}

	public int compareTo(DictTemp other) {
		// So sanh group name
		if (Formater.isNull(this.getRealGroupName())) {
			if (!Formater.isNull(other.getRealGroupName()))
				return -1;
		} else {
			if (Formater.isNull(other.getRealGroupName()))
				return 1;
			int iTemp = this.getRealGroupName().compareTo(other.getRealGroupName());
			if (iTemp != 0)
				return iTemp;

		}

		// So sanh vi tri
		if (this.getColumnPosition() == null) {
			if (other.getColumnPosition() != null)
				return -1;
		} else {
			if (other.getColumnPosition() == null)
				return 1;
			return this.getColumnPosition().compareTo(other.getColumnPosition());
		}

		// So sanh group class
		if (Formater.isNull(this.getGroupClass())) {
			if (!Formater.isNull(other.getGroupClass()))
				return -1;
		} else {
			if (Formater.isNull(other.getGroupClass()))
				return 1;
			int iTemp = this.getGroupClass().compareTo(other.getGroupClass());
			if (iTemp != 0)
				return iTemp;
		}

		return 0;

	}

	public void sparateClass() {
		if (!Formater.isNull(this.getGroupName()) && this.getGroupName().indexOf("{") > 0
				&& this.getGroupName().indexOf("}") > 0) {
			String[] temp1 = this.getGroupName().split("\\{");
			String realGroupName = temp1[0];
			String groupClass = temp1[1].split("}")[0];
			this.setRealGroupName(realGroupName);
			this.setGroupClass(groupClass);

		} else
			this.setRealGroupName(this.getGroupName());
	}

	private Object value;
	private Short iLableWidth;
	private static final String DEFAULT_BS_FORMAT_CSS = "col-md-%s col-lg-%s col-sm-12 col-xs-12";
	private String bsLabelCss, bsInputCss;

	public void prepare(Object profile) throws Exception {
		// control type
		this.controlType = this.getCtrType() == null ? this.getDictMeasure().getDataSource()
				: this.getCtrType().getValue();
		if (this.controlType == null)
			this.controlType = ControlType.TEXT;

		// Label
		if (!Formater.isNull(this.columnDesc) && this.columnDesc.trim().length() > 3
				&& (isInputControl(this.controlType) || ControlType.CHECKBOX.equals(this.controlType)
						|| ControlType.TEXTAREA.equals(this.controlType) || ControlType.CHK_GRP.equals(this.controlType)
						|| ControlType.DATE.equals(this.controlType) || ControlType.DATM.equals(this.controlType)
						|| ControlType.SELECT.equals(this.controlType))) {

			// 1{2}
			String temp = this.columnDesc.substring(this.columnDesc.length() - 3);
			Pattern p = Pattern.compile("(?s).*\\{(\\d)\\}$");
			Matcher m = p.matcher(temp);
			if (m.matches()) {
				this.displayInOneLine = Boolean.TRUE;
				this.label = this.columnDesc.substring(0, this.columnDesc.length() - 3).trim();
				// title
				Pattern p1 = Pattern.compile("(?s).*\\{(.*)\\}$");
				Matcher m1 = p1.matcher(this.label);
				if (m1.matches()) {
					this.title = m1.group(1);
					if (this.label.length() > this.title.length()) {
						this.label = this.label.substring(0, this.label.length() - (this.title.length() + 2));
					}
				}
				iLableWidth = Short.valueOf(m.group(1));
				this.bsLabelCss = String.format(DEFAULT_BS_FORMAT_CSS, new Object[] { iLableWidth, iLableWidth });
				this.bsInputCss = String.format(DEFAULT_BS_FORMAT_CSS,
						new Object[] { 12 - iLableWidth, 12 - iLableWidth });
			}

		}

		if (this.label == null) {
			if (this.displayInOneLine == null || !this.displayInOneLine) {
				this.displayInOneLine = ControlType.TEXTAREA.equals(this.controlType)
						|| ControlType.RADIO.equals(this.controlType) || ControlType.CKEDITOR.equals(this.controlType);
			}
			this.label = Formater.isNull(this.columnDesc) ? dictMeasure.getColDesc() : this.columnDesc;
			// title
			Pattern p = Pattern.compile("(?s).*\\{(.*)\\}$");
			Matcher m = p.matcher(this.label);
			if (m.matches()) {
				this.title = m.group(1);
				if (this.label.length() > this.title.length()) {
					this.label = this.label.substring(0, this.label.length() - (this.title.length() + 2));
				}
			}
			if (this.getMandatory() != null && this.getMandatory())
				this.label += "<font color=\"red\">*</font>";

			this.bsLabelCss = String.format(DEFAULT_BS_FORMAT_CSS, new Object[] { 2, 2 });

			if (this.displayInOneLine)
				this.bsInputCss = String.format(DEFAULT_BS_FORMAT_CSS, new Object[] { 10, 10 });
			else
				this.bsInputCss = String.format(DEFAULT_BS_FORMAT_CSS, new Object[] { 3, 3 });
		}

		// Value
		this.value = profile != null && !Formater.isNull(dictMeasure.getPath()) ? profile.getClass().getMethod("getValue", new Class[] { String.class })
				.invoke(profile, dictMeasure.getPath()) : null;

		// Class
		this.sclass = getCssClass(dictMeasure.getDataType()) + " " + String.valueOf(dictMeasure.getDictGrp().getId());
		if (this.getMandatory() != null && this.getMandatory())
			this.sclass += " required";
		if (ControlType.TEXTDIGITS.equals(this.controlType))
			this.sclass += " " + ControlType.TEXTDIGITS;
		else if (ControlType.TEXTINT.equals(this.controlType))
			this.sclass += " " + ControlType.TEXTINT;
		if (!Formater.isNull(this.sclass))
			this.sclass = this.sclass.toLowerCase();

		// Max lengh
		this.maxlength = "";
		if (dictMeasure.getColLength() != null && dictMeasure.getColLength().indexOf(",") == -1) {
			this.maxlength = dictMeasure.getColLength();
		} else if (dictMeasure.getColLength() != null && dictMeasure.getColLength().indexOf(",") != -1) {
			if (DATA_TYPE_NUM.equalsIgnoreCase(dictMeasure.getDataType())) {
				int totalLength = Integer.parseInt(dictMeasure.getColLength().split(",")[0]);
				int decimaLength = Integer.parseInt(dictMeasure.getColLength().split(",")[1]);
				int intLength = totalLength - decimaLength;
				int numOfCommaSeparator = intLength <= 3 ? 0 : intLength % 3 == 0 ? intLength / 3 - 1 : intLength / 3;
				if (decimaLength > 2)
					decimaLength = 2;
				this.maxlength = String.valueOf(intLength + numOfCommaSeparator + 1 + decimaLength);
			}
		}
	}

	public String createInput(Object dataObj, String id2) throws Exception {

		String propertyName = this.getDictMeasure().getPath()
				.substring(this.getDictMeasure().getPath().lastIndexOf(".") + 1);
		Object value = null;
		if (!ControlType.GRDCLM_DOWNLOAD.equals(controlType)) {
			value = dataObj == null ? null : Util.getValueOfProperty(dataObj, propertyName);
		}

		String sclass = getCssClass(dictMeasure.getDataType()) + " " + String.valueOf(dictMeasure.getDictGrp().getId());

		if (this.getMandatory() != null && this.getMandatory())
			sclass += " required";

		// Uu tien la trong dictemp truoc
		controlType = this.getCtrType() == null ? this.getDictMeasure().getDataSource() : this.getCtrType().getValue();
		if (ControlType.TEXTDIGITS.equals(controlType) || ControlType.GRDCLM_TEXTDIGITS.equals(controlType))
			sclass += " " + ControlType.TEXTDIGITS;

		if (this.getCtrType() != null)
			sclass += " " + this.getCtrType().getValue();

		if (!Formater.isNull(sclass))
			sclass = sclass.toLowerCase();

		String sValue = value == null ? "" : value.toString();
		if (isInputControl(controlType)) {
			// name = '%s' '%s' class = '%s' value = '%s'
			return String.format(FIELD_INPUT, new Object[] { dictMeasure.getPath(), Formater.isNull(this.maxlength)?"":"maxlength='" +this.maxlength+"'", sclass, sValue });
		} else if (ControlType.GRDCLM_TXT_READONLY.equals(controlType)) {
			return String.format(HTML_FIELD_TXT_READONLY, new Object[] {dictMeasure.getPath(), Formater.isNull(this.maxlength)?"":"maxlength='" +this.maxlength+"'", sclass, sValue });
		} 
		else if (ControlType.INPUT_READONLY.equals(controlType)) {
			// [lable, class, name, value]
			return String.format(HTML_FIELD_INPUT_READONLY, new Object[] { this.bsLabelCss, this.label, this.bsInputCss,
					this.sclass, dictMeasure.getPath(), this.maxlength, sValue });
		} else if (ControlType.INPUT_HIDDEN.equals(controlType)) {
			// [lable, class, name, value]
			return String.format(HTML_FIELD_INPUT_HIDDEN, new Object[] { this.bsLabelCss, this.label, this.bsInputCss,
					this.sclass, dictMeasure.getPath(), this.maxlength, sValue });
		} 
		else if (ControlType.CHECKBOX.equals(controlType) || ControlType.GRDCLM_CHECKBOX.equals(controlType)) {
			// [lable, class, name, value, checked] bo class" easyui-switchbutton"
			String chkValue = value == null ? "false" : sValue;
			String temp = String.format(FIELD_CHECK_BOX, new Object[] { sclass, dictMeasure.getPath(), chkValue,
					value == null ? "" : (Boolean) value ? "checked" : "" });
			return temp;
		} else if (ControlType.RADIO.equals(controlType) || ControlType.GRDCLM_RADIO.equals(controlType)) {
			if (this.getDictType() == null) {
				return "";
			} else {
				String[] arrStrResult = renderRadios(dictMeasure, sValue);
				String htmlRadioEle = arrStrResult[0];
				String temp = String.format(FIELD_RADIO, new Object[] { dictMeasure.getColDesc(), htmlRadioEle });
				// Bo sung hidden field luu gia tri cua radio
				temp += String.format(FIELD_HIDDEN, new Object[] { this.getDictMeasure().getPath(),
						this.getDictMeasure().getPath(), Formater.isNull(sValue) ? arrStrResult[1] : sValue });
				// Bo sung su kien check tren tab khac
				// temp += makeChkScriptOnMulTiTatab(this.getDictMeasure().getPath());
				return temp;
			}

		} else if (ControlType.DATE.equals(controlType) || ControlType.GRDCLM_DATE.equals(controlType)) {
			// [lable, class, name, value]
			String temp = String.format(FIELD_DATE, new Object[] { sclass, dictMeasure.getPath(), sValue, "" });
			return temp;
		} else if (ControlType.DATM.equals(controlType) || ControlType.GRD_DATM.equals(controlType)) {
			// [lable, class, name, value]
			String temp = String.format(FIELD_DATE_TIME, new Object[] { sclass, dictMeasure.getPath(), sValue, "" });
			return temp;
		} else if (ControlType.TEXTAREA.equals(controlType) || ControlType.GRDCLM_TEXTAREA.equals(controlType)) {
			// [lable, class, name, value]
			String temp = String.format(FIELD_TEXT_AREA,
					new Object[] { sclass, dictMeasure.getPath(), maxlength, sValue });
			return temp;
		} else if (ControlType.CKEDITOR.equals(controlType)) {
			String temp = String.format(HTML_FIELD_CK_EDITOR,
					new Object[] { Formater.isNull(this.groupClass) ? "" : this.groupClass, this.bsLabelCss, this.label,
							this.bsInputCss, this.sclass, dictMeasure.getPath(), this.maxlength, sValue });
			temp += String.format(EVENT_CK_EDITTOR, new Object[] { dictMeasure.getPath(), dictMeasure.getPath(),
					dictMeasure.getPath(), dictMeasure.getPath() });
			return temp;
		} else if (ControlType.SELECT.equals(controlType) || ControlType.GRDCLM_SELECT.equals(controlType)) {
			String htmlOption = this.getDictType() == null ? renderOptions(dictMeasure.getListDataSelect(), sValue)
					: renderOptions(sValue);
			String temp = String.format(FIELD_SELECT,
					new Object[] { sclass, dictMeasure.getPath(), sValue, htmlOption });
			return temp;
		}else if (ControlType.LINK.equals(controlType) || ControlType.GRDCLM_LINK.equals(controlType)) {
			String linkUrl = "";
			if (dataObj != null) {
				Long profileId = (Long) dataObj.getClass().getMethod("getId").invoke(dataObj);
				linkUrl = dictMeasure.getPath() + profileId;
			}
			String temp = String.format(FIELD_LINK, new Object[] { linkUrl });
			return temp;
		} else if (ControlType.TITLE.equals(controlType) || ControlType.GRDCLM_TITLE.equals(controlType)) {
			return "";
		} else if (ControlType.GRDCLM_UPLOAD.equals(controlType)) {
			if (Formater.isNull(id))
				return "";
			String uploadInfo[] = this.getDictMeasure().getPath().split(",");
			if (uploadInfo == null || uploadInfo.length != 2)
				return "check lai thong tin cau hinh";
			String temp = String.format(FIELD_UPLOAD, new Object[] { uploadInfo[1].trim(), uploadInfo[0].trim() });
			return temp;
			// <a href="#" onclick="upload()"><i class="fa fa-upload"></i>Tải file</a>
		} else if (ControlType.GRDCLM_DOWNLOAD.equals(controlType)) {
			if (Formater.isNull(id))
				return "";
			String dwnloadInf[] = this.getDictMeasure().getPath().split(",");
			if (dwnloadInf == null || dwnloadInf.length != 2)
				return "check lai thong tin cau hinh";
//			String propertyFileName = dwnloadInf[0].trim().substring(dwnloadInf[0].lastIndexOf(".") + 1);
//			String fileName = dataObj == null ? null : (String) Util.getValueOfProperty(dataObj, propertyFileName);
//
//			String propertyFileId = dwnloadInf[1].trim().substring(dwnloadInf[1].trim().lastIndexOf(".") + 1);
//			String fileId = dataObj == null ? null : (String) Util.getValueOfProperty(dataObj, propertyFileId);
//			if (Formater.isNull(fileId))
//				return "";
			String temp = String.format(FIELD_DOWNLOAD, new Object[] {dwnloadInf[0], dwnloadInf[1]});
			return temp;

			// <a href="#" onclick="upload()"><i class="fa fa-upload"></i>Tải file</a>
		}
		lg.info(this);
		throw new ResourceException("DataSource type not valid");
	}

	private static final Logger lg = LogManager.getLogger(DictTemp.class);
	/**
	 * [lable, class, name, maxlength, value]
	 */
	private static final String FIELD_INPUT = "<input type= 'text' onchange='updateSameControl($(this))' name = '%s' %s class = '%s' value = '%s'/>";

	/**
	 * [lable, class, name, maxlength, value]
	 */
	private static final String HTML_FIELD_INPUT_READONLY = "<div class=\"%s\"%s>%s</div>\n"
			+ "<div class=\"%s\"><input onchange=\"updateSameControl($(this))\" class=\"%s\" name=\'%s\' maxlength=\"%s\" value=\"%s\" type=\"text\" readonly=\"readonly\" ></div>\n";

	
	/**
	 * [lable, class, name, maxlength, value]
	 */
	private static final String HTML_FIELD_TXT_READONLY =  "<input style='border:none;' type= 'text' onchange='updateSameControl($(this))' name = '%s' %s class = '%s' value = '%s'/>";

	
	/**
	 * [lable, class, name, maxlength, value]
	 */
	private static final String HTML_FIELD_INPUT_HIDDEN = "<div class=\"%s\"%s>%s</div>\n"
			+ "<div class=\"%s\"><input onchange=\"updateSameControl($(this))\" class=\"%s\" name=\'%s\' maxlength=\"%s\" value=\"%s\" type=\"hidden\" ></div>\n";

	
	/**
	 * [lable, class, name, value],option
	 */
	private static final String FIELD_SELECT = "<select onchange='updateSameControl($(this))' class='%s' name='%s' value='%s'>%s</select>";

	/**
	 * [lable, class, name, maxlength, value]
	 */
	private static final String FIELD_TEXT_AREA = "<textarea onchange='updateSameControl($(this))' class='%s' name='%s' rows='4' maxlength='%s'>%s</textarea>";

	/**
	 * [lable, class, name, value]
	 */
	private static final String FIELD_DATE = "<input onchange='updateSameControl($(this))' class='date %s' name='%s' value='%s' type='text'>";

	/**
	 * [lable, class, name, value]
	 */
	private static final String FIELD_DATE_TIME = "<input onchange='updateSameControl($(this))' class='dateTime %s' name='%s' value='%s' type='text'>";

	/**
	 * [linkUrl, lable]
	 */
	private static final String FIELD_LINK = "<a href='#' onClick = 'window.open(\"%s\")'>%s</a>";

	/**
	 * [lable, class, name, value]
	 */
	private static final String FIELD_CHECK_BOX = "<input onchange='updateSameControl($(this))' class='%s' name='%s' value='%s' %s type='checkbox'>";
	private static final String FIELD_HIDDEN = "<input type='hidden' id = '%s' name = '%s'  value = '%s'/>";

	/**
	 * [radioElement]
	 */
	private static final String FIELD_RADIO = "%s%s";

	private static final String FIELD_OPTIONS = "<option value=\"%s\"%s>%s</option>\n";

	/**
	 * [id, name, value, checked, for, label]
	 */
	private static final String FIELD_RADIO_ELE = "<label><input type=\"radio\" id=\"%s\"  name=\\'%s\\' value=\"%s\" %s onClick = \"hideGroup($('%s'), $(this));showGroup($('.%s'), $(this)); $('input[type=\\'hidden\\'][name=\\'%s\\']').val($(this).val());updateSameControl($(this));\">%s</label>";
	private static final String FIELD_UPLOAD = "<a href='#' onclick='uploadECM(\\\"%s\\\",this,\\\"%s\\\")'><i class='fa fa-upload'></i>Upload</a>";
	private static final String FIELD_DOWNLOAD = "<a  href='#' onclick='downloadECM(this,\\\"%s\\\",\\\"%s\\\")'><i class='fa fa-download'></i>download</a>";
	public static final String DATA_TYPE_NUM = "NUMBER";
	public static final String DATA_TYPE_DATE = "DATE";

	private String getCssClass(String dataType) {
		if (Formater.isNull(dataType))
			return "";
		if (dataType.toLowerCase().startsWith("number"))
			return DATA_TYPE_NUM;
		return dataType;
	}

	private boolean isInputControl(String controlType) {
		if ("text".equals(controlType) || ControlType.GRDCLM_TEXT.equals(controlType))
			return true;
		if ("textdigit".equals(controlType) || ControlType.GRDCLM_TEXTDIGITS.equals(controlType))
			return true;
		if (ControlType.TEXTINT.equals(controlType) || ControlType.GRDCLM_TEXTINT.equals(controlType))
			return true;
		if ("hidden".equals(controlType) || ControlType.GRDCLM_HIDDEN.equals(controlType))
			return true;
		return false;
	}

	@Transient
	public Boolean getDisplayInOneLine() {
		return displayInOneLine;
	}

	public void setDisplayInOneLine(Boolean displayInOneLine) {
		this.displayInOneLine = displayInOneLine;
	}

	public void setControlType(String controlType) {
		this.controlType = controlType;
	}

	@Transient
	public String getControlType() {
		return controlType;
	}

	private String[] renderRadios(DictMeasure dictMeasure, String value) {
		String[] arrStrResult = new String[2];
		String htmlObject = "";

		ArrayList<SysDictParam> sortedParam = null;
		if (!Formater.isNull(dictType.getSysDictParams())) {
			sortedParam = new ArrayList<SysDictParam>(dictType.getSysDictParams());
			Collections.sort(sortedParam, new Comparator<SysDictParam>() {
				@Override
				public int compare(final SysDictParam before, SysDictParam afer) {
					try {

						if (Formater.isNull(before.getDisOrder())) {
							if (!Formater.isNull(afer.getDisOrder()))
								return -1;
							else
								return 0;
						}
						if (Formater.isNull(afer.getDisOrder()))
							return 1;
						return before.getDisOrder().compareTo(afer.getDisOrder());
					} catch (Exception ex) {
						return 0;
					}
				}
			});
		}

		boolean checked = false;
		for (SysDictParam dict : sortedParam) {
			if (((Formater.isNull(value) || dict.getId().equals(value))) && !checked) {
				String parentVal = String.valueOf(this.getDictType().getId());
				String id = dictMeasure.getPath();
				String name = this.getTemplates().getId() + dictMeasure.getPath();
				String svalue = dict.getId();
				arrStrResult[1] = svalue;
				String schecked = "checked";
				String onClickEvt = (this.getParentCtrl() != null && this.getParentCtrl()) ? "showGroup($(this)); "
						: "";
				onClickEvt += "$('input[type=\\'hidden\\'][name=\\'" + dictMeasure.getPath()
						+ "\\']').val($(this).val());updateSameControl($(this));";
				String sClass = (this.getParentCtrl() != null && this.getParentCtrl() ? "radioPanel " : "") + parentVal
						+ " " + dict.getCode();
				String label = dict.getDescription();
				Object[] attr = new Object[] { parentVal, id, name, svalue, schecked, onClickEvt, sClass, label };
				htmlObject += String.format(HTML_FIELD_RADIO_ELE, attr);
				checked = true;
				if (this.getParentCtrl() != null && this.getParentCtrl())
					htmlObject += String.format(EVENT_RADIO,
							new Object[] { "$('." + this.getDictType().getId() + "." + dict.getCode() + "')" });

			} else {
				String parentVal = String.valueOf(this.getDictType().getId());
				String id = dictMeasure.getPath();
				String name = this.getTemplates().getId() + dictMeasure.getPath();
				String svalue = dict.getId();
				String schecked = "";
				String onClickEvt = (this.getParentCtrl() != null && this.getParentCtrl()) ? "showGroup($(this)); "
						: "";
				onClickEvt += "$('input[type=\\'hidden\\'][name=\\'" + dictMeasure.getPath()
						+ "\\']').val($(this).val());updateSameControl($(this));";
				String sClass = (this.getParentCtrl() != null && this.getParentCtrl() ? "radioPanel " : "") + parentVal
						+ " " + dict.getCode();
				String label = dict.getDescription();
				Object[] attr = new Object[] { parentVal, id, name, svalue, schecked, onClickEvt, sClass, label };
				htmlObject += String.format(HTML_FIELD_RADIO_ELE, attr);
			}
		}
		arrStrResult[0] = htmlObject;
		return arrStrResult;
	}

	@Transient
	public Boolean getParentCtrl() {
		return parentCtrl;
	}

	public void setParentCtrl(Boolean parentCtrl) {
		this.parentCtrl = parentCtrl;
	}

	/**
	 * [id, name, value, checked, for, label]
	 */
	private static final String HTML_FIELD_RADIO_ELE = "<label><input parentVal=\"%s\" type=\"radio\" id=\"%s\"  name=\\'%s\\' value=\"%s\" %s onClick = \"%s\" class = \"%s\">%s</label>";

	private static final String EVENT_RADIO = "<script language=\"javascript\" type=\"text/javascript\"> $(document).ready(function () {showGroup(%s);});</script>";

	private static final String EVENT_CK_EDITTOR = "<script language=\"javascript\" type=\"text/javascript\"> $(document).ready(function () {CKEDITOR.replace( \"%s\", {} );"
			+ " CKEDITOR.instances[\"%s\"].on('change', function() {"
			+ " $('textarea[name=\"%s\"]').val(CKEDITOR.instances[\"%s\"].getData());});\r\n" + " });</script>";
	private static final String HTML_FIELD_CK_EDITOR = "<div class=\"Row %s\"> " + "<div class=\"%s\">%s</div>\n"
			+ "<div class=\"%s\"><textarea onchange=\"updateSameControl($(this))\" class=\"%s\" name=\'%s\' rows=\"4\" maxlength=\"%s\">%s</textarea></div></div>\n";

	public String renderOptions(JSONArray listDataSelect, String value) {
		if(listDataSelect==null)
			return "";
		String htmlObject = "";
		try {
			if (listDataSelect != null) {
				for (int i = 0; i < listDataSelect.length(); i++) {
					JSONObject object = listDataSelect.getJSONObject(i);
					if (object.get("value").toString().equals(value))
						htmlObject += String.format(HTML_FIELD_OPTIONS, new Object[] { object.get("value").toString(),
								" selected", object.get("display").toString() });
					else
						htmlObject += String.format(HTML_FIELD_OPTIONS,
								new Object[] { object.get("value").toString(), "", object.get("display").toString() });
				}
			}
			
		} catch (JSONException ex) {
			lg.error("Loi", ex);
		}

		return htmlObject;
	}
	/**
	 * [radioElement]
	 */
	private static final String HTML_FIELD_RADIO = "<div class=\"Row %s\">\n"
			+ "<div class=\"col-md-2 col-lg-2 col-sm-12 col-xs-12\">%s</div>\n"
			+ "<div class=\"col-md-10 col-lg-10 col-sm-12 col-xs-12\">%s</div>\n" + "</div>";
	private static final String HTML_FIELD_OPTIONS = "<option value='%s'%s>%s</option>";
	private static final String HTML_FIELD_HIDDEN = "<input type='hidden' id = '%s' name = '%s'  value = '%s'/>";

	public String draw(Object profile) throws Exception {
		String htmlControl = drawControl(profile);
		if (!Formater.isNull(htmlControl)) {
			if (this.displayInOneLine != null && this.displayInOneLine) {
				if (!ControlType.RADIO.equals(this.controlType) && !ControlType.TEXTAREA.equals(this.controlType)
						&& !ControlType.CKEDITOR.equals(this.controlType))
					htmlControl = "<div class =\"Row\">" + htmlControl + "</div>";
			}
		}
		return htmlControl;
	}

	private String drawControl(Object profile) throws Exception {

		// Input
		String sValue = this.value == null ? "" : this.value.toString();
		if (isInputControl(this.controlType)) {
			// [lable, class, name, value]
			return String.format(HTML_FIELD_INPUT,
					new Object[] { this.bsLabelCss, Formater.isNull(this.title) ? "" : "title='" + this.title + "'",
							this.label, this.bsInputCss, this.sclass, dictMeasure.getPath(), this.maxlength, sValue });
		}
		if (ControlType.CHECKBOX.equals(this.controlType)) {
			if (!Formater.isNull(this.sclass) && this.sclass.indexOf("number") >= 0)
				this.sclass = this.sclass.replaceAll("number", "");
			String temp = String.format(HTML_FIELD_CHECK_BOX,
					new Object[] { this.bsLabelCss, this.label, this.bsInputCss, this.sclass, dictMeasure.getPath(),
							"true", this.value == null ? "" : (Boolean) this.value ? "checked" : "" });
			return temp;
		}
		if (ControlType.CHK_GRP.equals(this.controlType)) {
			if (!Formater.isNull(this.sclass) && this.sclass.indexOf("number") >= 0)
				this.sclass = this.sclass.replaceAll("number", "");
			this.sclass += " " + dictMeasure.getId() + " " + ControlType.CHK_GRP;
			String temp = String.format(HTML_FIELD_CHECK_BOX_GRP,
					new Object[] { this.bsLabelCss, this.label, this.bsInputCss, this.sclass, dictMeasure.getPath(),
							"true", this.value == null ? "" : (Boolean) this.value ? "checked" : "",
							String.valueOf(dictMeasure.getId()) });
			return temp;
		}
		if (ControlType.RADIO.equals(this.controlType)) {
			if (this.getDictType() == null) {
				return "";
			} else {
				String[] arrStrResult = renderRadios(dictMeasure, sValue);
				String htmlRadioEle = arrStrResult[0];
				String temp = String.format(HTML_FIELD_RADIO,
						new Object[] { this.getGroupClass(), this.label, htmlRadioEle });
				// Bo sung hidden field luu gia tri cua radio
				temp += String.format(HTML_FIELD_HIDDEN, new Object[] { this.getDictMeasure().getPath(),
						this.getDictMeasure().getPath(), Formater.isNull(sValue) ? arrStrResult[1] : sValue });
				return temp;
			}

		}
		if (ControlType.DATE.equals(this.controlType)) {
			// [lable, class, name, value]
			String temp = String.format(HTML_FIELD_DATE, new Object[] { this.bsLabelCss, this.label, this.bsInputCss,
					this.sclass, dictMeasure.getPath(), sValue, "" });
			return temp;
		}
		if (ControlType.DATM.equals(this.controlType)) {
			// [lable, class, name, value]
			String temp = String.format(HTML_FIELD_DATE_TIME, new Object[] { this.bsLabelCss, this.label,
					this.bsInputCss, this.sclass, dictMeasure.getPath(), sValue, "" });
			return temp;
		}
		if (ControlType.TEXTAREA.equals(this.controlType)) {
			// [lable, class, name, value]
			String temp = String.format(HTML_FIELD_TEXT_AREA,
					new Object[] { Formater.isNull(this.groupClass) ? "" : this.groupClass, this.bsLabelCss, this.label,
							this.bsInputCss, this.sclass, dictMeasure.getPath(), this.maxlength, sValue });
			return temp;
		}

		if (ControlType.CKEDITOR.equals(this.controlType)) {
			// [lable, class, name, value]
			String temp = String.format(HTML_FIELD_CK_EDITOR,
					new Object[] { Formater.isNull(this.groupClass) ? "" : this.groupClass, this.bsLabelCss, this.label,
							this.bsInputCss, this.sclass, dictMeasure.getPath(), this.maxlength, sValue });
			temp += String.format(EVENT_CK_EDITTOR, new Object[] { dictMeasure.getPath(), dictMeasure.getPath(),
					dictMeasure.getPath(), dictMeasure.getPath() });
			return temp;
		}
		
		if (ControlType.INPUT_READONLY.equals(controlType)) {
			// [lable, class, name, value]
			return String.format(HTML_FIELD_INPUT_READONLY, new Object[] { this.bsLabelCss,Formater.isNull(this.title) ? "" : "title='" + this.title + "'", 
					this.label, this.bsInputCss, this.sclass, dictMeasure.getPath(), this.maxlength, sValue });
		} 

		if (ControlType.SELECT.equals(this.controlType)) {
			String htmlOption = this.getDictType() == null ? renderOptions(dictMeasure.getListDataSelect(), sValue)
					: renderOptions(sValue);
			String temp = String.format(HTML_FIELD_SELECT, new Object[] { this.bsLabelCss, this.label, this.bsInputCss,
					this.sclass, dictMeasure.getPath(), sValue, htmlOption });
			return temp;
		}
		if (ControlType.LINK.equals(this.controlType)) {
			String linkUrl = "";
			if (profile != null) {
				Long profileId = (Long) profile.getClass().getMethod("getId").invoke(profile);
				linkUrl = dictMeasure.getPath() + profileId;
			}
			String temp = String.format(HTML_FIELD_LINK, new Object[] { linkUrl, this.label });
			return temp;
		} else if (ControlType.TITLE.equals(this.controlType)) {
			return "";
		}

		// TODO: bo sung class neu item thuoc checkbox group
		throw new ResourceException("DataSource type not valid");
	}
	private String renderOptions(String value) {
		String htmlObject = String.format(HTML_FIELD_OPTIONS, new Object[] { "", "", "" });
		Collections.sort(dictType.getSysDictParams(), new Comparator<SysDictParam>() {
			@Override
			public int compare(final SysDictParam before, SysDictParam afer) {
				try {

					if (Formater.isNull(before.getDisOrder())) {
						if (!Formater.isNull(afer.getDisOrder()))
							return -1;
						else
							return 0;
					}
					if (Formater.isNull(afer.getDisOrder()))
						return 1;
					return before.getDisOrder().compareTo(afer.getDisOrder());
				} catch (Exception ex) {
					return 0;
				}
			}
		});
		for (SysDictParam dict : dictType.getSysDictParams()) {
			if (dict.getId().equals(value))
				htmlObject += String.format(HTML_FIELD_OPTIONS,
						new Object[] { dict.getId(), " selected", dict.getValue() });
			else
				htmlObject += String.format(HTML_FIELD_OPTIONS, new Object[] { dict.getId(), "", dict.getValue() });
		}

		return htmlObject;
	}

	private static final String HTML_FIELD_SELECT = "<div class=\"%s\">%s</div>\n"
			+ "<div class=\"%s\"><select onchange=\"updateSameControl($(this))\" class=\"%s\" name=\'%s\' value=\"%s\">%s</select></div>\n";
	/**
	 * [linkUrl, lable]
	 */
	private static final String HTML_FIELD_LINK = "<div class=\"label-static col-md-2 col-lg-2 col-sm-12 col-xs-12\"><a href=\"#\" onClick = \"window.open('%s&type=subForm','',window_property)\">%s</a></div><div class=\"col-md-3 col-lg-3 col-sm-12 col-xs-12\"></div>";

	private static final String HTML_FIELD_CHECK_BOX = "<div class=\"%s\">%s</div>\n"
			+ "<div class=\"%s\"><input onchange=\"updateSameControl($(this))\" class=\"%s\" name=\'%s\' value=\"%s\" %s type=\"checkbox\"></div>\n";

	private static final String HTML_FIELD_CHECK_BOX_GRP = "<div class=\"%s\">%s</div>\n"
			+ "<div class=\"%s\"><input onchange=\"updateSameControl($(this))\" class=\"%s\" name=\'%s\' value=\"%s\" %s type=\"checkbox\" id=\"%s\"></div>\n";
	/**
	 * [lable, class, name, maxlength, value]
	 */
	private static final String HTML_FIELD_TEXT_AREA = "<div class=\"Row %s\"> " + "<div class=\"%s\">%s</div>\n"
			+ "<div class=\"%s\"><textarea onchange=\"updateSameControl($(this))\" class=\"%s\" name=\'%s\' rows=\"4\" maxlength=\"%s\">%s</textarea></div></div>\n";

	
	/**
	 * [lable, class, name, value]
	 */
	private static final String HTML_FIELD_DATE = "<div class=\"%s\">%s</div>\n"
			+ "<div class=\"%s\"><input onchange=\"updateSameControl($(this))\" class=\"date %s\" name=\'%s\' value=\"%s\" type=\"text\"></div>\n";

	/**
	 * [lable, class, name, value] Style on top
	 */
	private static final String HTML_FIELD_DATE_TIME = "<div class=\"%s\">%s</div>\n"
			+ "<div class=\"%s\"><input style=\"position: relative;z-index:100000;\" onchange=\"updateSameControl($(this))\" readOnly=\"true\" class=\"dateTime %s\" name=\'%s\' value=\"%s\" type=\"text\"></div>\n";

	

	/**
	 * [lable, class, name, maxlength, value]
	 */
	private static final String HTML_FIELD_INPUT = "<div class=\"%s\" %s>%s</div>\n"
			+ "<div class=\"%s\"><input onchange=\"updateSameControl($(this))\" class=\"%s\" name=\'%s\' maxlength=\"%s\" value=\"%s\" type=\"text\" ></div>\n";
	@Transient
	public String getRealControlType() {
		return realControlType;
	}
	
	public void setRealControlType(String realControlType) {
		this.realControlType = realControlType;
	}

	
}
