package entity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DictGrp generated by hbm2java
 */
@Entity
@Table(name = "DICT_GRP", schema = "POC")
public class DictGrp implements java.io.Serializable {

	private Long id;
	private String objectId;
	private String objectName;
	private Long objectLevel;
	private String objectParent;
	private String objectSubject;
	private String objectDesc;
	private String objectType;
	private Long objectPosition;

	public DictGrp() {
	}

	public DictGrp(Long id) {
		this.id = id;
	}

	public DictGrp(Long id, String objectId, String objectName, Long objectLevel, String objectParent,
			String objectSubject, String objectDesc, String objectType, Long objectPosition) {
		this.id = id;
		this.objectId = objectId;
		this.objectName = objectName;
		this.objectLevel = objectLevel;
		this.objectParent = objectParent;
		this.objectSubject = objectSubject;
		this.objectDesc = objectDesc;
		this.objectType = objectType;
		this.objectPosition = objectPosition;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "OBJECT_ID", length = 20)
	public String getObjectId() {
		return this.objectId;
	}

	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}

	@Column(name = "OBJECT_NAME", length = 30)
	public String getObjectName() {
		return this.objectName;
	}

	public void setObjectName(String objectName) {
		this.objectName = objectName;
	}

	@Column(name = "OBJECT_LEVEL", precision = 22, scale = 0)
	public Long getObjectLevel() {
		return this.objectLevel;
	}

	public void setObjectLevel(Long objectLevel) {
		this.objectLevel = objectLevel;
	}

	@Column(name = "OBJECT_PARENT", length = 20)
	public String getObjectParent() {
		return this.objectParent;
	}

	public void setObjectParent(String objectParent) {
		this.objectParent = objectParent;
	}

	@Column(name = "OBJECT_SUBJECT", length = 20)
	public String getObjectSubject() {
		return this.objectSubject;
	}

	public void setObjectSubject(String objectSubject) {
		this.objectSubject = objectSubject;
	}

	@Column(name = "OBJECT_DESC", length = 100)
	public String getObjectDesc() {
		return this.objectDesc;
	}

	public void setObjectDesc(String objectDesc) {
		this.objectDesc = objectDesc;
	}

	@Column(name = "OBJECT_TYPE", length = 20)
	public String getObjectType() {
		return this.objectType;
	}

	public void setObjectType(String objectType) {
		this.objectType = objectType;
	}

	@Column(name = "OBJECT_POSITION", precision = 22, scale = 0)
	public Long getObjectPosition() {
		return this.objectPosition;
	}

	public void setObjectPosition(Long objectPosition) {
		this.objectPosition = objectPosition;
	}

}
