package entity;

// Generated Jan 6, 2021 10:10:52 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.json.JSONArray;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * DictMeasure generated by hbm2java
 */
@Entity
@Table(name = "DICT_MEASURE", schema = "POC")
public class DictMeasure implements java.io.Serializable {
	 
	private Long id;
	@JsonIgnore
	private DictGrp dictGrp;
	private String subject;
	private String level1;
	private String level2;
	private String colCode;
	private String dataType;
	private String colLength;
	private String colTbl;
	private String colKey;
	private String colDesc;
	private String colView;
	private String colField;
	private String parentTbl;
	private String parentField;
	private String refTbl;
	private String refFieldChild;
	private String refFieldParent;
	private Date updDate;
	private String updBy;
	private String dataSource;
	private String selectData;
	private String path;
	private String backUpColLength;
	private JSONArray listDataSelect;
	public DictMeasure() {
	}

	public DictMeasure(Long id, DictGrp dictGrp, String datasource) {
		this.id = id;
		this.dictGrp = dictGrp;
		this.dataSource = datasource;
	}


	@Id
	@Column(name = "ID")
	@SequenceGenerator(name = "DICT_MEAS_ID", sequenceName = "DICT_MEAS_ID")
	@GeneratedValue(generator = "DICT_MEAS_ID")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DIC_GROUP_ID")
	public DictGrp getDictGrp() {
		return this.dictGrp;
	}

	public void setDictGrp(DictGrp dictGrp) {
		this.dictGrp = dictGrp;
	}

	@Column(name = "SUBJECT", length = 20)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "LEVEL1", length = 30)
	public String getLevel1() {
		return this.level1;
	}

	public void setLevel1(String level1) {
		this.level1 = level1;
	}

	@Column(name = "LEVEL2", length = 30)
	public String getLevel2() {
		return this.level2;
	}

	public void setLevel2(String level2) {
		this.level2 = level2;
	}

	@Column(name = "COL_CODE", length = 1000)
	public String getColCode() {
		return this.colCode;
	}

	public void setColCode(String colCode) {
		this.colCode = colCode;
	}

	@Column(name = "DATA_TYPE", length = 20)
	public String getDataType() {
		return this.dataType;
	}

	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

	@Column(name = "COL_LENGTH", length = 20)
	public String getColLength() {
		return this.colLength;
	}

	public void setColLength(String colLength) {
		this.colLength = colLength;
	}

	@Column(name = "COL_TBL", length = 40)
	public String getColTbl() {
		return this.colTbl;
	}

	public void setColTbl(String colTbl) {
		this.colTbl = colTbl;
	}

	@Column(name = "COL_KEY", length = 30)
	public String getColKey() {
		return this.colKey;
	}

	public void setColKey(String colKey) {
		this.colKey = colKey;
	}

	@Column(name = "COL_DESC", length = 2000)
	public String getColDesc() {
		return this.colDesc;
	}

	public void setColDesc(String colDesc) {
		this.colDesc = colDesc;
	}

	@Column(name = "COL_VIEW", length = 30)
	public String getColView() {
		return this.colView;
	}

	public void setColView(String colView) {
		this.colView = colView;
	}

	@Column(name = "COL_FIELD", length = 50)
	public String getColField() {
		return this.colField;
	}

	public void setColField(String colField) {
		this.colField = colField;
	}

	@Column(name = "PARENT_TBL", length = 50)
	public String getParentTbl() {
		return this.parentTbl;
	}

	public void setParentTbl(String parentTbl) {
		this.parentTbl = parentTbl;
	}

	@Column(name = "PARENT_FIELD", length = 50)
	public String getParentField() {
		return this.parentField;
	}

	public void setParentField(String parentField) {
		this.parentField = parentField;
	}

	@Column(name = "REF_TBL", length = 50)
	public String getRefTbl() {
		return this.refTbl;
	}

	public void setRefTbl(String refTbl) {
		this.refTbl = refTbl;
	}

	@Column(name = "REF_FIELD_CHILD", length = 50)
	public String getRefFieldChild() {
		return this.refFieldChild;
	}

	public void setRefFieldChild(String refFieldChild) {
		this.refFieldChild = refFieldChild;
	}

	@Column(name = "REF_FIELD_PARENT", length = 50)
	public String getRefFieldParent() {
		return this.refFieldParent;
	}

	public void setRefFieldParent(String refFieldParent) {
		this.refFieldParent = refFieldParent;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPD_DATE", length = 7)
	public Date getUpdDate() {
		return this.updDate;
	}

	public void setUpdDate(Date updDate) {
		this.updDate = updDate;
	}

	@Column(name = "UPD_BY", length = 50)
	public String getUpdBy() {
		return this.updBy;
	}

	public void setUpdBy(String updBy) {
		this.updBy = updBy;
	}

	@Column(name = "DATASOURCE")
	public String getDataSource() {
		return this.dataSource;
	}

	public void setDataSource(String datasource) {
		this.dataSource = datasource;
	}

	@Column(name = "SELECT_DATA", length = 3000)
	public String getSelectData() {
		return this.selectData;
	}

	public void setSelectData(String selectData) {
		this.selectData = selectData;
	}

	@Column(name = "PATH", length = 300)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "BACK_UP_COL_LENGTH", length = 20)
	public String getBackUpColLength() {
		return this.backUpColLength;
	}

	public void setBackUpColLength(String backUpColLength) {
		this.backUpColLength = backUpColLength;
	}
	@Transient
	public JSONArray getListDataSelect() {
		return listDataSelect;
	}

	public void setListDataSelect(JSONArray listDataSelect) {
		this.listDataSelect = listDataSelect;
	}

}
