package entity;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;

// Generated Jan 6, 2021 10:10:52 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.hibernate.annotations.GenericGenerator;

import common.util.Formater;
import common.util.ResourceException;
import common.util.Util;

/**
 * PocUserinfoForm generated by hbm2java
 */
@Entity
@Table(name = "POC_USERINFO_FORM")
public class PocUserinfoForm implements java.io.Serializable {
	private static final Logger logger = LogManager.getLogger(PocUserinfoForm.class);
	private static final long serialVersionUID = 1L;
	private String id;
	private String name;
	private Date dateOfBirthday;
	private String dateOfBirthdayStr;
	private String placeOfBirth;
	private String sex;
	private String nation;
	private String nationality;
	private String cardId;
	private Date dateCardRange;
	private String dateCardRangeStr;
	private String placeCard;
	private String cardIdOther;
	private Date dateCardRangeOther;
	private String dateCardRangeOtherStr;
	private String placeCardOther;
	private String address;
	private String permanentAddress;
	private String phoneNumber;
	private String email;
	private String personInvolved;
	private String relationship;
	private String phoneNumberRelationship;
	private String academicLevel;
	private String insurranceCode;
	private String insurranceCompany;
	private Date insurranceDateRange;
	private String insurranceDateRangeStr;
	private String classId;
	private String questionId;
	private String localRecruitment;
	private String formRecruitment;
	private Short status;
	private Short subStatus;
	private String action;
	private AppFlow appFlow;
	private String statusCode;
	private String createId;
	private String buId;
	private Date createDt;
	private String description;
	private String activeCode;

	private String templateId;

	public PocUserinfoForm() {
	}

	public PocUserinfoForm(String id) {
		this.id = id;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 40)
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		if (Formater.isNull(id))
			this.id = null;
		else
			this.id = id;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_OF_BIRTHDAY", length = 7)
	public Date getDateOfBirthday() {
		return this.dateOfBirthday;
	}

	public void setDateOfBirthday(Date dateOfBirthday) {
		this.dateOfBirthday = dateOfBirthday;
		this.dateOfBirthdayStr = Formater.date2str(this.dateOfBirthday);
	}

	@Column(name = "PLACE_OF_BIRTH", length = 100)
	public String getPlaceOfBirth() {
		return this.placeOfBirth;
	}

	public void setPlaceOfBirth(String placeOfBirth) {
		this.placeOfBirth = placeOfBirth;
	}

	@Column(name = "NATION", length = 100)
	public String getNation() {
		return this.nation;
	}

	@Column(name = "SEX")
	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	@Column(name = "NATIONALITY", length = 100)
	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	@Column(name = "CARD_ID", length = 40)
	public String getCardId() {
		return this.cardId;
	}

	public void setCardId(String cardId) {
		this.cardId = cardId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_CARD_RANGE", length = 7)
	public Date getDateCardRange() {
		return this.dateCardRange;
	}

	public void setDateCardRange(Date dateCardRange) {
		this.dateCardRange = dateCardRange;
		this.dateCardRangeStr = Formater.date2str(dateCardRange);
	}

	@Transient
	public String getDateCardRangeStr() {
		return dateCardRangeStr;
	}

	public void setDateCardRangeStr(String dateCardRangeStr) throws Exception {
		this.dateCardRangeStr = dateCardRangeStr;
		this.dateCardRange = Formater.str2date(this.dateCardRangeStr);
	}

	@Column(name = "PLACE_CARD", length = 200)
	public String getPlaceCard() {
		return this.placeCard;
	}

	public void setPlaceCard(String placeCard) {
		this.placeCard = placeCard;
	}

	@Column(name = "CARD_ID_OTHER", length = 40)
	public String getCardIdOther() {
		return this.cardIdOther;
	}

	public void setCardIdOther(String cardIdOther) {
		this.cardIdOther = cardIdOther;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_CARD_RANGE_OTHER", length = 7)
	public Date getDateCardRangeOther() {
		return this.dateCardRangeOther;
	}

	public void setDateCardRangeOther(Date dateCardRangeOther) {
		this.dateCardRangeOther = dateCardRangeOther;
		this.dateCardRangeOtherStr = Formater.date2str(this.getDateCardRangeOther());
	}

	@Transient
	public String getDateCardRangeOtherStr() {
		return dateCardRangeOtherStr;
	}

	public void setDateCardRangeOtherStr(String dateCardRangeOtherStr) throws Exception {
		this.dateCardRangeOtherStr = dateCardRangeOtherStr;
		this.dateCardRangeOther = Formater.str2date(this.getDateCardRangeOtherStr());
	}

	@Column(name = "PLACE_CARD_OTHER", length = 200)
	public String getPlaceCardOther() {
		return this.placeCardOther;
	}

	public void setPlaceCardOther(String placeCardOther) {
		this.placeCardOther = placeCardOther;
	}

	@Column(name = "ADDRESS", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "PERMANENT_ADDRESS", length = 200)
	public String getPermanentAddress() {
		return this.permanentAddress;
	}

	public void setPermanentAddress(String permanentAddress) {
		this.permanentAddress = permanentAddress;
	}

	@Column(name = "PHONE_NUMBER", length = 10)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PERSON_INVOLVED", length = 100)
	public String getPersonInvolved() {
		return this.personInvolved;
	}

	public void setPersonInvolved(String personInvolved) {
		this.personInvolved = personInvolved;
	}

	@Column(name = "RELATIONSHIP", length = 100)
	public String getRelationship() {
		return this.relationship;
	}

	public void setRelationship(String relationship) {
		this.relationship = relationship;
	}

	@Column(name = "PHONE_NUMBER_RELATIONSHIP", length = 10)
	public String getPhoneNumberRelationship() {
		return this.phoneNumberRelationship;
	}

	public void setPhoneNumberRelationship(String phoneNumberRelationship) {
		this.phoneNumberRelationship = phoneNumberRelationship;
	}

	@Column(name = "ACADEMIC_LEVEL", length = 40)
	public String getAcademicLevel() {
		return this.academicLevel;
	}

	public void setAcademicLevel(String academicLevel) {
		this.academicLevel = academicLevel;
	}

	@Column(name = "INSURRANCE_CODE", length = 40)
	public String getInsurranceCode() {
		return this.insurranceCode;
	}

	public void setInsurranceCode(String insurranceCode) {
		this.insurranceCode = insurranceCode;
	}

	@Column(name = "INSURRANCE_COMPANY", length = 200)
	public String getInsurranceCompany() {
		return this.insurranceCompany;
	}

	public void setInsurranceCompany(String insurranceCompany) {
		this.insurranceCompany = insurranceCompany;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "INSURRANCE_DATE_RANGE", length = 7)
	public Date getInsurranceDateRange() {
		return this.insurranceDateRange;
	}

	public void setInsurranceDateRange(Date insurranceDateRange) {
		this.insurranceDateRange = insurranceDateRange;
		this.insurranceDateRangeStr = Formater.date2str(this.insurranceDateRange);
	}

	@Column(name = "CLASS_ID", length = 40)
	public String getClassId() {
		return this.classId;
	}

	public void setClassId(String classId) {
		this.classId = classId;
	}

	@Column(name = "QUESTION_ID", length = 40)
	public String getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(String questionId) {
		this.questionId = questionId;
	}

	@Column(name = "LOCAL_RECRUITMENT", length = 40)
	public String getLocalRecruitment() {
		return this.localRecruitment;
	}

	public void setLocalRecruitment(String localRecruitment) {
		this.localRecruitment = localRecruitment;
	}

	@Column(name = "FORM_RECRUITMENT", length = 40)
	public String getFormRecruitment() {
		return this.formRecruitment;
	}

	public void setFormRecruitment(String formRecruitment) {
		this.formRecruitment = formRecruitment;
	}

	@Column(name = "STATUS")
	public Short getStatus() {
		return status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	@Column(name = "SUB_STATUS")
	public Short getSubStatus() {
		return subStatus;
	}

	public void setSubStatus(Short subStatus) {
		this.subStatus = subStatus;
	}

	@Transient
	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Transient
	private Boolean sortList;

	public void next(List<AppFlow> lstAppflow) throws ResourceException {
		for (int i = 0; i < lstAppflow.size(); i++) {
			if (equalStatus(lstAppflow.get(i))) {
				if (i == lstAppflow.size() - 1)
					throw new ResourceException("It's the last status, cannot change to next status");
				setAppFlow(lstAppflow.get(i + 1));
				return;
			}

		}

	}

	public void previos(List<AppFlow> lstAppflow) throws ResourceException {
		int i = lstAppflow.size() - 1;
		while (i >= 0) {
			if (equalStatus(lstAppflow.get(i))) {
				if (i == 0)
					throw new ResourceException("It's the first status, cannot change to previos status");
				setAppFlow(lstAppflow.get(i - 1));
				return;
			}

			i--;
		}
	}

	private boolean equalStatus(AppFlow appFlow) {
		if (!this.status.equals(appFlow.getStatus()))
			return false;
		if (appFlow.getSubStatus() == null) {
			if (this.getSubStatus() != null && this.getSubStatus() != 0)
				return false;
			return true;
		}
		return appFlow.getSubStatus().equals(this.getSubStatus());
	}

	@SuppressWarnings("unused")
	private void sort(List<AppFlow> appflow) {
		if (this.sortList)
			return;
		this.sortList = Boolean.TRUE;
		Collections.sort(appflow, new Comparator<AppFlow>() {
			@Override
			public int compare(AppFlow before, AppFlow after) {
				if (before.getStatus() == 0 || before.getStatus() == null)
					return 1;
				if (after.getStatus() == 0 || after.getStatus() == null)
					return -1;
				if (before.getStatus() < after.getStatus())
					return 1;
				if (before.getStatus() > after.getStatus())
					return -1;
				if (before.getSubStatus() == 0 || before.getSubStatus() == null)
					return 1;
				if (after.getSubStatus() == 0 || after.getSubStatus() == null)
					return -1;
				return before.getSubStatus().compareTo(before.getSubStatus());
			}
		});

	}

	@Transient
	public AppFlow getAppFlow() {
		return appFlow;
	}

	public void setAppFlow(AppFlow appFlow) {
		this.appFlow = appFlow;
		this.status = appFlow.getStatus();
		this.subStatus = appFlow.getSubStatus();
	}

	@Transient
	public String getStatusCode() {
		String statusCode = String.valueOf(this.status);
		if (this.subStatus != null)
			statusCode += "." + String.valueOf(this.subStatus);
		this.statusCode = statusCode;
		return this.statusCode;
	}

	@Column(name = "CREATE_ID", length = 40)
	public String getCreateId() {
		return createId;
	}

	public void setCreateId(String createId) {
		this.createId = createId;
	}

	@Column(name = "BU_ID", length = 40)
	public String getBuId() {
		return buId;
	}

	public void setBuId(String buId) {
		this.buId = buId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DT")
	public Date getCreateDt() {
		return createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Transient
	public String getDateOfBirthdayStr() {
		return dateOfBirthdayStr;
	}

	public void setDateOfBirthdayStr(String dateOfBirthdayStr) throws Exception {
		this.dateOfBirthdayStr = dateOfBirthdayStr;
		this.dateOfBirthday = Formater.str2date(this.dateOfBirthdayStr);
	}

	@Transient
	public String getInsurranceDateRangeStr() {
		return insurranceDateRangeStr;
	}

	public void setInsurranceDateRangeStr(String insurranceDateRangeStr) throws Exception {
		this.insurranceDateRangeStr = insurranceDateRangeStr;
		this.insurranceDateRange = Formater.str2date(this.insurranceDateRangeStr);
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	private List<PocFile> pocFiles = new ArrayList<PocFile>();
	private List<PocInterViewRs> pocInterViewRs = new ArrayList<PocInterViewRs>();

	@OneToMany(cascade = CascadeType.ALL, mappedBy = "userId")
	public List<PocFile> getPocFiles() {
		return pocFiles;
	}

	public void setPocFiles(List<PocFile> pocFiles) {
		this.pocFiles = pocFiles;
	}

	@OneToMany(cascade = CascadeType.ALL, mappedBy = "userId")
	public List<PocInterViewRs> getPocInterViewRs() {
		return pocInterViewRs;
	}

	public void setPocInterViewRs(List<PocInterViewRs> pocInterViewRs) {
		this.pocInterViewRs = pocInterViewRs;
	}

	@Transient
	public Object getValue(String path) {
		if (Formater.isNull(path))
			return "";
		try {
			return Util.getValueByPath(this, path);
		} catch (Exception e) {
			logger.error(e);
		}
		return "";
	}

	@Column(name = "TEMPLATE_ID")
	public String getTemplateId() {
		return templateId;
	}

	public void setTemplateId(String templateId) {
		this.templateId = templateId;
	}

	@Column(name = "ACTIVE_CODE")
	public String getActiveCode() {
		return activeCode;
	}

	public void setActiveCode(String activeCode) {
		this.activeCode = activeCode;
	}

}
