package entity;

// Generated Apr 10, 2020 2:07:06 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RpDetailK2K2b generated by hbm2java
 */
@Entity
@Table(name = "RP_DETAIL_K2_K2B", schema = "CIC")
public class RpDetailK2K2b implements java.io.Serializable {

	private String id;
	private RpSum rpSum;
	private String macn;
	private String tencn;
	private String ngaybaocao;
	private Boolean status;
	private String errorCode;
	private Date createdDate;
	private String createdBy;
	private Date modifiedDate;
	private String modifiedBy;
	private String bc001;
	private String bc002;
	private String bc003;
	private String bc004;
	private String bc005;
	private String bc006;
	private String bc007;
	private String cd100idx1;
	private String cd100idx2;
	private String cd110idx1;
	private String cd110idx2;
	private String cd111idx1;
	private String cd111idx2;
	private String cd112idx1;
	private String cd112idx2;
	private String cd120idx1;
	private String cd120idx2;
	private String cd121idx1;
	private String cd121idx2;
	private String cd122idx1;
	private String cd122idx2;
	private String cd123idx1;
	private String cd123idx2;
	private String cd124idx1;
	private String cd124idx2;
	private String cd130idx1;
	private String cd130idx2;
	private String cd131idx1;
	private String cd131idx2;
	private String cd132idx1;
	private String cd132idx2;
	private String cd133idx1;
	private String cd133idx2;
	private String cd134idx1;
	private String cd134idx2;
	private String cd135idx1;
	private String cd135idx2;
	private String cd136idx1;
	private String cd136idx2;
	private String cd137idx1;
	private String cd137idx2;
	private String cd138idx1;
	private String cd138idx2;
	private String cd139idx1;
	private String cd139idx2;
	private String cd140idx1;
	private String cd140idx2;
	private String cd141idx1;
	private String cd141idx2;
	private String cd142idx1;
	private String cd142idx2;
	private String cd149idx1;
	private String cd149idx2;
	private String cd150idx1;
	private String cd150idx2;
	private String cd151idx1;
	private String cd151idx2;
	private String cd152idx1;
	private String cd152idx2;
	private String cd153idx1;
	private String cd153idx2;
	private String cd154idx1;
	private String cd154idx2;
	private String cd155idx1;
	private String cd155idx2;
	private String cd160idx1;
	private String cd160idx2;
	private String cd161idx1;
	private String cd161idx2;
	private String cd162idx1;
	private String cd162idx2;
	private String cd170idx1;
	private String cd170idx2;
	private String cd180idx1;
	private String cd180idx2;
	private String cd181idx1;
	private String cd181idx2;
	private String cd182idx1;
	private String cd182idx2;
	private String cd200idx1;
	private String cd200idx2;
	private String cd210idx1;
	private String cd210idx2;
	private String cd211idx1;
	private String cd211idx2;
	private String cd212idx1;
	private String cd212idx2;
	private String cd213idx1;
	private String cd213idx2;
	private String cd214idx1;
	private String cd214idx2;
	private String cd215idx1;
	private String cd215idx2;
	private String cd216idx1;
	private String cd216idx2;
	private String cd219idx1;
	private String cd219idx2;
	private String cd220idx1;
	private String cd220idx2;
	private String cd221idx1;
	private String cd221idx2;
	private String cd222idx1;
	private String cd222idx2;
	private String cd223idx1;
	private String cd223idx2;
	private String cd224idx1;
	private String cd224idx2;
	private String cd225idx1;
	private String cd225idx2;
	private String cd226idx1;
	private String cd226idx2;
	private String cd227idx1;
	private String cd227idx2;
	private String cd228idx1;
	private String cd228idx2;
	private String cd229idx1;
	private String cd229idx2;
	private String cd230idx1;
	private String cd230idx2;
	private String cd231idx1;
	private String cd231idx2;
	private String cd232idx1;
	private String cd232idx2;
	private String cd240idx1;
	private String cd240idx2;
	private String cd241idx1;
	private String cd241idx2;
	private String cd242idx1;
	private String cd242idx2;
	private String cd250idx1;
	private String cd250idx2;
	private String cd251idx1;
	private String cd251idx2;
	private String cd252idx1;
	private String cd252idx2;
	private String cd253idx1;
	private String cd253idx2;
	private String cd254idx1;
	private String cd254idx2;
	private String cd255idx1;
	private String cd255idx2;
	private String cd260idx1;
	private String cd260idx2;
	private String cd261idx1;
	private String cd261idx2;
	private String cd262idx1;
	private String cd262idx2;
	private String cd263idx1;
	private String cd263idx2;
	private String cd268idx1;
	private String cd268idx2;
	private String cd269idx1;
	private String cd269idx2;
	private String cd270idx1;
	private String cd270idx2;
	private String cd300idx1;
	private String cd300idx2;
	private String cd310idx1;
	private String cd310idx2;
	private String cd311idx1;
	private String cd311idx2;
	private String cd312idx1;
	private String cd312idx2;
	private String cd313idx1;
	private String cd313idx2;
	private String cd314idx1;
	private String cd314idx2;
	private String cd315idx1;
	private String cd315idx2;
	private String cd316idx1;
	private String cd316idx2;
	private String cd317idx1;
	private String cd317idx2;
	private String cd318idx1;
	private String cd318idx2;
	private String cd319idx1;
	private String cd319idx2;
	private String cd320idx1;
	private String cd320idx2;
	private String cd321idx1;
	private String cd321idx2;
	private String cd322idx1;
	private String cd322idx2;
	private String cd323idx1;
	private String cd323idx2;
	private String cd324idx1;
	private String cd324idx2;
	private String cd330idx1;
	private String cd330idx2;
	private String cd331idx1;
	private String cd331idx2;
	private String cd332idx1;
	private String cd332idx2;
	private String cd333idx1;
	private String cd333idx2;
	private String cd334idx1;
	private String cd334idx2;
	private String cd335idx1;
	private String cd335idx2;
	private String cd336idx1;
	private String cd336idx2;
	private String cd337idx1;
	private String cd337idx2;
	private String cd338idx1;
	private String cd338idx2;
	private String cd339idx1;
	private String cd339idx2;
	private String cd340idx1;
	private String cd340idx2;
	private String cd341idx1;
	private String cd341idx2;
	private String cd342idx1;
	private String cd342idx2;
	private String cd343idx1;
	private String cd343idx2;
	private String cd400idx1;
	private String cd400idx2;
	private String cd410idx1;
	private String cd410idx2;
	private String cd411idx1;
	private String cd411idx2;
	private String cd4111idx1;
	private String cd4111idx2;
	private String cd4112idx1;
	private String cd4112idx2;
	private String cd412idx1;
	private String cd412idx2;
	private String cd413idx1;
	private String cd413idx2;
	private String cd414idx1;
	private String cd414idx2;
	private String cd415idx1;
	private String cd415idx2;
	private String cd416idx1;
	private String cd416idx2;
	private String cd417idx1;
	private String cd417idx2;
	private String cd418idx1;
	private String cd418idx2;
	private String cd419idx1;
	private String cd419idx2;
	private String cd420idx1;
	private String cd420idx2;
	private String cd421idx1;
	private String cd421idx2;
	private String cd4211idx1;
	private String cd4211idx2;
	private String cd4212idx1;
	private String cd4212idx2;
	private String cd422idx1;
	private String cd422idx2;
	private String cd429idx1;
	private String cd429idx2;
	private String cd430idx1;
	private String cd430idx2;
	private String cd431idx1;
	private String cd431idx2;
	private String cd432idx1;
	private String cd432idx2;
	private String cd440idx1;
	private String cd440idx2;
	private String cd500idx1;
	private String cd500idx2;
	private String kq01;
	private String kq02;
	private String kq10;
	private String kq11;
	private String kq20;
	private String kq21;
	private String kq22;
	private String kq23;
	private String kq24;
	private String kq25;
	private String kq26;
	private String kq30;
	private String kq31;
	private String kq32;
	private String kq40;
	private String kq50;
	private String kq51;
	private String kq52;
	private String kq60;
	private String kq61;
	private String kq62;
	private String kq70;
	private String kq71;
	private String lct01;
	private String lct02;
	private String lct03;
	private String lct04;
	private String lct05;
	private String lct06;
	private String lct07;
	private String lct20;
	private String lct21;
	private String lct22;
	private String lct23;
	private String lct24;
	private String lct25;
	private String lct26;
	private String lct27;
	private String lct30;
	private String lct31;
	private String lct32;
	private String lct33;
	private String lct34;
	private String lct35;
	private String lct36;
	private String lct40;
	private String lct50;
	private String lct60;
	private String lct61;
	private String lct70;
	private String lcg01;
	private String lcg02;
	private String lcg03;
	private String lcg04;
	private String lcg05;
	private String lcg06;
	private String lcg07;
	private String lcg08;
	private String lcg09;
	private String lcg10;
	private String lcg11;
	private String lcg12;
	private String lcg13;
	private String lcg14;
	private String lcg15;
	private String lcg16;
	private String lcg17;
	private String lcg18;
	private String lcg20;
	private String lcg21;
	private String lcg22;
	private String lcg23;
	private String lcg24;
	private String lcg25;
	private String lcg26;
	private String lcg27;
	private String lcg30;
	private String lcg31;
	private String lcg32;
	private String lcg33;
	private String lcg34;
	private String lcg35;
	private String lcg36;
	private String lcg40;
	private String lcg50;
	private String lcg60;
	private String lcg61;
	private String lcg70;
	private BigDecimal dongloi;
	private BigDecimal dongloitctd;

	public RpDetailK2K2b() {
	}

	public RpDetailK2K2b(String id, RpSum rpSum, Date createdDate, String createdBy, Date modifiedDate,
			String modifiedBy) {
		this.id = id;
		this.rpSum = rpSum;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 40)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REPORT_ID", nullable = false)
	public RpSum getRpSum() {
		return this.rpSum;
	}

	public void setRpSum(RpSum rpSum) {
		this.rpSum = rpSum;
	}

	@Column(name = "MACN")
	public String getMacn() {
		return this.macn;
	}

	public void setMacn(String macn) {
		this.macn = macn;
	}

	@Column(name = "TENCN")
	public String getTencn() {
		return this.tencn;
	}

	public void setTencn(String tencn) {
		this.tencn = tencn;
	}

	@Column(name = "NGAYBAOCAO")
	public String getNgaybaocao() {
		return this.ngaybaocao;
	}

	public void setNgaybaocao(String ngaybaocao) {
		this.ngaybaocao = ngaybaocao;
	}

	@Column(name = "STATUS", precision = 1, scale = 0)
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "ERROR_CODE", length = 1000)
	public String getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", nullable = false, length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", nullable = false, length = 7)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "MODIFIED_BY", nullable = false)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "BC001")
	public String getBc001() {
		return this.bc001;
	}

	public void setBc001(String bc001) {
		this.bc001 = bc001;
	}

	@Column(name = "BC002")
	public String getBc002() {
		return this.bc002;
	}

	public void setBc002(String bc002) {
		this.bc002 = bc002;
	}

	@Column(name = "BC003")
	public String getBc003() {
		return this.bc003;
	}

	public void setBc003(String bc003) {
		this.bc003 = bc003;
	}

	@Column(name = "BC004")
	public String getBc004() {
		return this.bc004;
	}

	public void setBc004(String bc004) {
		this.bc004 = bc004;
	}

	@Column(name = "BC005")
	public String getBc005() {
		return this.bc005;
	}

	public void setBc005(String bc005) {
		this.bc005 = bc005;
	}

	@Column(name = "BC006")
	public String getBc006() {
		return this.bc006;
	}

	public void setBc006(String bc006) {
		this.bc006 = bc006;
	}

	@Column(name = "BC007")
	public String getBc007() {
		return this.bc007;
	}

	public void setBc007(String bc007) {
		this.bc007 = bc007;
	}

	@Column(name = "CD100IDX1")
	public String getCd100idx1() {
		return this.cd100idx1;
	}

	public void setCd100idx1(String cd100idx1) {
		this.cd100idx1 = cd100idx1;
	}

	@Column(name = "CD100IDX2")
	public String getCd100idx2() {
		return this.cd100idx2;
	}

	public void setCd100idx2(String cd100idx2) {
		this.cd100idx2 = cd100idx2;
	}

	@Column(name = "CD110IDX1")
	public String getCd110idx1() {
		return this.cd110idx1;
	}

	public void setCd110idx1(String cd110idx1) {
		this.cd110idx1 = cd110idx1;
	}

	@Column(name = "CD110IDX2")
	public String getCd110idx2() {
		return this.cd110idx2;
	}

	public void setCd110idx2(String cd110idx2) {
		this.cd110idx2 = cd110idx2;
	}

	@Column(name = "CD111IDX1")
	public String getCd111idx1() {
		return this.cd111idx1;
	}

	public void setCd111idx1(String cd111idx1) {
		this.cd111idx1 = cd111idx1;
	}

	@Column(name = "CD111IDX2")
	public String getCd111idx2() {
		return this.cd111idx2;
	}

	public void setCd111idx2(String cd111idx2) {
		this.cd111idx2 = cd111idx2;
	}

	@Column(name = "CD112IDX1")
	public String getCd112idx1() {
		return this.cd112idx1;
	}

	public void setCd112idx1(String cd112idx1) {
		this.cd112idx1 = cd112idx1;
	}

	@Column(name = "CD112IDX2")
	public String getCd112idx2() {
		return this.cd112idx2;
	}

	public void setCd112idx2(String cd112idx2) {
		this.cd112idx2 = cd112idx2;
	}

	@Column(name = "CD120IDX1")
	public String getCd120idx1() {
		return this.cd120idx1;
	}

	public void setCd120idx1(String cd120idx1) {
		this.cd120idx1 = cd120idx1;
	}

	@Column(name = "CD120IDX2")
	public String getCd120idx2() {
		return this.cd120idx2;
	}

	public void setCd120idx2(String cd120idx2) {
		this.cd120idx2 = cd120idx2;
	}

	@Column(name = "CD121IDX1")
	public String getCd121idx1() {
		return this.cd121idx1;
	}

	public void setCd121idx1(String cd121idx1) {
		this.cd121idx1 = cd121idx1;
	}

	@Column(name = "CD121IDX2")
	public String getCd121idx2() {
		return this.cd121idx2;
	}

	public void setCd121idx2(String cd121idx2) {
		this.cd121idx2 = cd121idx2;
	}

	@Column(name = "CD122IDX1")
	public String getCd122idx1() {
		return this.cd122idx1;
	}

	public void setCd122idx1(String cd122idx1) {
		this.cd122idx1 = cd122idx1;
	}

	@Column(name = "CD122IDX2")
	public String getCd122idx2() {
		return this.cd122idx2;
	}

	public void setCd122idx2(String cd122idx2) {
		this.cd122idx2 = cd122idx2;
	}

	@Column(name = "CD123IDX1")
	public String getCd123idx1() {
		return this.cd123idx1;
	}

	public void setCd123idx1(String cd123idx1) {
		this.cd123idx1 = cd123idx1;
	}

	@Column(name = "CD123IDX2")
	public String getCd123idx2() {
		return this.cd123idx2;
	}

	public void setCd123idx2(String cd123idx2) {
		this.cd123idx2 = cd123idx2;
	}

	@Column(name = "CD124IDX1")
	public String getCd124idx1() {
		return this.cd124idx1;
	}

	public void setCd124idx1(String cd124idx1) {
		this.cd124idx1 = cd124idx1;
	}

	@Column(name = "CD124IDX2")
	public String getCd124idx2() {
		return this.cd124idx2;
	}

	public void setCd124idx2(String cd124idx2) {
		this.cd124idx2 = cd124idx2;
	}

	@Column(name = "CD130IDX1")
	public String getCd130idx1() {
		return this.cd130idx1;
	}

	public void setCd130idx1(String cd130idx1) {
		this.cd130idx1 = cd130idx1;
	}

	@Column(name = "CD130IDX2")
	public String getCd130idx2() {
		return this.cd130idx2;
	}

	public void setCd130idx2(String cd130idx2) {
		this.cd130idx2 = cd130idx2;
	}

	@Column(name = "CD131IDX1")
	public String getCd131idx1() {
		return this.cd131idx1;
	}

	public void setCd131idx1(String cd131idx1) {
		this.cd131idx1 = cd131idx1;
	}

	@Column(name = "CD131IDX2")
	public String getCd131idx2() {
		return this.cd131idx2;
	}

	public void setCd131idx2(String cd131idx2) {
		this.cd131idx2 = cd131idx2;
	}

	@Column(name = "CD132IDX1")
	public String getCd132idx1() {
		return this.cd132idx1;
	}

	public void setCd132idx1(String cd132idx1) {
		this.cd132idx1 = cd132idx1;
	}

	@Column(name = "CD132IDX2")
	public String getCd132idx2() {
		return this.cd132idx2;
	}

	public void setCd132idx2(String cd132idx2) {
		this.cd132idx2 = cd132idx2;
	}

	@Column(name = "CD133IDX1")
	public String getCd133idx1() {
		return this.cd133idx1;
	}

	public void setCd133idx1(String cd133idx1) {
		this.cd133idx1 = cd133idx1;
	}

	@Column(name = "CD133IDX2")
	public String getCd133idx2() {
		return this.cd133idx2;
	}

	public void setCd133idx2(String cd133idx2) {
		this.cd133idx2 = cd133idx2;
	}

	@Column(name = "CD134IDX1")
	public String getCd134idx1() {
		return this.cd134idx1;
	}

	public void setCd134idx1(String cd134idx1) {
		this.cd134idx1 = cd134idx1;
	}

	@Column(name = "CD134IDX2")
	public String getCd134idx2() {
		return this.cd134idx2;
	}

	public void setCd134idx2(String cd134idx2) {
		this.cd134idx2 = cd134idx2;
	}

	@Column(name = "CD135IDX1")
	public String getCd135idx1() {
		return this.cd135idx1;
	}

	public void setCd135idx1(String cd135idx1) {
		this.cd135idx1 = cd135idx1;
	}

	@Column(name = "CD135IDX2")
	public String getCd135idx2() {
		return this.cd135idx2;
	}

	public void setCd135idx2(String cd135idx2) {
		this.cd135idx2 = cd135idx2;
	}

	@Column(name = "CD136IDX1")
	public String getCd136idx1() {
		return this.cd136idx1;
	}

	public void setCd136idx1(String cd136idx1) {
		this.cd136idx1 = cd136idx1;
	}

	@Column(name = "CD136IDX2")
	public String getCd136idx2() {
		return this.cd136idx2;
	}

	public void setCd136idx2(String cd136idx2) {
		this.cd136idx2 = cd136idx2;
	}

	@Column(name = "CD137IDX1")
	public String getCd137idx1() {
		return this.cd137idx1;
	}

	public void setCd137idx1(String cd137idx1) {
		this.cd137idx1 = cd137idx1;
	}

	@Column(name = "CD137IDX2")
	public String getCd137idx2() {
		return this.cd137idx2;
	}

	public void setCd137idx2(String cd137idx2) {
		this.cd137idx2 = cd137idx2;
	}

	@Column(name = "CD138IDX1")
	public String getCd138idx1() {
		return this.cd138idx1;
	}

	public void setCd138idx1(String cd138idx1) {
		this.cd138idx1 = cd138idx1;
	}

	@Column(name = "CD138IDX2")
	public String getCd138idx2() {
		return this.cd138idx2;
	}

	public void setCd138idx2(String cd138idx2) {
		this.cd138idx2 = cd138idx2;
	}

	@Column(name = "CD139IDX1")
	public String getCd139idx1() {
		return this.cd139idx1;
	}

	public void setCd139idx1(String cd139idx1) {
		this.cd139idx1 = cd139idx1;
	}

	@Column(name = "CD139IDX2")
	public String getCd139idx2() {
		return this.cd139idx2;
	}

	public void setCd139idx2(String cd139idx2) {
		this.cd139idx2 = cd139idx2;
	}

	@Column(name = "CD140IDX1")
	public String getCd140idx1() {
		return this.cd140idx1;
	}

	public void setCd140idx1(String cd140idx1) {
		this.cd140idx1 = cd140idx1;
	}

	@Column(name = "CD140IDX2")
	public String getCd140idx2() {
		return this.cd140idx2;
	}

	public void setCd140idx2(String cd140idx2) {
		this.cd140idx2 = cd140idx2;
	}

	@Column(name = "CD141IDX1")
	public String getCd141idx1() {
		return this.cd141idx1;
	}

	public void setCd141idx1(String cd141idx1) {
		this.cd141idx1 = cd141idx1;
	}

	@Column(name = "CD141IDX2")
	public String getCd141idx2() {
		return this.cd141idx2;
	}

	public void setCd141idx2(String cd141idx2) {
		this.cd141idx2 = cd141idx2;
	}

	@Column(name = "CD142IDX1")
	public String getCd142idx1() {
		return this.cd142idx1;
	}

	public void setCd142idx1(String cd142idx1) {
		this.cd142idx1 = cd142idx1;
	}

	@Column(name = "CD142IDX2")
	public String getCd142idx2() {
		return this.cd142idx2;
	}

	public void setCd142idx2(String cd142idx2) {
		this.cd142idx2 = cd142idx2;
	}

	@Column(name = "CD149IDX1")
	public String getCd149idx1() {
		return this.cd149idx1;
	}

	public void setCd149idx1(String cd149idx1) {
		this.cd149idx1 = cd149idx1;
	}

	@Column(name = "CD149IDX2")
	public String getCd149idx2() {
		return this.cd149idx2;
	}

	public void setCd149idx2(String cd149idx2) {
		this.cd149idx2 = cd149idx2;
	}

	@Column(name = "CD150IDX1")
	public String getCd150idx1() {
		return this.cd150idx1;
	}

	public void setCd150idx1(String cd150idx1) {
		this.cd150idx1 = cd150idx1;
	}

	@Column(name = "CD150IDX2")
	public String getCd150idx2() {
		return this.cd150idx2;
	}

	public void setCd150idx2(String cd150idx2) {
		this.cd150idx2 = cd150idx2;
	}

	@Column(name = "CD151IDX1")
	public String getCd151idx1() {
		return this.cd151idx1;
	}

	public void setCd151idx1(String cd151idx1) {
		this.cd151idx1 = cd151idx1;
	}

	@Column(name = "CD151IDX2")
	public String getCd151idx2() {
		return this.cd151idx2;
	}

	public void setCd151idx2(String cd151idx2) {
		this.cd151idx2 = cd151idx2;
	}

	@Column(name = "CD152IDX1")
	public String getCd152idx1() {
		return this.cd152idx1;
	}

	public void setCd152idx1(String cd152idx1) {
		this.cd152idx1 = cd152idx1;
	}

	@Column(name = "CD152IDX2")
	public String getCd152idx2() {
		return this.cd152idx2;
	}

	public void setCd152idx2(String cd152idx2) {
		this.cd152idx2 = cd152idx2;
	}

	@Column(name = "CD153IDX1")
	public String getCd153idx1() {
		return this.cd153idx1;
	}

	public void setCd153idx1(String cd153idx1) {
		this.cd153idx1 = cd153idx1;
	}

	@Column(name = "CD153IDX2")
	public String getCd153idx2() {
		return this.cd153idx2;
	}

	public void setCd153idx2(String cd153idx2) {
		this.cd153idx2 = cd153idx2;
	}

	@Column(name = "CD154IDX1")
	public String getCd154idx1() {
		return this.cd154idx1;
	}

	public void setCd154idx1(String cd154idx1) {
		this.cd154idx1 = cd154idx1;
	}

	@Column(name = "CD154IDX2")
	public String getCd154idx2() {
		return this.cd154idx2;
	}

	public void setCd154idx2(String cd154idx2) {
		this.cd154idx2 = cd154idx2;
	}

	@Column(name = "CD155IDX1")
	public String getCd155idx1() {
		return this.cd155idx1;
	}

	public void setCd155idx1(String cd155idx1) {
		this.cd155idx1 = cd155idx1;
	}

	@Column(name = "CD155IDX2")
	public String getCd155idx2() {
		return this.cd155idx2;
	}

	public void setCd155idx2(String cd155idx2) {
		this.cd155idx2 = cd155idx2;
	}

	@Column(name = "CD160IDX1")
	public String getCd160idx1() {
		return this.cd160idx1;
	}

	public void setCd160idx1(String cd160idx1) {
		this.cd160idx1 = cd160idx1;
	}

	@Column(name = "CD160IDX2")
	public String getCd160idx2() {
		return this.cd160idx2;
	}

	public void setCd160idx2(String cd160idx2) {
		this.cd160idx2 = cd160idx2;
	}

	@Column(name = "CD161IDX1")
	public String getCd161idx1() {
		return this.cd161idx1;
	}

	public void setCd161idx1(String cd161idx1) {
		this.cd161idx1 = cd161idx1;
	}

	@Column(name = "CD161IDX2")
	public String getCd161idx2() {
		return this.cd161idx2;
	}

	public void setCd161idx2(String cd161idx2) {
		this.cd161idx2 = cd161idx2;
	}

	@Column(name = "CD162IDX1")
	public String getCd162idx1() {
		return this.cd162idx1;
	}

	public void setCd162idx1(String cd162idx1) {
		this.cd162idx1 = cd162idx1;
	}

	@Column(name = "CD162IDX2")
	public String getCd162idx2() {
		return this.cd162idx2;
	}

	public void setCd162idx2(String cd162idx2) {
		this.cd162idx2 = cd162idx2;
	}

	@Column(name = "CD170IDX1")
	public String getCd170idx1() {
		return this.cd170idx1;
	}

	public void setCd170idx1(String cd170idx1) {
		this.cd170idx1 = cd170idx1;
	}

	@Column(name = "CD170IDX2")
	public String getCd170idx2() {
		return this.cd170idx2;
	}

	public void setCd170idx2(String cd170idx2) {
		this.cd170idx2 = cd170idx2;
	}

	@Column(name = "CD180IDX1")
	public String getCd180idx1() {
		return this.cd180idx1;
	}

	public void setCd180idx1(String cd180idx1) {
		this.cd180idx1 = cd180idx1;
	}

	@Column(name = "CD180IDX2")
	public String getCd180idx2() {
		return this.cd180idx2;
	}

	public void setCd180idx2(String cd180idx2) {
		this.cd180idx2 = cd180idx2;
	}

	@Column(name = "CD181IDX1")
	public String getCd181idx1() {
		return this.cd181idx1;
	}

	public void setCd181idx1(String cd181idx1) {
		this.cd181idx1 = cd181idx1;
	}

	@Column(name = "CD181IDX2")
	public String getCd181idx2() {
		return this.cd181idx2;
	}

	public void setCd181idx2(String cd181idx2) {
		this.cd181idx2 = cd181idx2;
	}

	@Column(name = "CD182IDX1")
	public String getCd182idx1() {
		return this.cd182idx1;
	}

	public void setCd182idx1(String cd182idx1) {
		this.cd182idx1 = cd182idx1;
	}

	@Column(name = "CD182IDX2")
	public String getCd182idx2() {
		return this.cd182idx2;
	}

	public void setCd182idx2(String cd182idx2) {
		this.cd182idx2 = cd182idx2;
	}

	@Column(name = "CD200IDX1")
	public String getCd200idx1() {
		return this.cd200idx1;
	}

	public void setCd200idx1(String cd200idx1) {
		this.cd200idx1 = cd200idx1;
	}

	@Column(name = "CD200IDX2")
	public String getCd200idx2() {
		return this.cd200idx2;
	}

	public void setCd200idx2(String cd200idx2) {
		this.cd200idx2 = cd200idx2;
	}

	@Column(name = "CD210IDX1")
	public String getCd210idx1() {
		return this.cd210idx1;
	}

	public void setCd210idx1(String cd210idx1) {
		this.cd210idx1 = cd210idx1;
	}

	@Column(name = "CD210IDX2")
	public String getCd210idx2() {
		return this.cd210idx2;
	}

	public void setCd210idx2(String cd210idx2) {
		this.cd210idx2 = cd210idx2;
	}

	@Column(name = "CD211IDX1")
	public String getCd211idx1() {
		return this.cd211idx1;
	}

	public void setCd211idx1(String cd211idx1) {
		this.cd211idx1 = cd211idx1;
	}

	@Column(name = "CD211IDX2")
	public String getCd211idx2() {
		return this.cd211idx2;
	}

	public void setCd211idx2(String cd211idx2) {
		this.cd211idx2 = cd211idx2;
	}

	@Column(name = "CD212IDX1")
	public String getCd212idx1() {
		return this.cd212idx1;
	}

	public void setCd212idx1(String cd212idx1) {
		this.cd212idx1 = cd212idx1;
	}

	@Column(name = "CD212IDX2")
	public String getCd212idx2() {
		return this.cd212idx2;
	}

	public void setCd212idx2(String cd212idx2) {
		this.cd212idx2 = cd212idx2;
	}

	@Column(name = "CD213IDX1")
	public String getCd213idx1() {
		return this.cd213idx1;
	}

	public void setCd213idx1(String cd213idx1) {
		this.cd213idx1 = cd213idx1;
	}

	@Column(name = "CD213IDX2")
	public String getCd213idx2() {
		return this.cd213idx2;
	}

	public void setCd213idx2(String cd213idx2) {
		this.cd213idx2 = cd213idx2;
	}

	@Column(name = "CD214IDX1")
	public String getCd214idx1() {
		return this.cd214idx1;
	}

	public void setCd214idx1(String cd214idx1) {
		this.cd214idx1 = cd214idx1;
	}

	@Column(name = "CD214IDX2")
	public String getCd214idx2() {
		return this.cd214idx2;
	}

	public void setCd214idx2(String cd214idx2) {
		this.cd214idx2 = cd214idx2;
	}

	@Column(name = "CD215IDX1")
	public String getCd215idx1() {
		return this.cd215idx1;
	}

	public void setCd215idx1(String cd215idx1) {
		this.cd215idx1 = cd215idx1;
	}

	@Column(name = "CD215IDX2")
	public String getCd215idx2() {
		return this.cd215idx2;
	}

	public void setCd215idx2(String cd215idx2) {
		this.cd215idx2 = cd215idx2;
	}

	@Column(name = "CD216IDX1")
	public String getCd216idx1() {
		return this.cd216idx1;
	}

	public void setCd216idx1(String cd216idx1) {
		this.cd216idx1 = cd216idx1;
	}

	@Column(name = "CD216IDX2")
	public String getCd216idx2() {
		return this.cd216idx2;
	}

	public void setCd216idx2(String cd216idx2) {
		this.cd216idx2 = cd216idx2;
	}

	@Column(name = "CD219IDX1")
	public String getCd219idx1() {
		return this.cd219idx1;
	}

	public void setCd219idx1(String cd219idx1) {
		this.cd219idx1 = cd219idx1;
	}

	@Column(name = "CD219IDX2")
	public String getCd219idx2() {
		return this.cd219idx2;
	}

	public void setCd219idx2(String cd219idx2) {
		this.cd219idx2 = cd219idx2;
	}

	@Column(name = "CD220IDX1")
	public String getCd220idx1() {
		return this.cd220idx1;
	}

	public void setCd220idx1(String cd220idx1) {
		this.cd220idx1 = cd220idx1;
	}

	@Column(name = "CD220IDX2")
	public String getCd220idx2() {
		return this.cd220idx2;
	}

	public void setCd220idx2(String cd220idx2) {
		this.cd220idx2 = cd220idx2;
	}

	@Column(name = "CD221IDX1")
	public String getCd221idx1() {
		return this.cd221idx1;
	}

	public void setCd221idx1(String cd221idx1) {
		this.cd221idx1 = cd221idx1;
	}

	@Column(name = "CD221IDX2")
	public String getCd221idx2() {
		return this.cd221idx2;
	}

	public void setCd221idx2(String cd221idx2) {
		this.cd221idx2 = cd221idx2;
	}

	@Column(name = "CD222IDX1")
	public String getCd222idx1() {
		return this.cd222idx1;
	}

	public void setCd222idx1(String cd222idx1) {
		this.cd222idx1 = cd222idx1;
	}

	@Column(name = "CD222IDX2")
	public String getCd222idx2() {
		return this.cd222idx2;
	}

	public void setCd222idx2(String cd222idx2) {
		this.cd222idx2 = cd222idx2;
	}

	@Column(name = "CD223IDX1")
	public String getCd223idx1() {
		return this.cd223idx1;
	}

	public void setCd223idx1(String cd223idx1) {
		this.cd223idx1 = cd223idx1;
	}

	@Column(name = "CD223IDX2")
	public String getCd223idx2() {
		return this.cd223idx2;
	}

	public void setCd223idx2(String cd223idx2) {
		this.cd223idx2 = cd223idx2;
	}

	@Column(name = "CD224IDX1")
	public String getCd224idx1() {
		return this.cd224idx1;
	}

	public void setCd224idx1(String cd224idx1) {
		this.cd224idx1 = cd224idx1;
	}

	@Column(name = "CD224IDX2")
	public String getCd224idx2() {
		return this.cd224idx2;
	}

	public void setCd224idx2(String cd224idx2) {
		this.cd224idx2 = cd224idx2;
	}

	@Column(name = "CD225IDX1")
	public String getCd225idx1() {
		return this.cd225idx1;
	}

	public void setCd225idx1(String cd225idx1) {
		this.cd225idx1 = cd225idx1;
	}

	@Column(name = "CD225IDX2")
	public String getCd225idx2() {
		return this.cd225idx2;
	}

	public void setCd225idx2(String cd225idx2) {
		this.cd225idx2 = cd225idx2;
	}

	@Column(name = "CD226IDX1")
	public String getCd226idx1() {
		return this.cd226idx1;
	}

	public void setCd226idx1(String cd226idx1) {
		this.cd226idx1 = cd226idx1;
	}

	@Column(name = "CD226IDX2")
	public String getCd226idx2() {
		return this.cd226idx2;
	}

	public void setCd226idx2(String cd226idx2) {
		this.cd226idx2 = cd226idx2;
	}

	@Column(name = "CD227IDX1")
	public String getCd227idx1() {
		return this.cd227idx1;
	}

	public void setCd227idx1(String cd227idx1) {
		this.cd227idx1 = cd227idx1;
	}

	@Column(name = "CD227IDX2")
	public String getCd227idx2() {
		return this.cd227idx2;
	}

	public void setCd227idx2(String cd227idx2) {
		this.cd227idx2 = cd227idx2;
	}

	@Column(name = "CD228IDX1")
	public String getCd228idx1() {
		return this.cd228idx1;
	}

	public void setCd228idx1(String cd228idx1) {
		this.cd228idx1 = cd228idx1;
	}

	@Column(name = "CD228IDX2")
	public String getCd228idx2() {
		return this.cd228idx2;
	}

	public void setCd228idx2(String cd228idx2) {
		this.cd228idx2 = cd228idx2;
	}

	@Column(name = "CD229IDX1")
	public String getCd229idx1() {
		return this.cd229idx1;
	}

	public void setCd229idx1(String cd229idx1) {
		this.cd229idx1 = cd229idx1;
	}

	@Column(name = "CD229IDX2")
	public String getCd229idx2() {
		return this.cd229idx2;
	}

	public void setCd229idx2(String cd229idx2) {
		this.cd229idx2 = cd229idx2;
	}

	@Column(name = "CD230IDX1")
	public String getCd230idx1() {
		return this.cd230idx1;
	}

	public void setCd230idx1(String cd230idx1) {
		this.cd230idx1 = cd230idx1;
	}

	@Column(name = "CD230IDX2")
	public String getCd230idx2() {
		return this.cd230idx2;
	}

	public void setCd230idx2(String cd230idx2) {
		this.cd230idx2 = cd230idx2;
	}

	@Column(name = "CD231IDX1")
	public String getCd231idx1() {
		return this.cd231idx1;
	}

	public void setCd231idx1(String cd231idx1) {
		this.cd231idx1 = cd231idx1;
	}

	@Column(name = "CD231IDX2")
	public String getCd231idx2() {
		return this.cd231idx2;
	}

	public void setCd231idx2(String cd231idx2) {
		this.cd231idx2 = cd231idx2;
	}

	@Column(name = "CD232IDX1")
	public String getCd232idx1() {
		return this.cd232idx1;
	}

	public void setCd232idx1(String cd232idx1) {
		this.cd232idx1 = cd232idx1;
	}

	@Column(name = "CD232IDX2")
	public String getCd232idx2() {
		return this.cd232idx2;
	}

	public void setCd232idx2(String cd232idx2) {
		this.cd232idx2 = cd232idx2;
	}

	@Column(name = "CD240IDX1")
	public String getCd240idx1() {
		return this.cd240idx1;
	}

	public void setCd240idx1(String cd240idx1) {
		this.cd240idx1 = cd240idx1;
	}

	@Column(name = "CD240IDX2")
	public String getCd240idx2() {
		return this.cd240idx2;
	}

	public void setCd240idx2(String cd240idx2) {
		this.cd240idx2 = cd240idx2;
	}

	@Column(name = "CD241IDX1")
	public String getCd241idx1() {
		return this.cd241idx1;
	}

	public void setCd241idx1(String cd241idx1) {
		this.cd241idx1 = cd241idx1;
	}

	@Column(name = "CD241IDX2")
	public String getCd241idx2() {
		return this.cd241idx2;
	}

	public void setCd241idx2(String cd241idx2) {
		this.cd241idx2 = cd241idx2;
	}

	@Column(name = "CD242IDX1")
	public String getCd242idx1() {
		return this.cd242idx1;
	}

	public void setCd242idx1(String cd242idx1) {
		this.cd242idx1 = cd242idx1;
	}

	@Column(name = "CD242IDX2")
	public String getCd242idx2() {
		return this.cd242idx2;
	}

	public void setCd242idx2(String cd242idx2) {
		this.cd242idx2 = cd242idx2;
	}

	@Column(name = "CD250IDX1")
	public String getCd250idx1() {
		return this.cd250idx1;
	}

	public void setCd250idx1(String cd250idx1) {
		this.cd250idx1 = cd250idx1;
	}

	@Column(name = "CD250IDX2")
	public String getCd250idx2() {
		return this.cd250idx2;
	}

	public void setCd250idx2(String cd250idx2) {
		this.cd250idx2 = cd250idx2;
	}

	@Column(name = "CD251IDX1")
	public String getCd251idx1() {
		return this.cd251idx1;
	}

	public void setCd251idx1(String cd251idx1) {
		this.cd251idx1 = cd251idx1;
	}

	@Column(name = "CD251IDX2")
	public String getCd251idx2() {
		return this.cd251idx2;
	}

	public void setCd251idx2(String cd251idx2) {
		this.cd251idx2 = cd251idx2;
	}

	@Column(name = "CD252IDX1")
	public String getCd252idx1() {
		return this.cd252idx1;
	}

	public void setCd252idx1(String cd252idx1) {
		this.cd252idx1 = cd252idx1;
	}

	@Column(name = "CD252IDX2")
	public String getCd252idx2() {
		return this.cd252idx2;
	}

	public void setCd252idx2(String cd252idx2) {
		this.cd252idx2 = cd252idx2;
	}

	@Column(name = "CD253IDX1")
	public String getCd253idx1() {
		return this.cd253idx1;
	}

	public void setCd253idx1(String cd253idx1) {
		this.cd253idx1 = cd253idx1;
	}

	@Column(name = "CD253IDX2")
	public String getCd253idx2() {
		return this.cd253idx2;
	}

	public void setCd253idx2(String cd253idx2) {
		this.cd253idx2 = cd253idx2;
	}

	@Column(name = "CD254IDX1")
	public String getCd254idx1() {
		return this.cd254idx1;
	}

	public void setCd254idx1(String cd254idx1) {
		this.cd254idx1 = cd254idx1;
	}

	@Column(name = "CD254IDX2")
	public String getCd254idx2() {
		return this.cd254idx2;
	}

	public void setCd254idx2(String cd254idx2) {
		this.cd254idx2 = cd254idx2;
	}

	@Column(name = "CD255IDX1")
	public String getCd255idx1() {
		return this.cd255idx1;
	}

	public void setCd255idx1(String cd255idx1) {
		this.cd255idx1 = cd255idx1;
	}

	@Column(name = "CD255IDX2")
	public String getCd255idx2() {
		return this.cd255idx2;
	}

	public void setCd255idx2(String cd255idx2) {
		this.cd255idx2 = cd255idx2;
	}

	@Column(name = "CD260IDX1")
	public String getCd260idx1() {
		return this.cd260idx1;
	}

	public void setCd260idx1(String cd260idx1) {
		this.cd260idx1 = cd260idx1;
	}

	@Column(name = "CD260IDX2")
	public String getCd260idx2() {
		return this.cd260idx2;
	}

	public void setCd260idx2(String cd260idx2) {
		this.cd260idx2 = cd260idx2;
	}

	@Column(name = "CD261IDX1")
	public String getCd261idx1() {
		return this.cd261idx1;
	}

	public void setCd261idx1(String cd261idx1) {
		this.cd261idx1 = cd261idx1;
	}

	@Column(name = "CD261IDX2")
	public String getCd261idx2() {
		return this.cd261idx2;
	}

	public void setCd261idx2(String cd261idx2) {
		this.cd261idx2 = cd261idx2;
	}

	@Column(name = "CD262IDX1")
	public String getCd262idx1() {
		return this.cd262idx1;
	}

	public void setCd262idx1(String cd262idx1) {
		this.cd262idx1 = cd262idx1;
	}

	@Column(name = "CD262IDX2")
	public String getCd262idx2() {
		return this.cd262idx2;
	}

	public void setCd262idx2(String cd262idx2) {
		this.cd262idx2 = cd262idx2;
	}

	@Column(name = "CD263IDX1")
	public String getCd263idx1() {
		return this.cd263idx1;
	}

	public void setCd263idx1(String cd263idx1) {
		this.cd263idx1 = cd263idx1;
	}

	@Column(name = "CD263IDX2")
	public String getCd263idx2() {
		return this.cd263idx2;
	}

	public void setCd263idx2(String cd263idx2) {
		this.cd263idx2 = cd263idx2;
	}

	@Column(name = "CD268IDX1")
	public String getCd268idx1() {
		return this.cd268idx1;
	}

	public void setCd268idx1(String cd268idx1) {
		this.cd268idx1 = cd268idx1;
	}

	@Column(name = "CD268IDX2")
	public String getCd268idx2() {
		return this.cd268idx2;
	}

	public void setCd268idx2(String cd268idx2) {
		this.cd268idx2 = cd268idx2;
	}

	@Column(name = "CD269IDX1")
	public String getCd269idx1() {
		return this.cd269idx1;
	}

	public void setCd269idx1(String cd269idx1) {
		this.cd269idx1 = cd269idx1;
	}

	@Column(name = "CD269IDX2")
	public String getCd269idx2() {
		return this.cd269idx2;
	}

	public void setCd269idx2(String cd269idx2) {
		this.cd269idx2 = cd269idx2;
	}

	@Column(name = "CD270IDX1")
	public String getCd270idx1() {
		return this.cd270idx1;
	}

	public void setCd270idx1(String cd270idx1) {
		this.cd270idx1 = cd270idx1;
	}

	@Column(name = "CD270IDX2")
	public String getCd270idx2() {
		return this.cd270idx2;
	}

	public void setCd270idx2(String cd270idx2) {
		this.cd270idx2 = cd270idx2;
	}

	@Column(name = "CD300IDX1")
	public String getCd300idx1() {
		return this.cd300idx1;
	}

	public void setCd300idx1(String cd300idx1) {
		this.cd300idx1 = cd300idx1;
	}

	@Column(name = "CD300IDX2")
	public String getCd300idx2() {
		return this.cd300idx2;
	}

	public void setCd300idx2(String cd300idx2) {
		this.cd300idx2 = cd300idx2;
	}

	@Column(name = "CD310IDX1")
	public String getCd310idx1() {
		return this.cd310idx1;
	}

	public void setCd310idx1(String cd310idx1) {
		this.cd310idx1 = cd310idx1;
	}

	@Column(name = "CD310IDX2")
	public String getCd310idx2() {
		return this.cd310idx2;
	}

	public void setCd310idx2(String cd310idx2) {
		this.cd310idx2 = cd310idx2;
	}

	@Column(name = "CD311IDX1")
	public String getCd311idx1() {
		return this.cd311idx1;
	}

	public void setCd311idx1(String cd311idx1) {
		this.cd311idx1 = cd311idx1;
	}

	@Column(name = "CD311IDX2")
	public String getCd311idx2() {
		return this.cd311idx2;
	}

	public void setCd311idx2(String cd311idx2) {
		this.cd311idx2 = cd311idx2;
	}

	@Column(name = "CD312IDX1")
	public String getCd312idx1() {
		return this.cd312idx1;
	}

	public void setCd312idx1(String cd312idx1) {
		this.cd312idx1 = cd312idx1;
	}

	@Column(name = "CD312IDX2")
	public String getCd312idx2() {
		return this.cd312idx2;
	}

	public void setCd312idx2(String cd312idx2) {
		this.cd312idx2 = cd312idx2;
	}

	@Column(name = "CD313IDX1")
	public String getCd313idx1() {
		return this.cd313idx1;
	}

	public void setCd313idx1(String cd313idx1) {
		this.cd313idx1 = cd313idx1;
	}

	@Column(name = "CD313IDX2")
	public String getCd313idx2() {
		return this.cd313idx2;
	}

	public void setCd313idx2(String cd313idx2) {
		this.cd313idx2 = cd313idx2;
	}

	@Column(name = "CD314IDX1")
	public String getCd314idx1() {
		return this.cd314idx1;
	}

	public void setCd314idx1(String cd314idx1) {
		this.cd314idx1 = cd314idx1;
	}

	@Column(name = "CD314IDX2")
	public String getCd314idx2() {
		return this.cd314idx2;
	}

	public void setCd314idx2(String cd314idx2) {
		this.cd314idx2 = cd314idx2;
	}

	@Column(name = "CD315IDX1")
	public String getCd315idx1() {
		return this.cd315idx1;
	}

	public void setCd315idx1(String cd315idx1) {
		this.cd315idx1 = cd315idx1;
	}

	@Column(name = "CD315IDX2")
	public String getCd315idx2() {
		return this.cd315idx2;
	}

	public void setCd315idx2(String cd315idx2) {
		this.cd315idx2 = cd315idx2;
	}

	@Column(name = "CD316IDX1")
	public String getCd316idx1() {
		return this.cd316idx1;
	}

	public void setCd316idx1(String cd316idx1) {
		this.cd316idx1 = cd316idx1;
	}

	@Column(name = "CD316IDX2")
	public String getCd316idx2() {
		return this.cd316idx2;
	}

	public void setCd316idx2(String cd316idx2) {
		this.cd316idx2 = cd316idx2;
	}

	@Column(name = "CD317IDX1")
	public String getCd317idx1() {
		return this.cd317idx1;
	}

	public void setCd317idx1(String cd317idx1) {
		this.cd317idx1 = cd317idx1;
	}

	@Column(name = "CD317IDX2")
	public String getCd317idx2() {
		return this.cd317idx2;
	}

	public void setCd317idx2(String cd317idx2) {
		this.cd317idx2 = cd317idx2;
	}

	@Column(name = "CD318IDX1")
	public String getCd318idx1() {
		return this.cd318idx1;
	}

	public void setCd318idx1(String cd318idx1) {
		this.cd318idx1 = cd318idx1;
	}

	@Column(name = "CD318IDX2")
	public String getCd318idx2() {
		return this.cd318idx2;
	}

	public void setCd318idx2(String cd318idx2) {
		this.cd318idx2 = cd318idx2;
	}

	@Column(name = "CD319IDX1")
	public String getCd319idx1() {
		return this.cd319idx1;
	}

	public void setCd319idx1(String cd319idx1) {
		this.cd319idx1 = cd319idx1;
	}

	@Column(name = "CD319IDX2")
	public String getCd319idx2() {
		return this.cd319idx2;
	}

	public void setCd319idx2(String cd319idx2) {
		this.cd319idx2 = cd319idx2;
	}

	@Column(name = "CD320IDX1")
	public String getCd320idx1() {
		return this.cd320idx1;
	}

	public void setCd320idx1(String cd320idx1) {
		this.cd320idx1 = cd320idx1;
	}

	@Column(name = "CD320IDX2")
	public String getCd320idx2() {
		return this.cd320idx2;
	}

	public void setCd320idx2(String cd320idx2) {
		this.cd320idx2 = cd320idx2;
	}

	@Column(name = "CD321IDX1")
	public String getCd321idx1() {
		return this.cd321idx1;
	}

	public void setCd321idx1(String cd321idx1) {
		this.cd321idx1 = cd321idx1;
	}

	@Column(name = "CD321IDX2")
	public String getCd321idx2() {
		return this.cd321idx2;
	}

	public void setCd321idx2(String cd321idx2) {
		this.cd321idx2 = cd321idx2;
	}

	@Column(name = "CD322IDX1")
	public String getCd322idx1() {
		return this.cd322idx1;
	}

	public void setCd322idx1(String cd322idx1) {
		this.cd322idx1 = cd322idx1;
	}

	@Column(name = "CD322IDX2")
	public String getCd322idx2() {
		return this.cd322idx2;
	}

	public void setCd322idx2(String cd322idx2) {
		this.cd322idx2 = cd322idx2;
	}

	@Column(name = "CD323IDX1")
	public String getCd323idx1() {
		return this.cd323idx1;
	}

	public void setCd323idx1(String cd323idx1) {
		this.cd323idx1 = cd323idx1;
	}

	@Column(name = "CD323IDX2")
	public String getCd323idx2() {
		return this.cd323idx2;
	}

	public void setCd323idx2(String cd323idx2) {
		this.cd323idx2 = cd323idx2;
	}

	@Column(name = "CD324IDX1")
	public String getCd324idx1() {
		return this.cd324idx1;
	}

	public void setCd324idx1(String cd324idx1) {
		this.cd324idx1 = cd324idx1;
	}

	@Column(name = "CD324IDX2")
	public String getCd324idx2() {
		return this.cd324idx2;
	}

	public void setCd324idx2(String cd324idx2) {
		this.cd324idx2 = cd324idx2;
	}

	@Column(name = "CD330IDX1")
	public String getCd330idx1() {
		return this.cd330idx1;
	}

	public void setCd330idx1(String cd330idx1) {
		this.cd330idx1 = cd330idx1;
	}

	@Column(name = "CD330IDX2")
	public String getCd330idx2() {
		return this.cd330idx2;
	}

	public void setCd330idx2(String cd330idx2) {
		this.cd330idx2 = cd330idx2;
	}

	@Column(name = "CD331IDX1")
	public String getCd331idx1() {
		return this.cd331idx1;
	}

	public void setCd331idx1(String cd331idx1) {
		this.cd331idx1 = cd331idx1;
	}

	@Column(name = "CD331IDX2")
	public String getCd331idx2() {
		return this.cd331idx2;
	}

	public void setCd331idx2(String cd331idx2) {
		this.cd331idx2 = cd331idx2;
	}

	@Column(name = "CD332IDX1")
	public String getCd332idx1() {
		return this.cd332idx1;
	}

	public void setCd332idx1(String cd332idx1) {
		this.cd332idx1 = cd332idx1;
	}

	@Column(name = "CD332IDX2")
	public String getCd332idx2() {
		return this.cd332idx2;
	}

	public void setCd332idx2(String cd332idx2) {
		this.cd332idx2 = cd332idx2;
	}

	@Column(name = "CD333IDX1")
	public String getCd333idx1() {
		return this.cd333idx1;
	}

	public void setCd333idx1(String cd333idx1) {
		this.cd333idx1 = cd333idx1;
	}

	@Column(name = "CD333IDX2")
	public String getCd333idx2() {
		return this.cd333idx2;
	}

	public void setCd333idx2(String cd333idx2) {
		this.cd333idx2 = cd333idx2;
	}

	@Column(name = "CD334IDX1")
	public String getCd334idx1() {
		return this.cd334idx1;
	}

	public void setCd334idx1(String cd334idx1) {
		this.cd334idx1 = cd334idx1;
	}

	@Column(name = "CD334IDX2")
	public String getCd334idx2() {
		return this.cd334idx2;
	}

	public void setCd334idx2(String cd334idx2) {
		this.cd334idx2 = cd334idx2;
	}

	@Column(name = "CD335IDX1")
	public String getCd335idx1() {
		return this.cd335idx1;
	}

	public void setCd335idx1(String cd335idx1) {
		this.cd335idx1 = cd335idx1;
	}

	@Column(name = "CD335IDX2")
	public String getCd335idx2() {
		return this.cd335idx2;
	}

	public void setCd335idx2(String cd335idx2) {
		this.cd335idx2 = cd335idx2;
	}

	@Column(name = "CD336IDX1")
	public String getCd336idx1() {
		return this.cd336idx1;
	}

	public void setCd336idx1(String cd336idx1) {
		this.cd336idx1 = cd336idx1;
	}

	@Column(name = "CD336IDX2")
	public String getCd336idx2() {
		return this.cd336idx2;
	}

	public void setCd336idx2(String cd336idx2) {
		this.cd336idx2 = cd336idx2;
	}

	@Column(name = "CD337IDX1")
	public String getCd337idx1() {
		return this.cd337idx1;
	}

	public void setCd337idx1(String cd337idx1) {
		this.cd337idx1 = cd337idx1;
	}

	@Column(name = "CD337IDX2")
	public String getCd337idx2() {
		return this.cd337idx2;
	}

	public void setCd337idx2(String cd337idx2) {
		this.cd337idx2 = cd337idx2;
	}

	@Column(name = "CD338IDX1")
	public String getCd338idx1() {
		return this.cd338idx1;
	}

	public void setCd338idx1(String cd338idx1) {
		this.cd338idx1 = cd338idx1;
	}

	@Column(name = "CD338IDX2")
	public String getCd338idx2() {
		return this.cd338idx2;
	}

	public void setCd338idx2(String cd338idx2) {
		this.cd338idx2 = cd338idx2;
	}

	@Column(name = "CD339IDX1")
	public String getCd339idx1() {
		return this.cd339idx1;
	}

	public void setCd339idx1(String cd339idx1) {
		this.cd339idx1 = cd339idx1;
	}

	@Column(name = "CD339IDX2")
	public String getCd339idx2() {
		return this.cd339idx2;
	}

	public void setCd339idx2(String cd339idx2) {
		this.cd339idx2 = cd339idx2;
	}

	@Column(name = "CD340IDX1")
	public String getCd340idx1() {
		return this.cd340idx1;
	}

	public void setCd340idx1(String cd340idx1) {
		this.cd340idx1 = cd340idx1;
	}

	@Column(name = "CD340IDX2")
	public String getCd340idx2() {
		return this.cd340idx2;
	}

	public void setCd340idx2(String cd340idx2) {
		this.cd340idx2 = cd340idx2;
	}

	@Column(name = "CD341IDX1")
	public String getCd341idx1() {
		return this.cd341idx1;
	}

	public void setCd341idx1(String cd341idx1) {
		this.cd341idx1 = cd341idx1;
	}

	@Column(name = "CD341IDX2")
	public String getCd341idx2() {
		return this.cd341idx2;
	}

	public void setCd341idx2(String cd341idx2) {
		this.cd341idx2 = cd341idx2;
	}

	@Column(name = "CD342IDX1")
	public String getCd342idx1() {
		return this.cd342idx1;
	}

	public void setCd342idx1(String cd342idx1) {
		this.cd342idx1 = cd342idx1;
	}

	@Column(name = "CD342IDX2")
	public String getCd342idx2() {
		return this.cd342idx2;
	}

	public void setCd342idx2(String cd342idx2) {
		this.cd342idx2 = cd342idx2;
	}

	@Column(name = "CD343IDX1")
	public String getCd343idx1() {
		return this.cd343idx1;
	}

	public void setCd343idx1(String cd343idx1) {
		this.cd343idx1 = cd343idx1;
	}

	@Column(name = "CD343IDX2")
	public String getCd343idx2() {
		return this.cd343idx2;
	}

	public void setCd343idx2(String cd343idx2) {
		this.cd343idx2 = cd343idx2;
	}

	@Column(name = "CD400IDX1")
	public String getCd400idx1() {
		return this.cd400idx1;
	}

	public void setCd400idx1(String cd400idx1) {
		this.cd400idx1 = cd400idx1;
	}

	@Column(name = "CD400IDX2")
	public String getCd400idx2() {
		return this.cd400idx2;
	}

	public void setCd400idx2(String cd400idx2) {
		this.cd400idx2 = cd400idx2;
	}

	@Column(name = "CD410IDX1")
	public String getCd410idx1() {
		return this.cd410idx1;
	}

	public void setCd410idx1(String cd410idx1) {
		this.cd410idx1 = cd410idx1;
	}

	@Column(name = "CD410IDX2")
	public String getCd410idx2() {
		return this.cd410idx2;
	}

	public void setCd410idx2(String cd410idx2) {
		this.cd410idx2 = cd410idx2;
	}

	@Column(name = "CD411IDX1")
	public String getCd411idx1() {
		return this.cd411idx1;
	}

	public void setCd411idx1(String cd411idx1) {
		this.cd411idx1 = cd411idx1;
	}

	@Column(name = "CD411IDX2")
	public String getCd411idx2() {
		return this.cd411idx2;
	}

	public void setCd411idx2(String cd411idx2) {
		this.cd411idx2 = cd411idx2;
	}

	@Column(name = "CD4111IDX1")
	public String getCd4111idx1() {
		return this.cd4111idx1;
	}

	public void setCd4111idx1(String cd4111idx1) {
		this.cd4111idx1 = cd4111idx1;
	}

	@Column(name = "CD4111IDX2")
	public String getCd4111idx2() {
		return this.cd4111idx2;
	}

	public void setCd4111idx2(String cd4111idx2) {
		this.cd4111idx2 = cd4111idx2;
	}

	@Column(name = "CD4112IDX1")
	public String getCd4112idx1() {
		return this.cd4112idx1;
	}

	public void setCd4112idx1(String cd4112idx1) {
		this.cd4112idx1 = cd4112idx1;
	}

	@Column(name = "CD4112IDX2")
	public String getCd4112idx2() {
		return this.cd4112idx2;
	}

	public void setCd4112idx2(String cd4112idx2) {
		this.cd4112idx2 = cd4112idx2;
	}

	@Column(name = "CD412IDX1")
	public String getCd412idx1() {
		return this.cd412idx1;
	}

	public void setCd412idx1(String cd412idx1) {
		this.cd412idx1 = cd412idx1;
	}

	@Column(name = "CD412IDX2")
	public String getCd412idx2() {
		return this.cd412idx2;
	}

	public void setCd412idx2(String cd412idx2) {
		this.cd412idx2 = cd412idx2;
	}

	@Column(name = "CD413IDX1")
	public String getCd413idx1() {
		return this.cd413idx1;
	}

	public void setCd413idx1(String cd413idx1) {
		this.cd413idx1 = cd413idx1;
	}

	@Column(name = "CD413IDX2")
	public String getCd413idx2() {
		return this.cd413idx2;
	}

	public void setCd413idx2(String cd413idx2) {
		this.cd413idx2 = cd413idx2;
	}

	@Column(name = "CD414IDX1")
	public String getCd414idx1() {
		return this.cd414idx1;
	}

	public void setCd414idx1(String cd414idx1) {
		this.cd414idx1 = cd414idx1;
	}

	@Column(name = "CD414IDX2")
	public String getCd414idx2() {
		return this.cd414idx2;
	}

	public void setCd414idx2(String cd414idx2) {
		this.cd414idx2 = cd414idx2;
	}

	@Column(name = "CD415IDX1")
	public String getCd415idx1() {
		return this.cd415idx1;
	}

	public void setCd415idx1(String cd415idx1) {
		this.cd415idx1 = cd415idx1;
	}

	@Column(name = "CD415IDX2")
	public String getCd415idx2() {
		return this.cd415idx2;
	}

	public void setCd415idx2(String cd415idx2) {
		this.cd415idx2 = cd415idx2;
	}

	@Column(name = "CD416IDX1")
	public String getCd416idx1() {
		return this.cd416idx1;
	}

	public void setCd416idx1(String cd416idx1) {
		this.cd416idx1 = cd416idx1;
	}

	@Column(name = "CD416IDX2")
	public String getCd416idx2() {
		return this.cd416idx2;
	}

	public void setCd416idx2(String cd416idx2) {
		this.cd416idx2 = cd416idx2;
	}

	@Column(name = "CD417IDX1")
	public String getCd417idx1() {
		return this.cd417idx1;
	}

	public void setCd417idx1(String cd417idx1) {
		this.cd417idx1 = cd417idx1;
	}

	@Column(name = "CD417IDX2")
	public String getCd417idx2() {
		return this.cd417idx2;
	}

	public void setCd417idx2(String cd417idx2) {
		this.cd417idx2 = cd417idx2;
	}

	@Column(name = "CD418IDX1")
	public String getCd418idx1() {
		return this.cd418idx1;
	}

	public void setCd418idx1(String cd418idx1) {
		this.cd418idx1 = cd418idx1;
	}

	@Column(name = "CD418IDX2")
	public String getCd418idx2() {
		return this.cd418idx2;
	}

	public void setCd418idx2(String cd418idx2) {
		this.cd418idx2 = cd418idx2;
	}

	@Column(name = "CD419IDX1")
	public String getCd419idx1() {
		return this.cd419idx1;
	}

	public void setCd419idx1(String cd419idx1) {
		this.cd419idx1 = cd419idx1;
	}

	@Column(name = "CD419IDX2")
	public String getCd419idx2() {
		return this.cd419idx2;
	}

	public void setCd419idx2(String cd419idx2) {
		this.cd419idx2 = cd419idx2;
	}

	@Column(name = "CD420IDX1")
	public String getCd420idx1() {
		return this.cd420idx1;
	}

	public void setCd420idx1(String cd420idx1) {
		this.cd420idx1 = cd420idx1;
	}

	@Column(name = "CD420IDX2")
	public String getCd420idx2() {
		return this.cd420idx2;
	}

	public void setCd420idx2(String cd420idx2) {
		this.cd420idx2 = cd420idx2;
	}

	@Column(name = "CD421IDX1")
	public String getCd421idx1() {
		return this.cd421idx1;
	}

	public void setCd421idx1(String cd421idx1) {
		this.cd421idx1 = cd421idx1;
	}

	@Column(name = "CD421IDX2")
	public String getCd421idx2() {
		return this.cd421idx2;
	}

	public void setCd421idx2(String cd421idx2) {
		this.cd421idx2 = cd421idx2;
	}

	@Column(name = "CD4211IDX1")
	public String getCd4211idx1() {
		return this.cd4211idx1;
	}

	public void setCd4211idx1(String cd4211idx1) {
		this.cd4211idx1 = cd4211idx1;
	}

	@Column(name = "CD4211IDX2")
	public String getCd4211idx2() {
		return this.cd4211idx2;
	}

	public void setCd4211idx2(String cd4211idx2) {
		this.cd4211idx2 = cd4211idx2;
	}

	@Column(name = "CD4212IDX1")
	public String getCd4212idx1() {
		return this.cd4212idx1;
	}

	public void setCd4212idx1(String cd4212idx1) {
		this.cd4212idx1 = cd4212idx1;
	}

	@Column(name = "CD4212IDX2")
	public String getCd4212idx2() {
		return this.cd4212idx2;
	}

	public void setCd4212idx2(String cd4212idx2) {
		this.cd4212idx2 = cd4212idx2;
	}

	@Column(name = "CD422IDX1")
	public String getCd422idx1() {
		return this.cd422idx1;
	}

	public void setCd422idx1(String cd422idx1) {
		this.cd422idx1 = cd422idx1;
	}

	@Column(name = "CD422IDX2")
	public String getCd422idx2() {
		return this.cd422idx2;
	}

	public void setCd422idx2(String cd422idx2) {
		this.cd422idx2 = cd422idx2;
	}

	@Column(name = "CD429IDX1")
	public String getCd429idx1() {
		return this.cd429idx1;
	}

	public void setCd429idx1(String cd429idx1) {
		this.cd429idx1 = cd429idx1;
	}

	@Column(name = "CD429IDX2")
	public String getCd429idx2() {
		return this.cd429idx2;
	}

	public void setCd429idx2(String cd429idx2) {
		this.cd429idx2 = cd429idx2;
	}

	@Column(name = "CD430IDX1")
	public String getCd430idx1() {
		return this.cd430idx1;
	}

	public void setCd430idx1(String cd430idx1) {
		this.cd430idx1 = cd430idx1;
	}

	@Column(name = "CD430IDX2")
	public String getCd430idx2() {
		return this.cd430idx2;
	}

	public void setCd430idx2(String cd430idx2) {
		this.cd430idx2 = cd430idx2;
	}

	@Column(name = "CD431IDX1")
	public String getCd431idx1() {
		return this.cd431idx1;
	}

	public void setCd431idx1(String cd431idx1) {
		this.cd431idx1 = cd431idx1;
	}

	@Column(name = "CD431IDX2")
	public String getCd431idx2() {
		return this.cd431idx2;
	}

	public void setCd431idx2(String cd431idx2) {
		this.cd431idx2 = cd431idx2;
	}

	@Column(name = "CD432IDX1")
	public String getCd432idx1() {
		return this.cd432idx1;
	}

	public void setCd432idx1(String cd432idx1) {
		this.cd432idx1 = cd432idx1;
	}

	@Column(name = "CD432IDX2")
	public String getCd432idx2() {
		return this.cd432idx2;
	}

	public void setCd432idx2(String cd432idx2) {
		this.cd432idx2 = cd432idx2;
	}

	@Column(name = "CD440IDX1")
	public String getCd440idx1() {
		return this.cd440idx1;
	}

	public void setCd440idx1(String cd440idx1) {
		this.cd440idx1 = cd440idx1;
	}

	@Column(name = "CD440IDX2")
	public String getCd440idx2() {
		return this.cd440idx2;
	}

	public void setCd440idx2(String cd440idx2) {
		this.cd440idx2 = cd440idx2;
	}

	@Column(name = "CD500IDX1")
	public String getCd500idx1() {
		return this.cd500idx1;
	}

	public void setCd500idx1(String cd500idx1) {
		this.cd500idx1 = cd500idx1;
	}

	@Column(name = "CD500IDX2")
	public String getCd500idx2() {
		return this.cd500idx2;
	}

	public void setCd500idx2(String cd500idx2) {
		this.cd500idx2 = cd500idx2;
	}

	@Column(name = "KQ01")
	public String getKq01() {
		return this.kq01;
	}

	public void setKq01(String kq01) {
		this.kq01 = kq01;
	}

	@Column(name = "KQ02")
	public String getKq02() {
		return this.kq02;
	}

	public void setKq02(String kq02) {
		this.kq02 = kq02;
	}

	@Column(name = "KQ10")
	public String getKq10() {
		return this.kq10;
	}

	public void setKq10(String kq10) {
		this.kq10 = kq10;
	}

	@Column(name = "KQ11")
	public String getKq11() {
		return this.kq11;
	}

	public void setKq11(String kq11) {
		this.kq11 = kq11;
	}

	@Column(name = "KQ20")
	public String getKq20() {
		return this.kq20;
	}

	public void setKq20(String kq20) {
		this.kq20 = kq20;
	}

	@Column(name = "KQ21")
	public String getKq21() {
		return this.kq21;
	}

	public void setKq21(String kq21) {
		this.kq21 = kq21;
	}

	@Column(name = "KQ22")
	public String getKq22() {
		return this.kq22;
	}

	public void setKq22(String kq22) {
		this.kq22 = kq22;
	}

	@Column(name = "KQ23")
	public String getKq23() {
		return this.kq23;
	}

	public void setKq23(String kq23) {
		this.kq23 = kq23;
	}

	@Column(name = "KQ24")
	public String getKq24() {
		return this.kq24;
	}

	public void setKq24(String kq24) {
		this.kq24 = kq24;
	}

	@Column(name = "KQ25")
	public String getKq25() {
		return this.kq25;
	}

	public void setKq25(String kq25) {
		this.kq25 = kq25;
	}

	@Column(name = "KQ26")
	public String getKq26() {
		return this.kq26;
	}

	public void setKq26(String kq26) {
		this.kq26 = kq26;
	}

	@Column(name = "KQ30")
	public String getKq30() {
		return this.kq30;
	}

	public void setKq30(String kq30) {
		this.kq30 = kq30;
	}

	@Column(name = "KQ31")
	public String getKq31() {
		return this.kq31;
	}

	public void setKq31(String kq31) {
		this.kq31 = kq31;
	}

	@Column(name = "KQ32")
	public String getKq32() {
		return this.kq32;
	}

	public void setKq32(String kq32) {
		this.kq32 = kq32;
	}

	@Column(name = "KQ40")
	public String getKq40() {
		return this.kq40;
	}

	public void setKq40(String kq40) {
		this.kq40 = kq40;
	}

	@Column(name = "KQ50")
	public String getKq50() {
		return this.kq50;
	}

	public void setKq50(String kq50) {
		this.kq50 = kq50;
	}

	@Column(name = "KQ51")
	public String getKq51() {
		return this.kq51;
	}

	public void setKq51(String kq51) {
		this.kq51 = kq51;
	}

	@Column(name = "KQ52")
	public String getKq52() {
		return this.kq52;
	}

	public void setKq52(String kq52) {
		this.kq52 = kq52;
	}

	@Column(name = "KQ60")
	public String getKq60() {
		return this.kq60;
	}

	public void setKq60(String kq60) {
		this.kq60 = kq60;
	}

	@Column(name = "KQ61")
	public String getKq61() {
		return this.kq61;
	}

	public void setKq61(String kq61) {
		this.kq61 = kq61;
	}

	@Column(name = "KQ62")
	public String getKq62() {
		return this.kq62;
	}

	public void setKq62(String kq62) {
		this.kq62 = kq62;
	}

	@Column(name = "KQ70")
	public String getKq70() {
		return this.kq70;
	}

	public void setKq70(String kq70) {
		this.kq70 = kq70;
	}

	@Column(name = "KQ71")
	public String getKq71() {
		return this.kq71;
	}

	public void setKq71(String kq71) {
		this.kq71 = kq71;
	}

	@Column(name = "LCT01")
	public String getLct01() {
		return this.lct01;
	}

	public void setLct01(String lct01) {
		this.lct01 = lct01;
	}

	@Column(name = "LCT02")
	public String getLct02() {
		return this.lct02;
	}

	public void setLct02(String lct02) {
		this.lct02 = lct02;
	}

	@Column(name = "LCT03")
	public String getLct03() {
		return this.lct03;
	}

	public void setLct03(String lct03) {
		this.lct03 = lct03;
	}

	@Column(name = "LCT04")
	public String getLct04() {
		return this.lct04;
	}

	public void setLct04(String lct04) {
		this.lct04 = lct04;
	}

	@Column(name = "LCT05")
	public String getLct05() {
		return this.lct05;
	}

	public void setLct05(String lct05) {
		this.lct05 = lct05;
	}

	@Column(name = "LCT06")
	public String getLct06() {
		return this.lct06;
	}

	public void setLct06(String lct06) {
		this.lct06 = lct06;
	}

	@Column(name = "LCT07")
	public String getLct07() {
		return this.lct07;
	}

	public void setLct07(String lct07) {
		this.lct07 = lct07;
	}

	@Column(name = "LCT20")
	public String getLct20() {
		return this.lct20;
	}

	public void setLct20(String lct20) {
		this.lct20 = lct20;
	}

	@Column(name = "LCT21")
	public String getLct21() {
		return this.lct21;
	}

	public void setLct21(String lct21) {
		this.lct21 = lct21;
	}

	@Column(name = "LCT22")
	public String getLct22() {
		return this.lct22;
	}

	public void setLct22(String lct22) {
		this.lct22 = lct22;
	}

	@Column(name = "LCT23")
	public String getLct23() {
		return this.lct23;
	}

	public void setLct23(String lct23) {
		this.lct23 = lct23;
	}

	@Column(name = "LCT24")
	public String getLct24() {
		return this.lct24;
	}

	public void setLct24(String lct24) {
		this.lct24 = lct24;
	}

	@Column(name = "LCT25")
	public String getLct25() {
		return this.lct25;
	}

	public void setLct25(String lct25) {
		this.lct25 = lct25;
	}

	@Column(name = "LCT26")
	public String getLct26() {
		return this.lct26;
	}

	public void setLct26(String lct26) {
		this.lct26 = lct26;
	}

	@Column(name = "LCT27")
	public String getLct27() {
		return this.lct27;
	}

	public void setLct27(String lct27) {
		this.lct27 = lct27;
	}

	@Column(name = "LCT30")
	public String getLct30() {
		return this.lct30;
	}

	public void setLct30(String lct30) {
		this.lct30 = lct30;
	}

	@Column(name = "LCT31")
	public String getLct31() {
		return this.lct31;
	}

	public void setLct31(String lct31) {
		this.lct31 = lct31;
	}

	@Column(name = "LCT32")
	public String getLct32() {
		return this.lct32;
	}

	public void setLct32(String lct32) {
		this.lct32 = lct32;
	}

	@Column(name = "LCT33")
	public String getLct33() {
		return this.lct33;
	}

	public void setLct33(String lct33) {
		this.lct33 = lct33;
	}

	@Column(name = "LCT34")
	public String getLct34() {
		return this.lct34;
	}

	public void setLct34(String lct34) {
		this.lct34 = lct34;
	}

	@Column(name = "LCT35")
	public String getLct35() {
		return this.lct35;
	}

	public void setLct35(String lct35) {
		this.lct35 = lct35;
	}

	@Column(name = "LCT36")
	public String getLct36() {
		return this.lct36;
	}

	public void setLct36(String lct36) {
		this.lct36 = lct36;
	}

	@Column(name = "LCT40")
	public String getLct40() {
		return this.lct40;
	}

	public void setLct40(String lct40) {
		this.lct40 = lct40;
	}

	@Column(name = "LCT50")
	public String getLct50() {
		return this.lct50;
	}

	public void setLct50(String lct50) {
		this.lct50 = lct50;
	}

	@Column(name = "LCT60")
	public String getLct60() {
		return this.lct60;
	}

	public void setLct60(String lct60) {
		this.lct60 = lct60;
	}

	@Column(name = "LCT61")
	public String getLct61() {
		return this.lct61;
	}

	public void setLct61(String lct61) {
		this.lct61 = lct61;
	}

	@Column(name = "LCT70")
	public String getLct70() {
		return this.lct70;
	}

	public void setLct70(String lct70) {
		this.lct70 = lct70;
	}

	@Column(name = "LCG01")
	public String getLcg01() {
		return this.lcg01;
	}

	public void setLcg01(String lcg01) {
		this.lcg01 = lcg01;
	}

	@Column(name = "LCG02")
	public String getLcg02() {
		return this.lcg02;
	}

	public void setLcg02(String lcg02) {
		this.lcg02 = lcg02;
	}

	@Column(name = "LCG03")
	public String getLcg03() {
		return this.lcg03;
	}

	public void setLcg03(String lcg03) {
		this.lcg03 = lcg03;
	}

	@Column(name = "LCG04")
	public String getLcg04() {
		return this.lcg04;
	}

	public void setLcg04(String lcg04) {
		this.lcg04 = lcg04;
	}

	@Column(name = "LCG05")
	public String getLcg05() {
		return this.lcg05;
	}

	public void setLcg05(String lcg05) {
		this.lcg05 = lcg05;
	}

	@Column(name = "LCG06")
	public String getLcg06() {
		return this.lcg06;
	}

	public void setLcg06(String lcg06) {
		this.lcg06 = lcg06;
	}

	@Column(name = "LCG07")
	public String getLcg07() {
		return this.lcg07;
	}

	public void setLcg07(String lcg07) {
		this.lcg07 = lcg07;
	}

	@Column(name = "LCG08")
	public String getLcg08() {
		return this.lcg08;
	}

	public void setLcg08(String lcg08) {
		this.lcg08 = lcg08;
	}

	@Column(name = "LCG09")
	public String getLcg09() {
		return this.lcg09;
	}

	public void setLcg09(String lcg09) {
		this.lcg09 = lcg09;
	}

	@Column(name = "LCG10")
	public String getLcg10() {
		return this.lcg10;
	}

	public void setLcg10(String lcg10) {
		this.lcg10 = lcg10;
	}

	@Column(name = "LCG11")
	public String getLcg11() {
		return this.lcg11;
	}

	public void setLcg11(String lcg11) {
		this.lcg11 = lcg11;
	}

	@Column(name = "LCG12")
	public String getLcg12() {
		return this.lcg12;
	}

	public void setLcg12(String lcg12) {
		this.lcg12 = lcg12;
	}

	@Column(name = "LCG13")
	public String getLcg13() {
		return this.lcg13;
	}

	public void setLcg13(String lcg13) {
		this.lcg13 = lcg13;
	}

	@Column(name = "LCG14")
	public String getLcg14() {
		return this.lcg14;
	}

	public void setLcg14(String lcg14) {
		this.lcg14 = lcg14;
	}

	@Column(name = "LCG15")
	public String getLcg15() {
		return this.lcg15;
	}

	public void setLcg15(String lcg15) {
		this.lcg15 = lcg15;
	}

	@Column(name = "LCG16")
	public String getLcg16() {
		return this.lcg16;
	}

	public void setLcg16(String lcg16) {
		this.lcg16 = lcg16;
	}

	@Column(name = "LCG17")
	public String getLcg17() {
		return this.lcg17;
	}

	public void setLcg17(String lcg17) {
		this.lcg17 = lcg17;
	}

	@Column(name = "LCG18")
	public String getLcg18() {
		return this.lcg18;
	}

	public void setLcg18(String lcg18) {
		this.lcg18 = lcg18;
	}

	@Column(name = "LCG20")
	public String getLcg20() {
		return this.lcg20;
	}

	public void setLcg20(String lcg20) {
		this.lcg20 = lcg20;
	}

	@Column(name = "LCG21")
	public String getLcg21() {
		return this.lcg21;
	}

	public void setLcg21(String lcg21) {
		this.lcg21 = lcg21;
	}

	@Column(name = "LCG22")
	public String getLcg22() {
		return this.lcg22;
	}

	public void setLcg22(String lcg22) {
		this.lcg22 = lcg22;
	}

	@Column(name = "LCG23")
	public String getLcg23() {
		return this.lcg23;
	}

	public void setLcg23(String lcg23) {
		this.lcg23 = lcg23;
	}

	@Column(name = "LCG24")
	public String getLcg24() {
		return this.lcg24;
	}

	public void setLcg24(String lcg24) {
		this.lcg24 = lcg24;
	}

	@Column(name = "LCG25")
	public String getLcg25() {
		return this.lcg25;
	}

	public void setLcg25(String lcg25) {
		this.lcg25 = lcg25;
	}

	@Column(name = "LCG26")
	public String getLcg26() {
		return this.lcg26;
	}

	public void setLcg26(String lcg26) {
		this.lcg26 = lcg26;
	}

	@Column(name = "LCG27")
	public String getLcg27() {
		return this.lcg27;
	}

	public void setLcg27(String lcg27) {
		this.lcg27 = lcg27;
	}

	@Column(name = "LCG30")
	public String getLcg30() {
		return this.lcg30;
	}

	public void setLcg30(String lcg30) {
		this.lcg30 = lcg30;
	}

	@Column(name = "LCG31")
	public String getLcg31() {
		return this.lcg31;
	}

	public void setLcg31(String lcg31) {
		this.lcg31 = lcg31;
	}

	@Column(name = "LCG32")
	public String getLcg32() {
		return this.lcg32;
	}

	public void setLcg32(String lcg32) {
		this.lcg32 = lcg32;
	}

	@Column(name = "LCG33")
	public String getLcg33() {
		return this.lcg33;
	}

	public void setLcg33(String lcg33) {
		this.lcg33 = lcg33;
	}

	@Column(name = "LCG34")
	public String getLcg34() {
		return this.lcg34;
	}

	public void setLcg34(String lcg34) {
		this.lcg34 = lcg34;
	}

	@Column(name = "LCG35")
	public String getLcg35() {
		return this.lcg35;
	}

	public void setLcg35(String lcg35) {
		this.lcg35 = lcg35;
	}

	@Column(name = "LCG36")
	public String getLcg36() {
		return this.lcg36;
	}

	public void setLcg36(String lcg36) {
		this.lcg36 = lcg36;
	}

	@Column(name = "LCG40")
	public String getLcg40() {
		return this.lcg40;
	}

	public void setLcg40(String lcg40) {
		this.lcg40 = lcg40;
	}

	@Column(name = "LCG50")
	public String getLcg50() {
		return this.lcg50;
	}

	public void setLcg50(String lcg50) {
		this.lcg50 = lcg50;
	}

	@Column(name = "LCG60")
	public String getLcg60() {
		return this.lcg60;
	}

	public void setLcg60(String lcg60) {
		this.lcg60 = lcg60;
	}

	@Column(name = "LCG61")
	public String getLcg61() {
		return this.lcg61;
	}

	public void setLcg61(String lcg61) {
		this.lcg61 = lcg61;
	}

	@Column(name = "LCG70")
	public String getLcg70() {
		return this.lcg70;
	}

	public void setLcg70(String lcg70) {
		this.lcg70 = lcg70;
	}

	@Column(name = "DONGLOI", precision = 22, scale = 0)
	public BigDecimal getDongloi() {
		return this.dongloi;
	}

	public void setDongloi(BigDecimal dongloi) {
		this.dongloi = dongloi;
	}

	@Column(name = "DONGLOITCTD", precision = 22, scale = 0)
	public BigDecimal getDongloitctd() {
		return this.dongloitctd;
	}

	public void setDongloitctd(BigDecimal dongloitctd) {
		this.dongloitctd = dongloitctd;
	}

}
