package entity;

// Generated Apr 10, 2020 2:07:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RpDetailK3213 generated by hbm2java
 */
@Entity
@Table(name = "RP_DETAIL_K3213", schema = "CIC")
public class RpDetailK3213 implements java.io.Serializable {

	private String id;
	private RpSum rpSum;
	private String macn;
	private String tencn;
	private String reportDate;
	private String status;
	private String errorCode;
	private Date createdDate;
	private String createdBy;
	private Date modifiedDate;
	private String modifiedBy;
	private String dn002;
	private String dn003;
	private String dn004;
	private String dna05;
	private String dna06;
	private String dna07;
	private String dna08;
	private String dnb091;
	private String dnb092;
	private String dnb10;
	private String dnb11;
	private String dnb12;
	private String dnb13;
	private String kb001;
	private String kb002;
	private String kb003;
	private String dna05aa;
	private String dna05bb;
	private String dna05cc;
	private String dnb091bb;
	private String dnb092bb;
	private String dnb092cc;

	public RpDetailK3213() {
	}

	public RpDetailK3213(String id, RpSum rpSum) {
		this.id = id;
		this.rpSum = rpSum;
	}

	public RpDetailK3213(String id, RpSum rpSum, String macn, String tencn, String reportDate, String status,
			String errorCode, Date createdDate, String createdBy, Date modifiedDate, String modifiedBy, String dn002,
			String dn003, String dn004, String dna05, String dna06, String dna07, String dna08, String dnb091,
			String dnb092, String dnb10, String dnb11, String dnb12, String dnb13, String kb001, String kb002,
			String kb003, String dna05aa, String dna05bb, String dna05cc, String dnb091bb, String dnb092bb,
			String dnb092cc) {
		this.id = id;
		this.rpSum = rpSum;
		this.macn = macn;
		this.tencn = tencn;
		this.reportDate = reportDate;
		this.status = status;
		this.errorCode = errorCode;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
		this.dn002 = dn002;
		this.dn003 = dn003;
		this.dn004 = dn004;
		this.dna05 = dna05;
		this.dna06 = dna06;
		this.dna07 = dna07;
		this.dna08 = dna08;
		this.dnb091 = dnb091;
		this.dnb092 = dnb092;
		this.dnb10 = dnb10;
		this.dnb11 = dnb11;
		this.dnb12 = dnb12;
		this.dnb13 = dnb13;
		this.kb001 = kb001;
		this.kb002 = kb002;
		this.kb003 = kb003;
		this.dna05aa = dna05aa;
		this.dna05bb = dna05bb;
		this.dna05cc = dna05cc;
		this.dnb091bb = dnb091bb;
		this.dnb092bb = dnb092bb;
		this.dnb092cc = dnb092cc;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 40)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REPORT_ID", nullable = false)
	public RpSum getRpSum() {
		return this.rpSum;
	}

	public void setRpSum(RpSum rpSum) {
		this.rpSum = rpSum;
	}

	@Column(name = "MACN")
	public String getMacn() {
		return this.macn;
	}

	public void setMacn(String macn) {
		this.macn = macn;
	}

	@Column(name = "TENCN", length = 510)
	public String getTencn() {
		return this.tencn;
	}

	public void setTencn(String tencn) {
		this.tencn = tencn;
	}

	@Column(name = "NGAYBAOCAO")
	public String getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(String reportDate) {
		this.reportDate = reportDate;
	}

	@Column(name = "STATUS", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "ERROR_CODE", length = 1000)
	public String getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", length = 7)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "MODIFIED_BY")
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "DN002")
	public String getDn002() {
		return this.dn002;
	}

	public void setDn002(String dn002) {
		this.dn002 = dn002;
	}

	@Column(name = "DN003")
	public String getDn003() {
		return this.dn003;
	}

	public void setDn003(String dn003) {
		this.dn003 = dn003;
	}

	@Column(name = "DN004")
	public String getDn004() {
		return this.dn004;
	}

	public void setDn004(String dn004) {
		this.dn004 = dn004;
	}

	@Column(name = "DNA05")
	public String getDna05() {
		return this.dna05;
	}

	public void setDna05(String dna05) {
		this.dna05 = dna05;
	}

	@Column(name = "DNA06")
	public String getDna06() {
		return this.dna06;
	}

	public void setDna06(String dna06) {
		this.dna06 = dna06;
	}

	@Column(name = "DNA07")
	public String getDna07() {
		return this.dna07;
	}

	public void setDna07(String dna07) {
		this.dna07 = dna07;
	}

	@Column(name = "DNA08")
	public String getDna08() {
		return this.dna08;
	}

	public void setDna08(String dna08) {
		this.dna08 = dna08;
	}

	@Column(name = "DNB091")
	public String getDnb091() {
		return this.dnb091;
	}

	public void setDnb091(String dnb091) {
		this.dnb091 = dnb091;
	}

	@Column(name = "DNB092")
	public String getDnb092() {
		return this.dnb092;
	}

	public void setDnb092(String dnb092) {
		this.dnb092 = dnb092;
	}

	@Column(name = "DNB10")
	public String getDnb10() {
		return this.dnb10;
	}

	public void setDnb10(String dnb10) {
		this.dnb10 = dnb10;
	}

	@Column(name = "DNB11")
	public String getDnb11() {
		return this.dnb11;
	}

	public void setDnb11(String dnb11) {
		this.dnb11 = dnb11;
	}

	@Column(name = "DNB12")
	public String getDnb12() {
		return this.dnb12;
	}

	public void setDnb12(String dnb12) {
		this.dnb12 = dnb12;
	}

	@Column(name = "DNB13")
	public String getDnb13() {
		return this.dnb13;
	}

	public void setDnb13(String dnb13) {
		this.dnb13 = dnb13;
	}

	@Column(name = "KB001")
	public String getKb001() {
		return this.kb001;
	}

	public void setKb001(String kb001) {
		this.kb001 = kb001;
	}

	@Column(name = "KB002")
	public String getKb002() {
		return this.kb002;
	}

	public void setKb002(String kb002) {
		this.kb002 = kb002;
	}

	@Column(name = "KB003")
	public String getKb003() {
		return this.kb003;
	}

	public void setKb003(String kb003) {
		this.kb003 = kb003;
	}

	@Column(name = "DNA05AA")
	public String getDna05aa() {
		return this.dna05aa;
	}

	public void setDna05aa(String dna05aa) {
		this.dna05aa = dna05aa;
	}

	@Column(name = "DNA05BB")
	public String getDna05bb() {
		return this.dna05bb;
	}

	public void setDna05bb(String dna05bb) {
		this.dna05bb = dna05bb;
	}

	@Column(name = "DNA05CC")
	public String getDna05cc() {
		return this.dna05cc;
	}

	public void setDna05cc(String dna05cc) {
		this.dna05cc = dna05cc;
	}

	@Column(name = "DNB091BB")
	public String getDnb091bb() {
		return this.dnb091bb;
	}

	public void setDnb091bb(String dnb091bb) {
		this.dnb091bb = dnb091bb;
	}

	@Column(name = "DNB092BB")
	public String getDnb092bb() {
		return this.dnb092bb;
	}

	public void setDnb092bb(String dnb092bb) {
		this.dnb092bb = dnb092bb;
	}

	@Column(name = "DNB092CC")
	public String getDnb092cc() {
		return this.dnb092cc;
	}

	public void setDnb092cc(String dnb092cc) {
		this.dnb092cc = dnb092cc;
	}

}
