package entity;

// Generated Apr 10, 2020 2:07:06 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RpDetailK31xx generated by hbm2java
 */
@Entity
@Table(name = "RP_DETAIL_K31XX", schema = "CIC")
public class RpDetailK31xx implements java.io.Serializable {

	private String id;
	private RpSum rpSum;
	private String macn;
	private String tencn;
	private String ngaybaocao;
	private String hd002;
	private String hd003;
	private String hd004;
	private String hd005;
	private String hd006;
	private String hd012;
	private String soku;
	private String hd007;
	private String hd008;
	private String hd009;
	private String hd010;
	private String hd011;
	private String hd013;
	private String hd014;
	private String hd015;
	private String hd016;
	private String hd017;
	private String hd018;
	private String hd019;
	private String hd020;
	private String hd021;
	private String hd022;
	private Boolean status;
	private String errorCode;
	private Date createdDate;
	private String createdBy;
	private Date modifiedDate;
	private String modifiedBy;
	private BigDecimal dongloi;
	private BigDecimal dongloitctd;

	public RpDetailK31xx() {
	}

	public RpDetailK31xx(String id, RpSum rpSum) {
		this.id = id;
		this.rpSum = rpSum;
	}

	public RpDetailK31xx(String id, RpSum rpSum, String macn, String tencn, String ngaybaocao, String hd002,
			String hd003, String hd004, String hd005, String hd006, String hd012, String soku, String hd007,
			String hd008, String hd009, String hd010, String hd011, String hd013, String hd014, String hd015,
			String hd016, String hd017, String hd018, String hd019, String hd020, String hd021, String hd022,
			Boolean status, String errorCode, Date createdDate, String createdBy, Date modifiedDate, String modifiedBy,
			BigDecimal dongloi, BigDecimal dongloitctd) {
		this.id = id;
		this.rpSum = rpSum;
		this.macn = macn;
		this.tencn = tencn;
		this.ngaybaocao = ngaybaocao;
		this.hd002 = hd002;
		this.hd003 = hd003;
		this.hd004 = hd004;
		this.hd005 = hd005;
		this.hd006 = hd006;
		this.hd012 = hd012;
		this.soku = soku;
		this.hd007 = hd007;
		this.hd008 = hd008;
		this.hd009 = hd009;
		this.hd010 = hd010;
		this.hd011 = hd011;
		this.hd013 = hd013;
		this.hd014 = hd014;
		this.hd015 = hd015;
		this.hd016 = hd016;
		this.hd017 = hd017;
		this.hd018 = hd018;
		this.hd019 = hd019;
		this.hd020 = hd020;
		this.hd021 = hd021;
		this.hd022 = hd022;
		this.status = status;
		this.errorCode = errorCode;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
		this.dongloi = dongloi;
		this.dongloitctd = dongloitctd;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 40)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REPORT_ID", nullable = false)
	public RpSum getRpSum() {
		return this.rpSum;
	}

	public void setRpSum(RpSum rpSum) {
		this.rpSum = rpSum;
	}

	@Column(name = "MACN")
	public String getMacn() {
		return this.macn;
	}

	public void setMacn(String macn) {
		this.macn = macn;
	}

	@Column(name = "TENCN")
	public String getTencn() {
		return this.tencn;
	}

	public void setTencn(String tencn) {
		this.tencn = tencn;
	}

	@Column(name = "NGAYBAOCAO")
	public String getNgaybaocao() {
		return this.ngaybaocao;
	}

	public void setNgaybaocao(String ngaybaocao) {
		this.ngaybaocao = ngaybaocao;
	}

	@Column(name = "HD002")
	public String getHd002() {
		return this.hd002;
	}

	public void setHd002(String hd002) {
		this.hd002 = hd002;
	}

	@Column(name = "HD003")
	public String getHd003() {
		return this.hd003;
	}

	public void setHd003(String hd003) {
		this.hd003 = hd003;
	}

	@Column(name = "HD004")
	public String getHd004() {
		return this.hd004;
	}

	public void setHd004(String hd004) {
		this.hd004 = hd004;
	}

	@Column(name = "HD005")
	public String getHd005() {
		return this.hd005;
	}

	public void setHd005(String hd005) {
		this.hd005 = hd005;
	}

	@Column(name = "HD006")
	public String getHd006() {
		return this.hd006;
	}

	public void setHd006(String hd006) {
		this.hd006 = hd006;
	}

	@Column(name = "HD012")
	public String getHd012() {
		return this.hd012;
	}

	public void setHd012(String hd012) {
		this.hd012 = hd012;
	}

	@Column(name = "SOKU")
	public String getSoku() {
		return this.soku;
	}

	public void setSoku(String soku) {
		this.soku = soku;
	}

	@Column(name = "HD007")
	public String getHd007() {
		return this.hd007;
	}

	public void setHd007(String hd007) {
		this.hd007 = hd007;
	}

	@Column(name = "HD008")
	public String getHd008() {
		return this.hd008;
	}

	public void setHd008(String hd008) {
		this.hd008 = hd008;
	}

	@Column(name = "HD009")
	public String getHd009() {
		return this.hd009;
	}

	public void setHd009(String hd009) {
		this.hd009 = hd009;
	}

	@Column(name = "HD010")
	public String getHd010() {
		return this.hd010;
	}

	public void setHd010(String hd010) {
		this.hd010 = hd010;
	}

	@Column(name = "HD011")
	public String getHd011() {
		return this.hd011;
	}

	public void setHd011(String hd011) {
		this.hd011 = hd011;
	}

	@Column(name = "HD013")
	public String getHd013() {
		return this.hd013;
	}

	public void setHd013(String hd013) {
		this.hd013 = hd013;
	}

	@Column(name = "HD014")
	public String getHd014() {
		return this.hd014;
	}

	public void setHd014(String hd014) {
		this.hd014 = hd014;
	}

	@Column(name = "HD015")
	public String getHd015() {
		return this.hd015;
	}

	public void setHd015(String hd015) {
		this.hd015 = hd015;
	}

	@Column(name = "HD016")
	public String getHd016() {
		return this.hd016;
	}

	public void setHd016(String hd016) {
		this.hd016 = hd016;
	}

	@Column(name = "HD017")
	public String getHd017() {
		return this.hd017;
	}

	public void setHd017(String hd017) {
		this.hd017 = hd017;
	}

	@Column(name = "HD018")
	public String getHd018() {
		return this.hd018;
	}

	public void setHd018(String hd018) {
		this.hd018 = hd018;
	}

	@Column(name = "HD019")
	public String getHd019() {
		return this.hd019;
	}

	public void setHd019(String hd019) {
		this.hd019 = hd019;
	}

	@Column(name = "HD020")
	public String getHd020() {
		return this.hd020;
	}

	public void setHd020(String hd020) {
		this.hd020 = hd020;
	}

	@Column(name = "HD021")
	public String getHd021() {
		return this.hd021;
	}

	public void setHd021(String hd021) {
		this.hd021 = hd021;
	}

	@Column(name = "HD022")
	public String getHd022() {
		return this.hd022;
	}

	public void setHd022(String hd022) {
		this.hd022 = hd022;
	}

	@Column(name = "STATUS", precision = 1, scale = 0)
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "ERROR_CODE", length = 1000)
	public String getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", length = 7)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "MODIFIED_BY")
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "DONGLOI", precision = 22, scale = 0)
	public BigDecimal getDongloi() {
		return this.dongloi;
	}

	public void setDongloi(BigDecimal dongloi) {
		this.dongloi = dongloi;
	}

	@Column(name = "DONGLOITCTD", precision = 22, scale = 0)
	public BigDecimal getDongloitctd() {
		return this.dongloitctd;
	}

	public void setDongloitctd(BigDecimal dongloitctd) {
		this.dongloitctd = dongloitctd;
	}

}
