package entity;

// Generated Apr 10, 2020 2:07:06 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RpDetailK333 generated by hbm2java
 */
@Entity
@Table(name = "RP_DETAIL_K333", schema = "CIC")
public class RpDetailK333 implements java.io.Serializable {

	private String id;
	private String reportId;
	private Date createdDate;
	private String createdBy;
	private Date modifiedDate;
	private String modifiedBy;
	private Boolean status;
	private String errorCode;
	private String macn;
	private String tencn;
	private String ngaybaocao;
	private String th001;
	private String th002;
	private String th101;
	private String th106;
	private String th102;
	private String th103;
	private String th104;
	private String th105;
	private String th107;
	private String th108;
	private String th109;
	private String th110;
	private String th111;
	private String th112;
	private String th113;
	private BigDecimal dongloi;
	private BigDecimal dongloitctd;

	public RpDetailK333() {
	}

	public RpDetailK333(String id, String reportId) {
		this.id = id;
		this.reportId = reportId;
	}

	public RpDetailK333(String id, String reportId, Date createdDate, String createdBy, Date modifiedDate,
			String modifiedBy, Boolean status, String errorCode, String macn, String tencn, String ngaybaocao,
			String th001, String th002, String th101, String th106, String th102, String th103, String th104,
			String th105, String th107, String th108, String th109, String th110, String th111, String th112,
			String th113, BigDecimal dongloi, BigDecimal dongloitctd) {
		this.id = id;
		this.reportId = reportId;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
		this.status = status;
		this.errorCode = errorCode;
		this.macn = macn;
		this.tencn = tencn;
		this.ngaybaocao = ngaybaocao;
		this.th001 = th001;
		this.th002 = th002;
		this.th101 = th101;
		this.th106 = th106;
		this.th102 = th102;
		this.th103 = th103;
		this.th104 = th104;
		this.th105 = th105;
		this.th107 = th107;
		this.th108 = th108;
		this.th109 = th109;
		this.th110 = th110;
		this.th111 = th111;
		this.th112 = th112;
		this.th113 = th113;
		this.dongloi = dongloi;
		this.dongloitctd = dongloitctd;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 40)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "REPORT_ID", nullable = false, length = 40)
	public String getReportId() {
		return this.reportId;
	}

	public void setReportId(String reportId) {
		this.reportId = reportId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", length = 40)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", length = 7)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "MODIFIED_BY", length = 40)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "STATUS", precision = 1, scale = 0)
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "ERROR_CODE", length = 1000)
	public String getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "MACN")
	public String getMacn() {
		return this.macn;
	}

	public void setMacn(String macn) {
		this.macn = macn;
	}

	@Column(name = "TENCN")
	public String getTencn() {
		return this.tencn;
	}

	public void setTencn(String tencn) {
		this.tencn = tencn;
	}

	@Column(name = "NGAYBAOCAO")
	public String getNgaybaocao() {
		return this.ngaybaocao;
	}

	public void setNgaybaocao(String ngaybaocao) {
		this.ngaybaocao = ngaybaocao;
	}

	@Column(name = "TH001")
	public String getTh001() {
		return this.th001;
	}

	public void setTh001(String th001) {
		this.th001 = th001;
	}

	@Column(name = "TH002")
	public String getTh002() {
		return this.th002;
	}

	public void setTh002(String th002) {
		this.th002 = th002;
	}

	@Column(name = "TH101")
	public String getTh101() {
		return this.th101;
	}

	public void setTh101(String th101) {
		this.th101 = th101;
	}

	@Column(name = "TH106")
	public String getTh106() {
		return this.th106;
	}

	public void setTh106(String th106) {
		this.th106 = th106;
	}

	@Column(name = "TH102")
	public String getTh102() {
		return this.th102;
	}

	public void setTh102(String th102) {
		this.th102 = th102;
	}

	@Column(name = "TH103")
	public String getTh103() {
		return this.th103;
	}

	public void setTh103(String th103) {
		this.th103 = th103;
	}

	@Column(name = "TH104")
	public String getTh104() {
		return this.th104;
	}

	public void setTh104(String th104) {
		this.th104 = th104;
	}

	@Column(name = "TH105")
	public String getTh105() {
		return this.th105;
	}

	public void setTh105(String th105) {
		this.th105 = th105;
	}

	@Column(name = "TH107")
	public String getTh107() {
		return this.th107;
	}

	public void setTh107(String th107) {
		this.th107 = th107;
	}

	@Column(name = "TH108")
	public String getTh108() {
		return this.th108;
	}

	public void setTh108(String th108) {
		this.th108 = th108;
	}

	@Column(name = "TH109")
	public String getTh109() {
		return this.th109;
	}

	public void setTh109(String th109) {
		this.th109 = th109;
	}

	@Column(name = "TH110")
	public String getTh110() {
		return this.th110;
	}

	public void setTh110(String th110) {
		this.th110 = th110;
	}

	@Column(name = "TH111")
	public String getTh111() {
		return this.th111;
	}

	public void setTh111(String th111) {
		this.th111 = th111;
	}

	@Column(name = "TH112")
	public String getTh112() {
		return this.th112;
	}

	public void setTh112(String th112) {
		this.th112 = th112;
	}

	@Column(name = "TH113")
	public String getTh113() {
		return this.th113;
	}

	public void setTh113(String th113) {
		this.th113 = th113;
	}

	@Column(name = "DONGLOI", precision = 22, scale = 0)
	public BigDecimal getDongloi() {
		return this.dongloi;
	}

	public void setDongloi(BigDecimal dongloi) {
		this.dongloi = dongloi;
	}

	@Column(name = "DONGLOITCTD", precision = 22, scale = 0)
	public BigDecimal getDongloitctd() {
		return this.dongloitctd;
	}

	public void setDongloitctd(BigDecimal dongloitctd) {
		this.dongloitctd = dongloitctd;
	}

}
