package entity;

// Generated Apr 10, 2020 2:07:06 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RpDetailK101 generated by hbm2java
 */
@Entity
@Table(name = "RP_DETAIL_K101", schema = "CIC")
public class RpDetailK101 implements java.io.Serializable {

	private String id;
	private String reportId;
	private Date createdDate;
	private String createdBy;
	private Date modifiedDate;
	private String modifiedBy;
	private Boolean status;
	private String errorCode;
	private String tc002;
	private String tc003;
	private String tc004;
	private String tc005;
	private String tc006;
	private String tc007;
	private String tc0081;
	private String tc0082;
	private String tc0083;
	private String tc0084;
	private String tc009;
	private String tc010;
	private String tc011;
	private String tc012;
	private String tc013;
	private String tc014;
	private String tc015;
	private String tc016;
	private String tc0171;
	private String tc0172;
	private String tc018;
	private String tc019;
	private String tc020;
	private String tc021;
	private String tc022;
	private String tc023;
	private String tc024;
	private String macn;
	private String tencn;
	private String ngaybaocao;
	private BigDecimal dongloi;
	private BigDecimal dongloitctd;

	public RpDetailK101() {
	}

	public RpDetailK101(String id, String reportId) {
		this.id = id;
		this.reportId = reportId;
	}

	public RpDetailK101(String id, String reportId, Date createdDate, String createdBy, Date modifiedDate,
			String modifiedBy, Boolean status, String errorCode, String tc002, String tc003, String tc004,
			String tc005, String tc006, String tc007, String tc0081, String tc0082, String tc0083, String tc0084,
			String tc009, String tc010, String tc011, String tc012, String tc013, String tc014, String tc015,
			String tc016, String tc0171, String tc0172, String tc018, String tc019, String tc020, String tc021,
			String tc022, String tc023, String tc024, String macn, String tencn, String ngaybaocao, BigDecimal dongloi,
			BigDecimal dongloitctd) {
		this.id = id;
		this.reportId = reportId;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
		this.status = status;
		this.errorCode = errorCode;
		this.tc002 = tc002;
		this.tc003 = tc003;
		this.tc004 = tc004;
		this.tc005 = tc005;
		this.tc006 = tc006;
		this.tc007 = tc007;
		this.tc0081 = tc0081;
		this.tc0082 = tc0082;
		this.tc0083 = tc0083;
		this.tc0084 = tc0084;
		this.tc009 = tc009;
		this.tc010 = tc010;
		this.tc011 = tc011;
		this.tc012 = tc012;
		this.tc013 = tc013;
		this.tc014 = tc014;
		this.tc015 = tc015;
		this.tc016 = tc016;
		this.tc0171 = tc0171;
		this.tc0172 = tc0172;
		this.tc018 = tc018;
		this.tc019 = tc019;
		this.tc020 = tc020;
		this.tc021 = tc021;
		this.tc022 = tc022;
		this.tc023 = tc023;
		this.tc024 = tc024;
		this.macn = macn;
		this.tencn = tencn;
		this.ngaybaocao = ngaybaocao;
		this.dongloi = dongloi;
		this.dongloitctd = dongloitctd;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 40)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "REPORT_ID", nullable = false, length = 40)
	public String getReportId() {
		return this.reportId;
	}

	public void setReportId(String reportId) {
		this.reportId = reportId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", length = 40)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", length = 7)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "MODIFIED_BY", length = 40)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "STATUS", precision = 1, scale = 0)
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "ERROR_CODE", length = 1000)
	public String getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "TC002")
	public String getTc002() {
		return this.tc002;
	}

	public void setTc002(String tc002) {
		this.tc002 = tc002;
	}

	@Column(name = "TC003")
	public String getTc003() {
		return this.tc003;
	}

	public void setTc003(String tc003) {
		this.tc003 = tc003;
	}

	@Column(name = "TC004")
	public String getTc004() {
		return this.tc004;
	}

	public void setTc004(String tc004) {
		this.tc004 = tc004;
	}

	@Column(name = "TC005")
	public String getTc005() {
		return this.tc005;
	}

	public void setTc005(String tc005) {
		this.tc005 = tc005;
	}

	@Column(name = "TC006")
	public String getTc006() {
		return this.tc006;
	}

	public void setTc006(String tc006) {
		this.tc006 = tc006;
	}

	@Column(name = "TC007")
	public String getTc007() {
		return this.tc007;
	}

	public void setTc007(String tc007) {
		this.tc007 = tc007;
	}

	@Column(name = "TC0081")
	public String getTc0081() {
		return this.tc0081;
	}

	public void setTc0081(String tc0081) {
		this.tc0081 = tc0081;
	}

	@Column(name = "TC0082")
	public String getTc0082() {
		return this.tc0082;
	}

	public void setTc0082(String tc0082) {
		this.tc0082 = tc0082;
	}

	@Column(name = "TC0083")
	public String getTc0083() {
		return this.tc0083;
	}

	public void setTc0083(String tc0083) {
		this.tc0083 = tc0083;
	}

	@Column(name = "TC0084")
	public String getTc0084() {
		return this.tc0084;
	}

	public void setTc0084(String tc0084) {
		this.tc0084 = tc0084;
	}

	@Column(name = "TC009")
	public String getTc009() {
		return this.tc009;
	}

	public void setTc009(String tc009) {
		this.tc009 = tc009;
	}

	@Column(name = "TC010")
	public String getTc010() {
		return this.tc010;
	}

	public void setTc010(String tc010) {
		this.tc010 = tc010;
	}

	@Column(name = "TC011")
	public String getTc011() {
		return this.tc011;
	}

	public void setTc011(String tc011) {
		this.tc011 = tc011;
	}

	@Column(name = "TC012")
	public String getTc012() {
		return this.tc012;
	}

	public void setTc012(String tc012) {
		this.tc012 = tc012;
	}

	@Column(name = "TC013")
	public String getTc013() {
		return this.tc013;
	}

	public void setTc013(String tc013) {
		this.tc013 = tc013;
	}

	@Column(name = "TC014")
	public String getTc014() {
		return this.tc014;
	}

	public void setTc014(String tc014) {
		this.tc014 = tc014;
	}

	@Column(name = "TC015")
	public String getTc015() {
		return this.tc015;
	}

	public void setTc015(String tc015) {
		this.tc015 = tc015;
	}

	@Column(name = "TC016")
	public String getTc016() {
		return this.tc016;
	}

	public void setTc016(String tc016) {
		this.tc016 = tc016;
	}

	@Column(name = "TC0171")
	public String getTc0171() {
		return this.tc0171;
	}

	public void setTc0171(String tc0171) {
		this.tc0171 = tc0171;
	}

	@Column(name = "TC0172")
	public String getTc0172() {
		return this.tc0172;
	}

	public void setTc0172(String tc0172) {
		this.tc0172 = tc0172;
	}

	@Column(name = "TC018")
	public String getTc018() {
		return this.tc018;
	}

	public void setTc018(String tc018) {
		this.tc018 = tc018;
	}

	@Column(name = "TC019")
	public String getTc019() {
		return this.tc019;
	}

	public void setTc019(String tc019) {
		this.tc019 = tc019;
	}

	@Column(name = "TC020")
	public String getTc020() {
		return this.tc020;
	}

	public void setTc020(String tc020) {
		this.tc020 = tc020;
	}

	@Column(name = "TC021")
	public String getTc021() {
		return this.tc021;
	}

	public void setTc021(String tc021) {
		this.tc021 = tc021;
	}

	@Column(name = "TC022", length = 260)
	public String getTc022() {
		return this.tc022;
	}

	public void setTc022(String tc022) {
		this.tc022 = tc022;
	}

	@Column(name = "TC023")
	public String getTc023() {
		return this.tc023;
	}

	public void setTc023(String tc023) {
		this.tc023 = tc023;
	}

	@Column(name = "TC024")
	public String getTc024() {
		return this.tc024;
	}

	public void setTc024(String tc024) {
		this.tc024 = tc024;
	}

	@Column(name = "MACN")
	public String getMacn() {
		return this.macn;
	}

	public void setMacn(String macn) {
		this.macn = macn;
	}

	@Column(name = "TENCN")
	public String getTencn() {
		return this.tencn;
	}

	public void setTencn(String tencn) {
		this.tencn = tencn;
	}

	@Column(name = "NGAYBAOCAO")
	public String getNgaybaocao() {
		return this.ngaybaocao;
	}

	public void setNgaybaocao(String ngaybaocao) {
		this.ngaybaocao = ngaybaocao;
	}

	@Column(name = "DONGLOI", precision = 22, scale = 0)
	public BigDecimal getDongloi() {
		return this.dongloi;
	}

	public void setDongloi(BigDecimal dongloi) {
		this.dongloi = dongloi;
	}

	@Column(name = "DONGLOITCTD", precision = 22, scale = 0)
	public BigDecimal getDongloitctd() {
		return this.dongloitctd;
	}

	public void setDongloitctd(BigDecimal dongloitctd) {
		this.dongloitctd = dongloitctd;
	}

}
