package entity;

// Generated Apr 10, 2020 2:07:06 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RpDetailK40x generated by hbm2java
 */
@Entity
@Table(name = "RP_DETAIL_K40X", schema = "CIC")
public class RpDetailK40x implements java.io.Serializable {

	private String id;
	private String reportId;
	private Date createdDate;
	private String createdBy;
	private Date modifiedDate;
	private String modifiedBy;
	private Boolean status;
	private String errorCode;
	private String macn;
	private String tencn;
	private String ngaybaocao;
	private String ts002;
	private String ts003;
	private String ts004;
	private String ts005;
	private String ts006;
	private String ts007;
	private String ts008;
	private String ts009;
	private String ts010;
	private String ts011;
	private String ts012;
	private String ts013;
	private String ts014;
	private String ts015;
	private String ts016;
	private BigDecimal dongloi;
	private Clob ts017;
	private BigDecimal dongloitctd;

	public RpDetailK40x() {
	}

	public RpDetailK40x(String id, String reportId) {
		this.id = id;
		this.reportId = reportId;
	}

	public RpDetailK40x(String id, String reportId, Date createdDate, String createdBy, Date modifiedDate,
			String modifiedBy, Boolean status, String errorCode, String macn, String tencn, String ngaybaocao,
			String ts002, String ts003, String ts004, String ts005, String ts006, String ts007, String ts008,
			String ts009, String ts010, String ts011, String ts012, String ts013, String ts014, String ts015,
			String ts016, BigDecimal dongloi, Clob ts017, BigDecimal dongloitctd) {
		this.id = id;
		this.reportId = reportId;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
		this.status = status;
		this.errorCode = errorCode;
		this.macn = macn;
		this.tencn = tencn;
		this.ngaybaocao = ngaybaocao;
		this.ts002 = ts002;
		this.ts003 = ts003;
		this.ts004 = ts004;
		this.ts005 = ts005;
		this.ts006 = ts006;
		this.ts007 = ts007;
		this.ts008 = ts008;
		this.ts009 = ts009;
		this.ts010 = ts010;
		this.ts011 = ts011;
		this.ts012 = ts012;
		this.ts013 = ts013;
		this.ts014 = ts014;
		this.ts015 = ts015;
		this.ts016 = ts016;
		this.dongloi = dongloi;
		this.ts017 = ts017;
		this.dongloitctd = dongloitctd;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 40)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "REPORT_ID", nullable = false, length = 40)
	public String getReportId() {
		return this.reportId;
	}

	public void setReportId(String reportId) {
		this.reportId = reportId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", length = 40)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", length = 7)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "MODIFIED_BY", length = 40)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "STATUS", precision = 1, scale = 0)
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "ERROR_CODE", length = 1000)
	public String getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "MACN")
	public String getMacn() {
		return this.macn;
	}

	public void setMacn(String macn) {
		this.macn = macn;
	}

	@Column(name = "TENCN")
	public String getTencn() {
		return this.tencn;
	}

	public void setTencn(String tencn) {
		this.tencn = tencn;
	}

	@Column(name = "NGAYBAOCAO")
	public String getNgaybaocao() {
		return this.ngaybaocao;
	}

	public void setNgaybaocao(String ngaybaocao) {
		this.ngaybaocao = ngaybaocao;
	}

	@Column(name = "TS002")
	public String getTs002() {
		return this.ts002;
	}

	public void setTs002(String ts002) {
		this.ts002 = ts002;
	}

	@Column(name = "TS003")
	public String getTs003() {
		return this.ts003;
	}

	public void setTs003(String ts003) {
		this.ts003 = ts003;
	}

	@Column(name = "TS004")
	public String getTs004() {
		return this.ts004;
	}

	public void setTs004(String ts004) {
		this.ts004 = ts004;
	}

	@Column(name = "TS005")
	public String getTs005() {
		return this.ts005;
	}

	public void setTs005(String ts005) {
		this.ts005 = ts005;
	}

	@Column(name = "TS006")
	public String getTs006() {
		return this.ts006;
	}

	public void setTs006(String ts006) {
		this.ts006 = ts006;
	}

	@Column(name = "TS007")
	public String getTs007() {
		return this.ts007;
	}

	public void setTs007(String ts007) {
		this.ts007 = ts007;
	}

	@Column(name = "TS008")
	public String getTs008() {
		return this.ts008;
	}

	public void setTs008(String ts008) {
		this.ts008 = ts008;
	}

	@Column(name = "TS009")
	public String getTs009() {
		return this.ts009;
	}

	public void setTs009(String ts009) {
		this.ts009 = ts009;
	}

	@Column(name = "TS010")
	public String getTs010() {
		return this.ts010;
	}

	public void setTs010(String ts010) {
		this.ts010 = ts010;
	}

	@Column(name = "TS011")
	public String getTs011() {
		return this.ts011;
	}

	public void setTs011(String ts011) {
		this.ts011 = ts011;
	}

	@Column(name = "TS012")
	public String getTs012() {
		return this.ts012;
	}

	public void setTs012(String ts012) {
		this.ts012 = ts012;
	}

	@Column(name = "TS013")
	public String getTs013() {
		return this.ts013;
	}

	public void setTs013(String ts013) {
		this.ts013 = ts013;
	}

	@Column(name = "TS014")
	public String getTs014() {
		return this.ts014;
	}

	public void setTs014(String ts014) {
		this.ts014 = ts014;
	}

	@Column(name = "TS015")
	public String getTs015() {
		return this.ts015;
	}

	public void setTs015(String ts015) {
		this.ts015 = ts015;
	}

	@Column(name = "TS016")
	public String getTs016() {
		return this.ts016;
	}

	public void setTs016(String ts016) {
		this.ts016 = ts016;
	}

	@Column(name = "DONGLOI", precision = 22, scale = 0)
	public BigDecimal getDongloi() {
		return this.dongloi;
	}

	public void setDongloi(BigDecimal dongloi) {
		this.dongloi = dongloi;
	}

	@Column(name = "TS017")
	public Clob getTs017() {
		return this.ts017;
	}

	public void setTs017(Clob ts017) {
		this.ts017 = ts017;
	}

	@Column(name = "DONGLOITCTD", precision = 22, scale = 0)
	public BigDecimal getDongloitctd() {
		return this.dongloitctd;
	}

	public void setDongloitctd(BigDecimal dongloitctd) {
		this.dongloitctd = dongloitctd;
	}

}
