package entity;

// Generated Apr 10, 2020 2:07:06 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RpDetailK102 generated by hbm2java
 */
@Entity
@Table(name = "RP_DETAIL_K102", schema = "CIC")
public class RpDetailK102 implements java.io.Serializable {

	private String id;
	private RpSum rpSum;
	private String macn;
	private String tencn;
	private String ngaybaocao;
	private String cn002;
	private String cn003;
	private String cn006;
	private String cn007;
	private String cn0101;
	private String cn0102;
	private String cn012;
	private String cn0131;
	private String cn0132;
	private String cn004;
	private String cn005;
	private String cn008;
	private String cn009;
	private String cn014;
	private String cn015;
	private String cn011101;
	private String cn011102;
	private String cn011103;
	private String cn011104;
	private String cn011105;
	private String cn011106;
	private Boolean status;
	private String errorCode;
	private Date createdDate;
	private String createdBy;
	private Date modifiedDate;
	private String modifiedBy;
	private String cn011201;
	private String cn011202;
	private String cn011203;
	private String cn011204;
	private String cn011205;
	private String cn011206;
	private String cn011;
	private BigDecimal dongloi;
	private BigDecimal dongloitctd;

	public RpDetailK102() {
	}

	public RpDetailK102(String id, RpSum rpSum, Date createdDate, String createdBy, Date modifiedDate, String modifiedBy) {
		this.id = id;
		this.rpSum = rpSum;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
	}

	public RpDetailK102(String id, RpSum rpSum, String macn, String tencn, String ngaybaocao, String cn002,
			String cn003, String cn006, String cn007, String cn0101, String cn0102, String cn012, String cn0131,
			String cn0132, String cn004, String cn005, String cn008, String cn009, String cn014, String cn015,
			String cn011101, String cn011102, String cn011103, String cn011104, String cn011105, String cn011106,
			Boolean status, String errorCode, Date createdDate, String createdBy, Date modifiedDate, String modifiedBy,
			String cn011201, String cn011202, String cn011203, String cn011204, String cn011205, String cn011206,
			String cn011, BigDecimal dongloi, BigDecimal dongloitctd) {
		this.id = id;
		this.rpSum = rpSum;
		this.macn = macn;
		this.tencn = tencn;
		this.ngaybaocao = ngaybaocao;
		this.cn002 = cn002;
		this.cn003 = cn003;
		this.cn006 = cn006;
		this.cn007 = cn007;
		this.cn0101 = cn0101;
		this.cn0102 = cn0102;
		this.cn012 = cn012;
		this.cn0131 = cn0131;
		this.cn0132 = cn0132;
		this.cn004 = cn004;
		this.cn005 = cn005;
		this.cn008 = cn008;
		this.cn009 = cn009;
		this.cn014 = cn014;
		this.cn015 = cn015;
		this.cn011101 = cn011101;
		this.cn011102 = cn011102;
		this.cn011103 = cn011103;
		this.cn011104 = cn011104;
		this.cn011105 = cn011105;
		this.cn011106 = cn011106;
		this.status = status;
		this.errorCode = errorCode;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
		this.cn011201 = cn011201;
		this.cn011202 = cn011202;
		this.cn011203 = cn011203;
		this.cn011204 = cn011204;
		this.cn011205 = cn011205;
		this.cn011206 = cn011206;
		this.cn011 = cn011;
		this.dongloi = dongloi;
		this.dongloitctd = dongloitctd;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 40)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REPORT_ID", nullable = false)
	public RpSum getRpSum() {
		return this.rpSum;
	}

	public void setRpSum(RpSum rpSum) {
		this.rpSum = rpSum;
	}

	@Column(name = "MACN")
	public String getMacn() {
		return this.macn;
	}

	public void setMacn(String macn) {
		this.macn = macn;
	}

	@Column(name = "TENCN")
	public String getTencn() {
		return this.tencn;
	}

	public void setTencn(String tencn) {
		this.tencn = tencn;
	}

	@Column(name = "NGAYBAOCAO")
	public String getNgaybaocao() {
		return this.ngaybaocao;
	}

	public void setNgaybaocao(String ngaybaocao) {
		this.ngaybaocao = ngaybaocao;
	}

	@Column(name = "CN002")
	public String getCn002() {
		return this.cn002;
	}

	public void setCn002(String cn002) {
		this.cn002 = cn002;
	}

	@Column(name = "CN003")
	public String getCn003() {
		return this.cn003;
	}

	public void setCn003(String cn003) {
		this.cn003 = cn003;
	}

	@Column(name = "CN006")
	public String getCn006() {
		return this.cn006;
	}

	public void setCn006(String cn006) {
		this.cn006 = cn006;
	}

	@Column(name = "CN007")
	public String getCn007() {
		return this.cn007;
	}

	public void setCn007(String cn007) {
		this.cn007 = cn007;
	}

	@Column(name = "CN0101")
	public String getCn0101() {
		return this.cn0101;
	}

	public void setCn0101(String cn0101) {
		this.cn0101 = cn0101;
	}

	@Column(name = "CN0102")
	public String getCn0102() {
		return this.cn0102;
	}

	public void setCn0102(String cn0102) {
		this.cn0102 = cn0102;
	}

	@Column(name = "CN012")
	public String getCn012() {
		return this.cn012;
	}

	public void setCn012(String cn012) {
		this.cn012 = cn012;
	}

	@Column(name = "CN0131")
	public String getCn0131() {
		return this.cn0131;
	}

	public void setCn0131(String cn0131) {
		this.cn0131 = cn0131;
	}

	@Column(name = "CN0132")
	public String getCn0132() {
		return this.cn0132;
	}

	public void setCn0132(String cn0132) {
		this.cn0132 = cn0132;
	}

	@Column(name = "CN004")
	public String getCn004() {
		return this.cn004;
	}

	public void setCn004(String cn004) {
		this.cn004 = cn004;
	}

	@Column(name = "CN005")
	public String getCn005() {
		return this.cn005;
	}

	public void setCn005(String cn005) {
		this.cn005 = cn005;
	}

	@Column(name = "CN008")
	public String getCn008() {
		return this.cn008;
	}

	public void setCn008(String cn008) {
		this.cn008 = cn008;
	}

	@Column(name = "CN009")
	public String getCn009() {
		return this.cn009;
	}

	public void setCn009(String cn009) {
		this.cn009 = cn009;
	}

	@Column(name = "CN014")
	public String getCn014() {
		return this.cn014;
	}

	public void setCn014(String cn014) {
		this.cn014 = cn014;
	}

	@Column(name = "CN015")
	public String getCn015() {
		return this.cn015;
	}

	public void setCn015(String cn015) {
		this.cn015 = cn015;
	}

	@Column(name = "CN011101")
	public String getCn011101() {
		return this.cn011101;
	}

	public void setCn011101(String cn011101) {
		this.cn011101 = cn011101;
	}

	@Column(name = "CN011102")
	public String getCn011102() {
		return this.cn011102;
	}

	public void setCn011102(String cn011102) {
		this.cn011102 = cn011102;
	}

	@Column(name = "CN011103")
	public String getCn011103() {
		return this.cn011103;
	}

	public void setCn011103(String cn011103) {
		this.cn011103 = cn011103;
	}

	@Column(name = "CN011104")
	public String getCn011104() {
		return this.cn011104;
	}

	public void setCn011104(String cn011104) {
		this.cn011104 = cn011104;
	}

	@Column(name = "CN011105")
	public String getCn011105() {
		return this.cn011105;
	}

	public void setCn011105(String cn011105) {
		this.cn011105 = cn011105;
	}

	@Column(name = "CN011106")
	public String getCn011106() {
		return this.cn011106;
	}

	public void setCn011106(String cn011106) {
		this.cn011106 = cn011106;
	}

	@Column(name = "STATUS", precision = 1, scale = 0)
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "ERROR_CODE", length = 1000)
	public String getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", nullable = false, length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", nullable = false, length = 7)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "MODIFIED_BY", nullable = false)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "CN011201")
	public String getCn011201() {
		return this.cn011201;
	}

	public void setCn011201(String cn011201) {
		this.cn011201 = cn011201;
	}

	@Column(name = "CN011202")
	public String getCn011202() {
		return this.cn011202;
	}

	public void setCn011202(String cn011202) {
		this.cn011202 = cn011202;
	}

	@Column(name = "CN011203")
	public String getCn011203() {
		return this.cn011203;
	}

	public void setCn011203(String cn011203) {
		this.cn011203 = cn011203;
	}

	@Column(name = "CN011204")
	public String getCn011204() {
		return this.cn011204;
	}

	public void setCn011204(String cn011204) {
		this.cn011204 = cn011204;
	}

	@Column(name = "CN011205")
	public String getCn011205() {
		return this.cn011205;
	}

	public void setCn011205(String cn011205) {
		this.cn011205 = cn011205;
	}

	@Column(name = "CN011206")
	public String getCn011206() {
		return this.cn011206;
	}

	public void setCn011206(String cn011206) {
		this.cn011206 = cn011206;
	}

	@Column(name = "CN011")
	public String getCn011() {
		return this.cn011;
	}

	public void setCn011(String cn011) {
		this.cn011 = cn011;
	}

	@Column(name = "DONGLOI", precision = 22, scale = 0)
	public BigDecimal getDongloi() {
		return this.dongloi;
	}

	public void setDongloi(BigDecimal dongloi) {
		this.dongloi = dongloi;
	}

	@Column(name = "DONGLOITCTD", precision = 22, scale = 0)
	public BigDecimal getDongloitctd() {
		return this.dongloitctd;
	}

	public void setDongloitctd(BigDecimal dongloitctd) {
		this.dongloitctd = dongloitctd;
	}

}
