package entity;

// Generated Apr 10, 2020 2:07:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RpDetailK113 generated by hbm2java
 */
@Entity
@Table(name = "RP_DETAIL_K113", schema = "CIC")
public class RpDetailK113 implements java.io.Serializable {

	private String id;
	private RpSum rpSum;
	private String macn;
	private String tencn;
	private String reportDate;
	private String status;
	private String errorCode;
	private Date createdDate;
	private String createdBy;
	private Date modifiedDate;
	private String modifiedBy;
	private String kb001;
	private String kb002;
	private String kb003;
	private String th001;
	private String th002;
	private String th003;
	private String th004;
	private String ts004;
	private String ts005;
	private String ts006;
	private String ts007;
	private String th005;
	private String th006;
	private String th007;
	private String th008;
	private String th0091;
	private String th0092;
	private String th011;
	private String th012;
	private String th013;
	private String th0101;
	private String th0102;
	private String th014;
	private String th015;
	private String ts008;
	private String ts009;
	private String ts010;
	private String ts011;
	private String ts012;
	private String ts013;
	private String ts014;
	private String ts015;
	private String ts016;
	private String ts017;
	private String th0201;
	private String th0202;
	private String th0301;
	private String th0302;
	private String th0401;
	private String th0402;
	private String th0501;
	private String th0502;
	private String th0601;
	private String th0602;

	public RpDetailK113() {
	}

	public RpDetailK113(String id, RpSum rpSum) {
		this.id = id;
		this.rpSum = rpSum;
	}

	public RpDetailK113(String id, RpSum rpSum, String macn, String tencn, String reportDate, String status,
			String errorCode, Date createdDate, String createdBy, Date modifiedDate, String modifiedBy, String kb001,
			String kb002, String kb003, String th001, String th002, String th003, String th004, String ts004,
			String ts005, String ts006, String ts007, String th005, String th006, String th007, String th008,
			String th0091, String th0092, String th011, String th012, String th013, String th0101, String th0102,
			String th014, String th015, String ts008, String ts009, String ts010, String ts011, String ts012,
			String ts013, String ts014, String ts015, String ts016, String ts017, String th0201, String th0202,
			String th0301, String th0302, String th0401, String th0402, String th0501, String th0502, String th0601,
			String th0602) {
		this.id = id;
		this.rpSum = rpSum;
		this.macn = macn;
		this.tencn = tencn;
		this.reportDate = reportDate;
		this.status = status;
		this.errorCode = errorCode;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
		this.kb001 = kb001;
		this.kb002 = kb002;
		this.kb003 = kb003;
		this.th001 = th001;
		this.th002 = th002;
		this.th003 = th003;
		this.th004 = th004;
		this.ts004 = ts004;
		this.ts005 = ts005;
		this.ts006 = ts006;
		this.ts007 = ts007;
		this.th005 = th005;
		this.th006 = th006;
		this.th007 = th007;
		this.th008 = th008;
		this.th0091 = th0091;
		this.th0092 = th0092;
		this.th011 = th011;
		this.th012 = th012;
		this.th013 = th013;
		this.th0101 = th0101;
		this.th0102 = th0102;
		this.th014 = th014;
		this.th015 = th015;
		this.ts008 = ts008;
		this.ts009 = ts009;
		this.ts010 = ts010;
		this.ts011 = ts011;
		this.ts012 = ts012;
		this.ts013 = ts013;
		this.ts014 = ts014;
		this.ts015 = ts015;
		this.ts016 = ts016;
		this.ts017 = ts017;
		this.th0201 = th0201;
		this.th0202 = th0202;
		this.th0301 = th0301;
		this.th0302 = th0302;
		this.th0401 = th0401;
		this.th0402 = th0402;
		this.th0501 = th0501;
		this.th0502 = th0502;
		this.th0601 = th0601;
		this.th0602 = th0602;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 40)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REPORT_ID", nullable = false)
	public RpSum getRpSum() {
		return this.rpSum;
	}

	public void setRpSum(RpSum rpSum) {
		this.rpSum = rpSum;
	}

	@Column(name = "MACN")
	public String getMacn() {
		return this.macn;
	}

	public void setMacn(String macn) {
		this.macn = macn;
	}

	@Column(name = "TENCN", length = 510)
	public String getTencn() {
		return this.tencn;
	}

	public void setTencn(String tencn) {
		this.tencn = tencn;
	}

	@Column(name = "NGAYBAOCAO")
	public String getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(String reportDate) {
		this.reportDate = reportDate;
	}

	@Column(name = "STATUS", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "ERROR_CODE", length = 1000)
	public String getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", length = 7)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "MODIFIED_BY")
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "KB001")
	public String getKb001() {
		return this.kb001;
	}

	public void setKb001(String kb001) {
		this.kb001 = kb001;
	}

	@Column(name = "KB002")
	public String getKb002() {
		return this.kb002;
	}

	public void setKb002(String kb002) {
		this.kb002 = kb002;
	}

	@Column(name = "KB003")
	public String getKb003() {
		return this.kb003;
	}

	public void setKb003(String kb003) {
		this.kb003 = kb003;
	}

	@Column(name = "TH001")
	public String getTh001() {
		return this.th001;
	}

	public void setTh001(String th001) {
		this.th001 = th001;
	}

	@Column(name = "TH002")
	public String getTh002() {
		return this.th002;
	}

	public void setTh002(String th002) {
		this.th002 = th002;
	}

	@Column(name = "TH003")
	public String getTh003() {
		return this.th003;
	}

	public void setTh003(String th003) {
		this.th003 = th003;
	}

	@Column(name = "TH004")
	public String getTh004() {
		return this.th004;
	}

	public void setTh004(String th004) {
		this.th004 = th004;
	}

	@Column(name = "TS004")
	public String getTs004() {
		return this.ts004;
	}

	public void setTs004(String ts004) {
		this.ts004 = ts004;
	}

	@Column(name = "TS005")
	public String getTs005() {
		return this.ts005;
	}

	public void setTs005(String ts005) {
		this.ts005 = ts005;
	}

	@Column(name = "TS006")
	public String getTs006() {
		return this.ts006;
	}

	public void setTs006(String ts006) {
		this.ts006 = ts006;
	}

	@Column(name = "TS007")
	public String getTs007() {
		return this.ts007;
	}

	public void setTs007(String ts007) {
		this.ts007 = ts007;
	}

	@Column(name = "TH005")
	public String getTh005() {
		return this.th005;
	}

	public void setTh005(String th005) {
		this.th005 = th005;
	}

	@Column(name = "TH006")
	public String getTh006() {
		return this.th006;
	}

	public void setTh006(String th006) {
		this.th006 = th006;
	}

	@Column(name = "TH007")
	public String getTh007() {
		return this.th007;
	}

	public void setTh007(String th007) {
		this.th007 = th007;
	}

	@Column(name = "TH008")
	public String getTh008() {
		return this.th008;
	}

	public void setTh008(String th008) {
		this.th008 = th008;
	}

	@Column(name = "TH0091")
	public String getTh0091() {
		return this.th0091;
	}

	public void setTh0091(String th0091) {
		this.th0091 = th0091;
	}

	@Column(name = "TH0092")
	public String getTh0092() {
		return this.th0092;
	}

	public void setTh0092(String th0092) {
		this.th0092 = th0092;
	}

	@Column(name = "TH011")
	public String getTh011() {
		return this.th011;
	}

	public void setTh011(String th011) {
		this.th011 = th011;
	}

	@Column(name = "TH012")
	public String getTh012() {
		return this.th012;
	}

	public void setTh012(String th012) {
		this.th012 = th012;
	}

	@Column(name = "TH013")
	public String getTh013() {
		return this.th013;
	}

	public void setTh013(String th013) {
		this.th013 = th013;
	}

	@Column(name = "TH0101")
	public String getTh0101() {
		return this.th0101;
	}

	public void setTh0101(String th0101) {
		this.th0101 = th0101;
	}

	@Column(name = "TH0102")
	public String getTh0102() {
		return this.th0102;
	}

	public void setTh0102(String th0102) {
		this.th0102 = th0102;
	}

	@Column(name = "TH014")
	public String getTh014() {
		return this.th014;
	}

	public void setTh014(String th014) {
		this.th014 = th014;
	}

	@Column(name = "TH015")
	public String getTh015() {
		return this.th015;
	}

	public void setTh015(String th015) {
		this.th015 = th015;
	}

	@Column(name = "TS008")
	public String getTs008() {
		return this.ts008;
	}

	public void setTs008(String ts008) {
		this.ts008 = ts008;
	}

	@Column(name = "TS009")
	public String getTs009() {
		return this.ts009;
	}

	public void setTs009(String ts009) {
		this.ts009 = ts009;
	}

	@Column(name = "TS010")
	public String getTs010() {
		return this.ts010;
	}

	public void setTs010(String ts010) {
		this.ts010 = ts010;
	}

	@Column(name = "TS011")
	public String getTs011() {
		return this.ts011;
	}

	public void setTs011(String ts011) {
		this.ts011 = ts011;
	}

	@Column(name = "TS012")
	public String getTs012() {
		return this.ts012;
	}

	public void setTs012(String ts012) {
		this.ts012 = ts012;
	}

	@Column(name = "TS013")
	public String getTs013() {
		return this.ts013;
	}

	public void setTs013(String ts013) {
		this.ts013 = ts013;
	}

	@Column(name = "TS014")
	public String getTs014() {
		return this.ts014;
	}

	public void setTs014(String ts014) {
		this.ts014 = ts014;
	}

	@Column(name = "TS015")
	public String getTs015() {
		return this.ts015;
	}

	public void setTs015(String ts015) {
		this.ts015 = ts015;
	}

	@Column(name = "TS016")
	public String getTs016() {
		return this.ts016;
	}

	public void setTs016(String ts016) {
		this.ts016 = ts016;
	}

	@Column(name = "TS017")
	public String getTs017() {
		return this.ts017;
	}

	public void setTs017(String ts017) {
		this.ts017 = ts017;
	}

	@Column(name = "TH0201")
	public String getTh0201() {
		return this.th0201;
	}

	public void setTh0201(String th0201) {
		this.th0201 = th0201;
	}

	@Column(name = "TH0202")
	public String getTh0202() {
		return this.th0202;
	}

	public void setTh0202(String th0202) {
		this.th0202 = th0202;
	}

	@Column(name = "TH0301")
	public String getTh0301() {
		return this.th0301;
	}

	public void setTh0301(String th0301) {
		this.th0301 = th0301;
	}

	@Column(name = "TH0302")
	public String getTh0302() {
		return this.th0302;
	}

	public void setTh0302(String th0302) {
		this.th0302 = th0302;
	}

	@Column(name = "TH0401")
	public String getTh0401() {
		return this.th0401;
	}

	public void setTh0401(String th0401) {
		this.th0401 = th0401;
	}

	@Column(name = "TH0402")
	public String getTh0402() {
		return this.th0402;
	}

	public void setTh0402(String th0402) {
		this.th0402 = th0402;
	}

	@Column(name = "TH0501")
	public String getTh0501() {
		return this.th0501;
	}

	public void setTh0501(String th0501) {
		this.th0501 = th0501;
	}

	@Column(name = "TH0502")
	public String getTh0502() {
		return this.th0502;
	}

	public void setTh0502(String th0502) {
		this.th0502 = th0502;
	}

	@Column(name = "TH0601")
	public String getTh0601() {
		return this.th0601;
	}

	public void setTh0601(String th0601) {
		this.th0601 = th0601;
	}

	@Column(name = "TH0602")
	public String getTh0602() {
		return this.th0602;
	}

	public void setTh0602(String th0602) {
		this.th0602 = th0602;
	}

}
