package entity;

// Generated Apr 10, 2020 2:07:06 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RpDetailK5 generated by hbm2java
 */
@Entity
@Table(name = "RP_DETAIL_K5", schema = "CIC")
public class RpDetailK5 implements java.io.Serializable {

	private String id;
	private RpSum rpSum;
	private String macn;
	private String tencn;
	private String ngaybaocao;
	private BigDecimal dongloi;
	private String tp002;
	private String tp003;
	private String tp004;
	private String tp005;
	private String tp006;
	private String tp007;
	private String tp008;
	private String tp009;
	private String tp010;
	private String tp011;
	private String tp012;
	private String tp013;
	private Boolean status;
	private String errorCode;
	private Date createdDate;
	private String createdBy;
	private Date modifiedDate;
	private String modifiedBy;
	private BigDecimal dongloitctd;

	public RpDetailK5() {
	}

	public RpDetailK5(String id, RpSum rpSum, Date createdDate, String createdBy, Date modifiedDate, String modifiedBy) {
		this.id = id;
		this.rpSum = rpSum;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
	}

	public RpDetailK5(String id, RpSum rpSum, String macn, String tencn, String ngaybaocao, BigDecimal dongloi,
			String tp002, String tp003, String tp004, String tp005, String tp006, String tp007, String tp008,
			String tp009, String tp010, String tp011, String tp012, String tp013, Boolean status, String errorCode,
			Date createdDate, String createdBy, Date modifiedDate, String modifiedBy, BigDecimal dongloitctd) {
		this.id = id;
		this.rpSum = rpSum;
		this.macn = macn;
		this.tencn = tencn;
		this.ngaybaocao = ngaybaocao;
		this.dongloi = dongloi;
		this.tp002 = tp002;
		this.tp003 = tp003;
		this.tp004 = tp004;
		this.tp005 = tp005;
		this.tp006 = tp006;
		this.tp007 = tp007;
		this.tp008 = tp008;
		this.tp009 = tp009;
		this.tp010 = tp010;
		this.tp011 = tp011;
		this.tp012 = tp012;
		this.tp013 = tp013;
		this.status = status;
		this.errorCode = errorCode;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
		this.dongloitctd = dongloitctd;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 40)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REPORT_ID", nullable = false)
	public RpSum getRpSum() {
		return this.rpSum;
	}

	public void setRpSum(RpSum rpSum) {
		this.rpSum = rpSum;
	}

	@Column(name = "MACN")
	public String getMacn() {
		return this.macn;
	}

	public void setMacn(String macn) {
		this.macn = macn;
	}

	@Column(name = "TENCN")
	public String getTencn() {
		return this.tencn;
	}

	public void setTencn(String tencn) {
		this.tencn = tencn;
	}

	@Column(name = "NGAYBAOCAO")
	public String getNgaybaocao() {
		return this.ngaybaocao;
	}

	public void setNgaybaocao(String ngaybaocao) {
		this.ngaybaocao = ngaybaocao;
	}

	@Column(name = "DONGLOI", precision = 22, scale = 0)
	public BigDecimal getDongloi() {
		return this.dongloi;
	}

	public void setDongloi(BigDecimal dongloi) {
		this.dongloi = dongloi;
	}

	@Column(name = "TP002")
	public String getTp002() {
		return this.tp002;
	}

	public void setTp002(String tp002) {
		this.tp002 = tp002;
	}

	@Column(name = "TP003")
	public String getTp003() {
		return this.tp003;
	}

	public void setTp003(String tp003) {
		this.tp003 = tp003;
	}

	@Column(name = "TP004")
	public String getTp004() {
		return this.tp004;
	}

	public void setTp004(String tp004) {
		this.tp004 = tp004;
	}

	@Column(name = "TP005")
	public String getTp005() {
		return this.tp005;
	}

	public void setTp005(String tp005) {
		this.tp005 = tp005;
	}

	@Column(name = "TP006")
	public String getTp006() {
		return this.tp006;
	}

	public void setTp006(String tp006) {
		this.tp006 = tp006;
	}

	@Column(name = "TP007")
	public String getTp007() {
		return this.tp007;
	}

	public void setTp007(String tp007) {
		this.tp007 = tp007;
	}

	@Column(name = "TP008")
	public String getTp008() {
		return this.tp008;
	}

	public void setTp008(String tp008) {
		this.tp008 = tp008;
	}

	@Column(name = "TP009")
	public String getTp009() {
		return this.tp009;
	}

	public void setTp009(String tp009) {
		this.tp009 = tp009;
	}

	@Column(name = "TP010")
	public String getTp010() {
		return this.tp010;
	}

	public void setTp010(String tp010) {
		this.tp010 = tp010;
	}

	@Column(name = "TP011")
	public String getTp011() {
		return this.tp011;
	}

	public void setTp011(String tp011) {
		this.tp011 = tp011;
	}

	@Column(name = "TP012")
	public String getTp012() {
		return this.tp012;
	}

	public void setTp012(String tp012) {
		this.tp012 = tp012;
	}

	@Column(name = "TP013")
	public String getTp013() {
		return this.tp013;
	}

	public void setTp013(String tp013) {
		this.tp013 = tp013;
	}

	@Column(name = "STATUS", precision = 1, scale = 0)
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "ERROR_CODE", length = 1000)
	public String getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", nullable = false, length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", nullable = false, length = 7)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "MODIFIED_BY", nullable = false)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "DONGLOITCTD", precision = 22, scale = 0)
	public BigDecimal getDongloitctd() {
		return this.dongloitctd;
	}

	public void setDongloitctd(BigDecimal dongloitctd) {
		this.dongloitctd = dongloitctd;
	}

}
