package entity;

// Generated Apr 10, 2020 2:07:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RpDetailT02g2 generated by hbm2java
 */
@Entity
@Table(name = "RP_DETAIL_T02G2", schema = "CIC")
public class RpDetailT02g2 implements java.io.Serializable {

	private String id;
	private RpSum rpSum;
	private String macn;
	private String tencn;
	private String reportDate;
	private String status;
	private String errorCode;
	private Date createdDate;
	private String createdBy;
	private Date modifiedDate;
	private String modifiedBy;
	private String kb001;
	private String kb002;
	private String pl003;
	private String dna05;
	private String dnb091;
	private String dnb092;
	private String dnb0921;
	private String dna05aa;
	private String dna05bb;
	private String dna05cc;
	private String dnb092bb;
	private String dnb092cc;
	private String typeFile;
	private String dnb091bb;
	private String dna051;

	public RpDetailT02g2() {
	}

	public RpDetailT02g2(String id, RpSum rpSum) {
		this.id = id;
		this.rpSum = rpSum;
	}

	public RpDetailT02g2(String id, RpSum rpSum, String macn, String tencn, String reportDate, String status,
			String errorCode, Date createdDate, String createdBy, Date modifiedDate, String modifiedBy, String kb001,
			String kb002, String pl003, String dna05, String dnb091, String dnb092, String dnb0921, String dna05aa,
			String dna05bb, String dna05cc, String dnb092bb, String dnb092cc, String typeFile, String dnb091bb,
			String dna051) {
		this.id = id;
		this.rpSum = rpSum;
		this.macn = macn;
		this.tencn = tencn;
		this.reportDate = reportDate;
		this.status = status;
		this.errorCode = errorCode;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
		this.kb001 = kb001;
		this.kb002 = kb002;
		this.pl003 = pl003;
		this.dna05 = dna05;
		this.dnb091 = dnb091;
		this.dnb092 = dnb092;
		this.dnb0921 = dnb0921;
		this.dna05aa = dna05aa;
		this.dna05bb = dna05bb;
		this.dna05cc = dna05cc;
		this.dnb092bb = dnb092bb;
		this.dnb092cc = dnb092cc;
		this.typeFile = typeFile;
		this.dnb091bb = dnb091bb;
		this.dna051 = dna051;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 40)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REPORT_ID", nullable = false)
	public RpSum getRpSum() {
		return this.rpSum;
	}

	public void setRpSum(RpSum rpSum) {
		this.rpSum = rpSum;
	}

	@Column(name = "MACN")
	public String getMacn() {
		return this.macn;
	}

	public void setMacn(String macn) {
		this.macn = macn;
	}

	@Column(name = "TENCN", length = 510)
	public String getTencn() {
		return this.tencn;
	}

	public void setTencn(String tencn) {
		this.tencn = tencn;
	}

	@Column(name = "NGAYBAOCAO")
	public String getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(String reportDate) {
		this.reportDate = reportDate;
	}

	@Column(name = "STATUS", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "ERROR_CODE", length = 1000)
	public String getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", length = 7)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "MODIFIED_BY")
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "KB001")
	public String getKb001() {
		return this.kb001;
	}

	public void setKb001(String kb001) {
		this.kb001 = kb001;
	}

	@Column(name = "KB002")
	public String getKb002() {
		return this.kb002;
	}

	public void setKb002(String kb002) {
		this.kb002 = kb002;
	}

	@Column(name = "PL003")
	public String getPl003() {
		return this.pl003;
	}

	public void setPl003(String pl003) {
		this.pl003 = pl003;
	}

	@Column(name = "DNA05")
	public String getDna05() {
		return this.dna05;
	}

	public void setDna05(String dna05) {
		this.dna05 = dna05;
	}

	@Column(name = "DNB091")
	public String getDnb091() {
		return this.dnb091;
	}

	public void setDnb091(String dnb091) {
		this.dnb091 = dnb091;
	}

	@Column(name = "DNB092")
	public String getDnb092() {
		return this.dnb092;
	}

	public void setDnb092(String dnb092) {
		this.dnb092 = dnb092;
	}

	@Column(name = "DNB0921")
	public String getDnb0921() {
		return this.dnb0921;
	}

	public void setDnb0921(String dnb0921) {
		this.dnb0921 = dnb0921;
	}

	@Column(name = "DNA05AA")
	public String getDna05aa() {
		return this.dna05aa;
	}

	public void setDna05aa(String dna05aa) {
		this.dna05aa = dna05aa;
	}

	@Column(name = "DNA05BB")
	public String getDna05bb() {
		return this.dna05bb;
	}

	public void setDna05bb(String dna05bb) {
		this.dna05bb = dna05bb;
	}

	@Column(name = "DNA05CC")
	public String getDna05cc() {
		return this.dna05cc;
	}

	public void setDna05cc(String dna05cc) {
		this.dna05cc = dna05cc;
	}

	@Column(name = "DNB092BB")
	public String getDnb092bb() {
		return this.dnb092bb;
	}

	public void setDnb092bb(String dnb092bb) {
		this.dnb092bb = dnb092bb;
	}

	@Column(name = "DNB092CC")
	public String getDnb092cc() {
		return this.dnb092cc;
	}

	public void setDnb092cc(String dnb092cc) {
		this.dnb092cc = dnb092cc;
	}

	@Column(name = "TYPE_FILE")
	public String getTypeFile() {
		return this.typeFile;
	}

	public void setTypeFile(String typeFile) {
		this.typeFile = typeFile;
	}

	@Column(name = "DNB091BB")
	public String getDnb091bb() {
		return this.dnb091bb;
	}

	public void setDnb091bb(String dnb091bb) {
		this.dnb091bb = dnb091bb;
	}

	@Column(name = "DNA051")
	public String getDna051() {
		return this.dna051;
	}

	public void setDna051(String dna051) {
		this.dna051 = dna051;
	}

}
