package entity;

// Generated Apr 10, 2020 2:07:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RpDetailT02ds generated by hbm2java
 */
@Entity
@Table(name = "RP_DETAIL_T02DS", schema = "CIC")
public class RpDetailT02ds implements java.io.Serializable {

	private String id;
	private RpSum rpSum;
	private String macn;
	private String tencn;
	private String pl003;
	private String pl004;
	private String pl005;
	private String pl006;
	private String pl007;
	private String status;
	private String errorCode;
	private Date createdDate;
	private String createdBy;
	private Date modifiedDate;
	private String modifiedBy;
	private String reportDate;
	private String kb001;
	private String kb002;

	public RpDetailT02ds() {
	}

	public RpDetailT02ds(String id, RpSum rpSum) {
		this.id = id;
		this.rpSum = rpSum;
	}

	public RpDetailT02ds(String id, RpSum rpSum, String macn, String tencn, String pl003, String pl004, String pl005,
			String pl006, String pl007, String status, String errorCode, Date createdDate, String createdBy,
			Date modifiedDate, String modifiedBy, String reportDate, String kb001, String kb002) {
		this.id = id;
		this.rpSum = rpSum;
		this.macn = macn;
		this.tencn = tencn;
		this.pl003 = pl003;
		this.pl004 = pl004;
		this.pl005 = pl005;
		this.pl006 = pl006;
		this.pl007 = pl007;
		this.status = status;
		this.errorCode = errorCode;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
		this.reportDate = reportDate;
		this.kb001 = kb001;
		this.kb002 = kb002;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 40)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REPORT_ID", nullable = false)
	public RpSum getRpSum() {
		return this.rpSum;
	}

	public void setRpSum(RpSum rpSum) {
		this.rpSum = rpSum;
	}

	@Column(name = "MACN")
	public String getMacn() {
		return this.macn;
	}

	public void setMacn(String macn) {
		this.macn = macn;
	}

	@Column(name = "TENCN", length = 510)
	public String getTencn() {
		return this.tencn;
	}

	public void setTencn(String tencn) {
		this.tencn = tencn;
	}

	@Column(name = "PL003")
	public String getPl003() {
		return this.pl003;
	}

	public void setPl003(String pl003) {
		this.pl003 = pl003;
	}

	@Column(name = "PL004")
	public String getPl004() {
		return this.pl004;
	}

	public void setPl004(String pl004) {
		this.pl004 = pl004;
	}

	@Column(name = "PL005")
	public String getPl005() {
		return this.pl005;
	}

	public void setPl005(String pl005) {
		this.pl005 = pl005;
	}

	@Column(name = "PL006")
	public String getPl006() {
		return this.pl006;
	}

	public void setPl006(String pl006) {
		this.pl006 = pl006;
	}

	@Column(name = "PL007")
	public String getPl007() {
		return this.pl007;
	}

	public void setPl007(String pl007) {
		this.pl007 = pl007;
	}

	@Column(name = "STATUS", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "ERROR_CODE", length = 1000)
	public String getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", length = 7)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "MODIFIED_BY")
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "NGAYBAOCAO")
	public String getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(String reportDate) {
		this.reportDate = reportDate;
	}

	@Column(name = "KB001")
	public String getKb001() {
		return this.kb001;
	}

	public void setKb001(String kb001) {
		this.kb001 = kb001;
	}

	@Column(name = "KB002")
	public String getKb002() {
		return this.kb002;
	}

	public void setKb002(String kb002) {
		this.kb002 = kb002;
	}

}
