package entity;

// Generated Apr 10, 2020 2:07:06 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RpSumBranch generated by hbm2java
 */
@Entity
@Table(name = "RP_SUM_BRANCH", schema = "CIC")
public class RpSumBranch implements java.io.Serializable {

	private String id;
	private RpSum rpSum;
	private String branchCode;
	private String branchName;
	private String reportDate;
	private BigDecimal beginRow;
	private Set<RpSumBranchErr> rpSumBranchErrs = new HashSet<RpSumBranchErr>(0);
	private Set<RpValidateDetail> rpValidateDetails = new HashSet<RpValidateDetail>(0);

	public RpSumBranch() {
	}

	public RpSumBranch(String id, RpSum rpSum) {
		this.id = id;
		this.rpSum = rpSum;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 40)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RP_SUM_ID", nullable = false)
	public RpSum getRpSum() {
		return this.rpSum;
	}

	public void setRpSum(RpSum rpSum) {
		this.rpSum = rpSum;
	}

	@Column(name = "BRANCH_CODE", length = 40)
	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	@Column(name = "BRANCH_NAME", length = 400)
	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	@Column(name = "REPORT_DATE", length = 20)
	public String getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(String reportDate) {
		this.reportDate = reportDate;
	}

	@Column(name = "BEGIN_ROW", precision = 20, scale = 0)
	public BigDecimal getBeginRow() {
		return this.beginRow;
	}

	public void setBeginRow(BigDecimal beginRow) {
		this.beginRow = beginRow;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rpSumBranch", cascade = CascadeType.ALL)
	public Set<RpSumBranchErr> getRpSumBranchErrs() {
		return this.rpSumBranchErrs;
	}

	public void setRpSumBranchErrs(Set<RpSumBranchErr> rpSumBranchErrs) {
		this.rpSumBranchErrs = rpSumBranchErrs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rpSumBranch", cascade = CascadeType.ALL)
	public Set<RpValidateDetail> getRpValidateDetails() {
		return this.rpValidateDetails;
	}

	public void setRpValidateDetails(Set<RpValidateDetail> rpValidateDetails) {
		this.rpValidateDetails = rpValidateDetails;
	}

}
