package entity;

// Generated Apr 10, 2020 2:07:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * RpSumError generated by hbm2java
 */
@Entity
@Table(name = "RP_SUM_ERROR", schema = "CIC")
public class RpSumError implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String id;
	private RpSum rpSum;
	private String errorCode;
	private String errorDes;
	private Boolean source;
	private String beginRow;
	private String errorCause;
	
	@Column(name = "ERROR_CAUSE", length = 40)
	public String getErrorCause() {
		return errorCause;
	}

	public void setErrorCause(String errorCause) {
		this.errorCause = errorCause;
	}

	public RpSumError() {
	}

	public RpSumError(String id, RpSum rpSum) {
		this.id = id;
		this.rpSum = rpSum;
	}

	public RpSumError(String id, RpSum rpSum, String errorCode, String errorDes, Boolean source) {
		this.id = id;
		this.rpSum = rpSum;
		this.errorCode = errorCode;
		this.errorDes = errorDes;
		this.source = source;
	}

	
	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 40)
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RP_SUM_ID", nullable = false)
	public RpSum getRpSum() {
		return this.rpSum;
	}

	public void setRpSum(RpSum rpSum) {
		this.rpSum = rpSum;
	}

	@Column(name = "ERROR_CODE", length = 40)
	public String getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "ERROR_DES", length = 2000)
	public String getErrorDes() {
		return this.errorDes;
	}

	public void setErrorDes(String errorDes) {
		this.errorDes = errorDes;
	}

	@Column(name = "SOURCE", precision = 1, scale = 0)
	public Boolean getSource() {
		return this.source;
	}

	public void setSource(Boolean source) {
		this.source = source;
	}

	@Column(name = "BEGIN_ROW", length = 20)
	public String getBeginRow() {
		return beginRow;
	}

	public void setBeginRow(String beginRow) {
		this.beginRow = beginRow;
	}

}
