package entity;

// Generated Apr 10, 2020 2:07:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RpSumBranchErr generated by hbm2java
 */
@Entity
@Table(name = "RP_SUM_BRANCH_ERR", schema = "CIC")
public class RpSumBranchErr implements java.io.Serializable {

	private String id;
	private RpSumBranch rpSumBranch;
	private String errorCode;
	private String errorCause;
	private String errorDes;

	public RpSumBranchErr() {
	}

	public RpSumBranchErr(String id, RpSumBranch rpSumBranch) {
		this.id = id;
		this.rpSumBranch = rpSumBranch;
	}

	public RpSumBranchErr(String id, RpSumBranch rpSumBranch, String errorCode, String errorDes) {
		this.id = id;
		this.rpSumBranch = rpSumBranch;
		this.errorCode = errorCode;
		this.errorDes = errorDes;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 40)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RP_SUM_BRANCH_ID", nullable = false)
	public RpSumBranch getRpSumBranch() {
		return this.rpSumBranch;
	}

	public void setRpSumBranch(RpSumBranch rpSumBranch) {
		this.rpSumBranch = rpSumBranch;
	}

	@Column(name = "ERROR_CODE", length = 40)
	public String getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "ERROR_DES", length = 2000)
	public String getErrorDes() {
		return this.errorDes;
	}

	public void setErrorDes(String errorDes) {
		this.errorDes = errorDes;
	}
	
	@Column(name = "ERROR_CAUSE", length = 2000)
	public String getErrorCause() {
		return errorCause;
	}

	public void setErrorCause(String errorCause) {
		this.errorCause = errorCause;
	}


}
