package entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;

import com.fasterxml.jackson.annotation.JsonIgnore;

import entity.frwk.SysObjects;

/**
 * SysObjAppFlow generated by hbm2java
 */
@Entity
@Table(name = "SYS_OBJ_APP_FLOW")
public class SysObjAppFlow implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
    @Column(name = "ID")
    private String id;
    @Column(name = "NEXT_STATUS")
    private String nextStatus;
    @JoinColumn(name = "APP_FLOW_ID", referencedColumnName = "ID")
    @ManyToOne
    private AppFlow appFlowId;
    @JoinColumn(name = "SYS_OBJ_ID", referencedColumnName = "ID")
    @ManyToOne
    @JsonIgnore
    private SysObjects sysObjId;

    public SysObjAppFlow() {
    }

    public SysObjAppFlow(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getNextStatus() {
        return nextStatus;
    }

    public void setNextStatus(String nextStatus) {
        this.nextStatus = nextStatus;
    }

    public AppFlow getAppFlowId() {
        return appFlowId;
    }

    public void setAppFlowId(AppFlow appFlowId) {
        this.appFlowId = appFlowId;
    }

    public SysObjects getSysObjId() {
        return sysObjId;
    }

    public void setSysObjId(SysObjects sysObjId) {
        this.sysObjId = sysObjId;
    }

}
