package entity;

// Generated Jan 6, 2021 10:10:52 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TemConfig generated by hbm2java
 */
@Entity
@Table(name = "TEM_CONFIG", schema = "POC")
public class TemConfig implements java.io.Serializable {

	private BigDecimal id;
	private String tempCd;
	private String tempNm;
	private Byte priority;
	private String tempType;
	private String tempSubtype;
	private String editable;
	private String contrType;
	private String guarantor;
	private String condOth;
	private Boolean ruleApproveId;
	private String document;
	private Date createDt;
	private Date updateDt;
	private BigDecimal subjectId;

	public TemConfig() {
	}

	public TemConfig(BigDecimal id) {
		this.id = id;
	}

	public TemConfig(BigDecimal id, String tempCd, String tempNm, Byte priority, String tempType, String tempSubtype,
			String editable, String contrType, String guarantor, String condOth, Boolean ruleApproveId,
			String document, Date createDt, Date updateDt, BigDecimal subjectId) {
		this.id = id;
		this.tempCd = tempCd;
		this.tempNm = tempNm;
		this.priority = priority;
		this.tempType = tempType;
		this.tempSubtype = tempSubtype;
		this.editable = editable;
		this.contrType = contrType;
		this.guarantor = guarantor;
		this.condOth = condOth;
		this.ruleApproveId = ruleApproveId;
		this.document = document;
		this.createDt = createDt;
		this.updateDt = updateDt;
		this.subjectId = subjectId;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "TEMP_CD", length = 15)
	public String getTempCd() {
		return this.tempCd;
	}

	public void setTempCd(String tempCd) {
		this.tempCd = tempCd;
	}

	@Column(name = "TEMP_NM", length = 200)
	public String getTempNm() {
		return this.tempNm;
	}

	public void setTempNm(String tempNm) {
		this.tempNm = tempNm;
	}

	@Column(name = "PRIORITY", precision = 2, scale = 0)
	public Byte getPriority() {
		return this.priority;
	}

	public void setPriority(Byte priority) {
		this.priority = priority;
	}

	@Column(name = "TEMP_TYPE", length = 10)
	public String getTempType() {
		return this.tempType;
	}

	public void setTempType(String tempType) {
		this.tempType = tempType;
	}

	@Column(name = "TEMP_SUBTYPE", length = 10)
	public String getTempSubtype() {
		return this.tempSubtype;
	}

	public void setTempSubtype(String tempSubtype) {
		this.tempSubtype = tempSubtype;
	}

	@Column(name = "EDITABLE", length = 5)
	public String getEditable() {
		return this.editable;
	}

	public void setEditable(String editable) {
		this.editable = editable;
	}

	@Column(name = "CONTR_TYPE", length = 2)
	public String getContrType() {
		return this.contrType;
	}

	public void setContrType(String contrType) {
		this.contrType = contrType;
	}

	@Column(name = "GUARANTOR", length = 20)
	public String getGuarantor() {
		return this.guarantor;
	}

	public void setGuarantor(String guarantor) {
		this.guarantor = guarantor;
	}

	@Column(name = "COND_OTH", length = 200)
	public String getCondOth() {
		return this.condOth;
	}

	public void setCondOth(String condOth) {
		this.condOth = condOth;
	}

	@Column(name = "RULE_APPROVE_ID", precision = 1, scale = 0)
	public Boolean getRuleApproveId() {
		return this.ruleApproveId;
	}

	public void setRuleApproveId(Boolean ruleApproveId) {
		this.ruleApproveId = ruleApproveId;
	}

	@Column(name = "DOCUMENT", length = 20)
	public String getDocument() {
		return this.document;
	}

	public void setDocument(String document) {
		this.document = document;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DT", length = 7)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATE_DT", length = 7)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "SUBJECT_ID", precision = 22, scale = 0)
	public BigDecimal getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(BigDecimal subjectId) {
		this.subjectId = subjectId;
	}
	

}
