package entity;

import java.sql.Blob;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;

import common.util.Formater;
import entity.frwk.SysDictParam;

/**
 * Templates generated by hbm2java
 */
@Entity
@Table(name = "TEMPLATES", schema = "POC", uniqueConstraints = @UniqueConstraint(columnNames = "CODE"))
public class Templates implements java.io.Serializable {

	private String id;
	private TemConfig temConfig;
	private Date effDate;
	private Short order;
	private Date expDate;
	private String tempNm;
	private String pathFile;
	private String noteCmd;
	private String status;
	private Blob tempFile;
	private Date updDate;
	private String updBy;
	private Blob tempXml;
	private Date approvDate;
	private String approvBy;
	private Byte type;
	private Boolean fastInput;
	private Boolean isAllProd;
	private String code;
	private String fileName;
	private Boolean multiInstance;
	private String path;
	private SysDictParam approveRole;
	private String sysCustomerType;
	private String branchForm;
	private String description;
	private String followText;
	private Date dateText;
	private Byte displayOrder;
	private List<DictTemp> lstDictTemps = new ArrayList<DictTemp>();
	private String expDateStr;
	private String effDateStr;
	public Templates() {
	}

	public Templates(String id, String code) {
		this.id = id;
		this.code = code;
	}

	@Id
    @Column(name = "ID")
    @GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TEMPCONFIG_ID")
	public TemConfig getTemConfig() {
		return this.temConfig;
	}

	public void setTemConfig(TemConfig temConfig) {
		this.temConfig = temConfig;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EFF_DATE", length = 7)
	public Date getEffDate() {
		return this.effDate;
	}

	@Column(name = "TEMP_NM", length = 200)
	public String getTempNm() {
		return this.tempNm;
	}

	public void setTempNm(String tempNm) {
		this.tempNm = tempNm;
	}

	@Column(name = "PATH_FILE", length = 300)
	public String getPathFile() {
		return this.pathFile;
	}

	public void setPathFile(String pathFile) {
		this.pathFile = pathFile;
	}

	@Column(name = "NOTE_CMD", length = 3000)
	public String getNoteCmd() {
		return this.noteCmd;
	}

	public void setNoteCmd(String noteCmd) {
		this.noteCmd = noteCmd;
	}

	@Column(name = "STATUS", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "TEMP_FILE")
	public Blob getTempFile() {
		return this.tempFile;
	}

	public void setTempFile(Blob tempFile) {
		this.tempFile = tempFile;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPD_DATE", length = 7)
	public Date getUpdDate() {
		return this.updDate;
	}

	public void setUpdDate(Date updDate) {
		this.updDate = updDate;
	}

	@Column(name = "UPD_BY", length = 50)
	public String getUpdBy() {
		return this.updBy;
	}

	public void setUpdBy(String updBy) {
		this.updBy = updBy;
	}

	@Column(name = "TEMP_XML")
	public Blob getTempXml() {
		return this.tempXml;
	}

	public void setTempXml(Blob tempXml) {
		this.tempXml = tempXml;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "APPROV_DATE", length = 7)
	public Date getApprovDate() {
		return this.approvDate;
	}

	public void setApprovDate(Date approvDate) {
		this.approvDate = approvDate;
	}

	@Column(name = "APPROV_BY", length = 50)
	public String getApprovBy() {
		return this.approvBy;
	}

	public void setApprovBy(String approvBy) {
		this.approvBy = approvBy;
	}

	@Column(name = "TYPE", precision = 1, scale = 0)
	public Byte getType() {
		return this.type;
	}

	public void setType(Byte type) {
		this.type = type;
	}

	@Column(name = "FAST_INPUT", precision = 1, scale = 0)
	public Boolean getFastInput() {
		return this.fastInput;
	}

	public void setFastInput(Boolean fastInput) {
		this.fastInput = fastInput;
	}

	@Column(name = "IS_ALL_PROD", precision = 1, scale = 0)
	public Boolean getIsAllProd() {
		return this.isAllProd;
	}

	public void setIsAllProd(Boolean isAllProd) {
		this.isAllProd = isAllProd;
	}

	@Column(name = "CODE", unique = true, nullable = false, length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "FILE_NAME", length = 200)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "MULTI_INSTANCE", precision = 1, scale = 0)
	public Boolean getMultiInstance() {
		return this.multiInstance;
	}

	public void setMultiInstance(Boolean multiInstance) {
		this.multiInstance = multiInstance;
	}

	@Column(name = "PATH", length = 300)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@JoinColumn(name = "APPROVE_ROLE", referencedColumnName = "ID")
	@ManyToOne(optional = true)
	public SysDictParam getApproveRole() {
		return this.approveRole;
	}

	public void setApproveRole(SysDictParam approveRole) {
		this.approveRole = approveRole;
	}

	@Column(name = "SYS_CUSTOMER_TYPE", length = 50)
	public String getSysCustomerType() {
		return this.sysCustomerType;
	}

	public void setSysCustomerType(String sysCustomerType) {
		this.sysCustomerType = sysCustomerType;
	}

	@Column(name = "BRANCH_FORM", length = 5)
	public String getBranchForm() {
		return this.branchForm;
	}

	public void setBranchForm(String branchForm) {
		this.branchForm = branchForm;
	}

	@Column(name = "DESCRIPTION", length = 3000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "FOLLOW_TEXT", length = 100)
	public String getFollowText() {
		return this.followText;
	}

	public void setFollowText(String followText) {
		this.followText = followText;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_TEXT", length = 7)
	public Date getDateText() {
		return this.dateText;
	}

	public void setDateText(Date dateText) {
		this.dateText = dateText;
	}

	@Column(name = "DISPLAY_ORDER", precision = 2, scale = 0)
	public Byte getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(Byte displayOrder) {
		this.displayOrder = displayOrder;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "templates", cascade = CascadeType.ALL)
	@OneToMany(cascade = CascadeType.ALL, mappedBy = "templates")
	public List<DictTemp> getLstDictTemps() {
		return lstDictTemps;
	}

	public void setLstDictTemps(List<DictTemp> lstDictTemps) {
		this.lstDictTemps = lstDictTemps;
	}

	public void setEffDate(Date effDate) {
		this.effDate = effDate;
		if (effDate != null)
			this.expDateStr = Formater.date2str(effDate);
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "EXP_DATE", length = 7)
	public Date getExpDate() {
		return this.expDate;
	}

	@Transient
	public String getExpDateStr() {
		return expDateStr;
	}

	public void setExpDateStr(String expDateStr) {
		this.expDateStr = expDateStr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXP_DATE", length = 7)
	public void setExpDate(Date expDate) {
		this.expDate = expDate;
		if (expDate != null)
			this.expDateStr = Formater.date2str(expDate);
	}

	

	public void setEffDateStr(String effDateStr) throws Exception {
		this.effDateStr = effDateStr;
		if (!Formater.isNull(effDateStr))
			this.effDate = Formater.str2date(effDateStr);
	}
	
	@Transient
	public String getEffDateStr() {
		return effDateStr;
	}

	@Transient
	public Short getOrder() {
		return order;
	}

	public void setOrder(Short order) {
		this.order = order;
	}

}
