//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.24 at 03:09:31 PM ICT 
//


package vn.com.cmc.ws.cicService;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CHFunction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CHFunction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TenFunction" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DSTHamSo" type="{http://www.endpoint.ws.core.cic.org.vn/cicqr}DSTHamSo"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CHFunction", propOrder = {
    "tenFunction",
    "dstHamSo"
})
public class CHFunction {

    @XmlElement(name = "TenFunction", required = true)
    protected String tenFunction;
    @XmlElement(name = "DSTHamSo", required = true)
    protected DSTHamSo dstHamSo;

    /**
     * Gets the value of the tenFunction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenFunction() {
        return tenFunction;
    }

    /**
     * Sets the value of the tenFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenFunction(String value) {
        this.tenFunction = value;
    }

    /**
     * Gets the value of the dstHamSo property.
     * 
     * @return
     *     possible object is
     *     {@link DSTHamSo }
     *     
     */
    public DSTHamSo getDSTHamSo() {
        return dstHamSo;
    }

    /**
     * Sets the value of the dstHamSo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DSTHamSo }
     *     
     */
    public void setDSTHamSo(DSTHamSo value) {
        this.dstHamSo = value;
    }

}
