//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.24 at 03:09:31 PM ICT 
//


package vn.com.cmc.ws.cicService;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ThamSo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ThamSo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TenTS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="GiaTriTS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ThamSo", propOrder = {
    "tenTS",
    "giaTriTS"
})
public class ThamSo {

    @XmlElement(name = "TenTS", required = true)
    protected String tenTS;
    @XmlElement(name = "GiaTriTS", required = true)
    protected String giaTriTS;

    /**
     * Gets the value of the tenTS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenTS() {
        return tenTS;
    }

    /**
     * Sets the value of the tenTS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenTS(String value) {
        this.tenTS = value;
    }

    /**
     * Gets the value of the giaTriTS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGiaTriTS() {
        return giaTriTS;
    }

    /**
     * Sets the value of the giaTriTS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGiaTriTS(String value) {
        this.giaTriTS = value;
    }

}
