//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.09 at 05:16:55 PM ICT 
//


package cic.ws.login;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for customInfor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="customInfor"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="diachi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="dkkd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="macic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="msthue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="socmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tenkh" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="loaikh" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "customInfor", propOrder = {
    "diachi",
    "dkkd",
    "macic",
    "msthue",
    "note",
    "socmt",
    "tenkh",
    "loaikh",
    "status"
})
public class CustomInfor {

    protected String diachi;
    protected String dkkd;
    protected String macic;
    protected String msthue;
    protected String note;
    protected String socmt;
    protected String tenkh;
    protected String loaikh;
    protected Integer status;

    /**
     * Gets the value of the diachi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiachi() {
        return diachi;
    }

    /**
     * Sets the value of the diachi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiachi(String value) {
        this.diachi = value;
    }

    /**
     * Gets the value of the dkkd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDkkd() {
        return dkkd;
    }

    /**
     * Sets the value of the dkkd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDkkd(String value) {
        this.dkkd = value;
    }

    /**
     * Gets the value of the macic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMacic() {
        return macic;
    }

    /**
     * Sets the value of the macic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMacic(String value) {
        this.macic = value;
    }

    /**
     * Gets the value of the msthue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsthue() {
        return msthue;
    }

    /**
     * Sets the value of the msthue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsthue(String value) {
        this.msthue = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the socmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSocmt() {
        return socmt;
    }

    /**
     * Sets the value of the socmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSocmt(String value) {
        this.socmt = value;
    }

    /**
     * Gets the value of the tenkh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenkh() {
        return tenkh;
    }

    /**
     * Sets the value of the tenkh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenkh(String value) {
        this.tenkh = value;
    }

    /**
     * Gets the value of the loaikh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoaikh() {
        return loaikh;
    }

    /**
     * Sets the value of the loaikh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoaikh(String value) {
        this.loaikh = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStatus(Integer value) {
        this.status = value;
    }

}
