//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.09 at 05:16:55 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ws.security.cic.fpt.com/")
package cic.ws.login;
