//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.21 at 03:12:12 PM ICT 
//


package vn.org.cic.h2h.ws.endpoint.cicstatisticalreport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MaBaoCao" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TuNgay" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DenNgay" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "maBaoCao",
    "tuNgay",
    "denNgay"
})
@XmlRootElement(name = "BaoCaoThongKe")
public class BaoCaoThongKe {

    @XmlElement(name = "MaBaoCao", required = true)
    protected String maBaoCao;
    @XmlElement(name = "TuNgay", required = true)
    protected String tuNgay;
    @XmlElement(name = "DenNgay", required = true)
    protected String denNgay;

    /**
     * Gets the value of the maBaoCao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaBaoCao() {
        return maBaoCao;
    }

    /**
     * Sets the value of the maBaoCao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaBaoCao(String value) {
        this.maBaoCao = value;
    }

    /**
     * Gets the value of the tuNgay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTuNgay() {
        return tuNgay;
    }

    /**
     * Sets the value of the tuNgay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTuNgay(String value) {
        this.tuNgay = value;
    }

    /**
     * Gets the value of the denNgay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDenNgay() {
        return denNgay;
    }

    /**
     * Sets the value of the denNgay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDenNgay(String value) {
        this.denNgay = value;
    }

}
