//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.18 at 01:37:14 PM ICT 
//


package vn.org.cic.h2h.ws.endpoint.cicqa;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DSKhachHangKQ complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DSKhachHangKQ">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DongKQ" type="{http://www.endpoint.ws.h2h.cic.org.vn/cicqa}DongKQ" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DSKhachHangKQ", propOrder = {
    "dongKQ"
})
public class DSKhachHangKQ {

    @XmlElement(name = "DongKQ")
    protected List<DongKQ> dongKQ;

    /**
     * Gets the value of the dongKQ property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dongKQ property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDongKQ().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DongKQ }
     * 
     * 
     */
    public List<DongKQ> getDongKQ() {
        if (dongKQ == null) {
            dongKQ = new ArrayList<DongKQ>();
        }
        return this.dongKQ;
    }

}
