//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.19 at 03:22:32 PM ICT 
//


package vn.org.cic.h2h.ws.endpoint.cicqa;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import vn.org.cic.h2h.ws.endpoint.cicqaprod.DSKhachHang;
import vn.org.cic.h2h.ws.endpoint.cicqaprod.TTChung;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TTChung" type="{http://www.endpoint.ws.h2h.cic.org.vn/cicqaProd}TTChung"/&gt;
 *         &lt;element name="DSKhachHang" type="{http://www.endpoint.ws.h2h.cic.org.vn/cicqaProd}DSKhachHang"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ttChung",
    "dsKhachHang"
})
@XmlRootElement(name = "HoiTin")
public class HoiTin {

    @XmlElement(name = "TTChung", required = true)
    protected TTChung ttChung;
    @XmlElement(name = "DSKhachHang", required = true)
    protected DSKhachHang dsKhachHang;

    /**
     * Gets the value of the ttChung property.
     * 
     * @return
     *     possible object is
     *     {@link TTChung }
     *     
     */
    public TTChung getTTChung() {
        return ttChung;
    }

    /**
     * Sets the value of the ttChung property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTChung }
     *     
     */
    public void setTTChung(TTChung value) {
        this.ttChung = value;
    }

    /**
     * Gets the value of the dsKhachHang property.
     * 
     * @return
     *     possible object is
     *     {@link DSKhachHang }
     *     
     */
    public DSKhachHang getDSKhachHang() {
        return dsKhachHang;
    }

    /**
     * Sets the value of the dsKhachHang property.
     * 
     * @param value
     *     allowed object is
     *     {@link DSKhachHang }
     *     
     */
    public void setDSKhachHang(DSKhachHang value) {
        this.dsKhachHang = value;
    }

}
