//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.19 at 03:22:32 PM ICT 
//


package vn.org.cic.h2h.ws.endpoint.cicqa;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MaSP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TenTep" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="NoiDungTep" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "maSP",
    "tenTep",
    "noiDungTep"
})
@XmlRootElement(name = "TepHoiTin")
public class TepHoiTin {

    @XmlElement(name = "MaSP", required = true)
    protected String maSP;
    @XmlElement(name = "TenTep", required = true)
    protected String tenTep;
    @XmlElement(name = "NoiDungTep", required = true)
    protected String noiDungTep;

    /**
     * Gets the value of the maSP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaSP() {
        return maSP;
    }

    /**
     * Sets the value of the maSP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaSP(String value) {
        this.maSP = value;
    }

    /**
     * Gets the value of the tenTep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenTep() {
        return tenTep;
    }

    /**
     * Sets the value of the tenTep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenTep(String value) {
        this.tenTep = value;
    }

    /**
     * Gets the value of the noiDungTep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoiDungTep() {
        return noiDungTep;
    }

    /**
     * Sets the value of the noiDungTep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoiDungTep(String value) {
        this.noiDungTep = value;
    }

}
