//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.18 at 01:37:14 PM ICT 
//


package vn.org.cic.h2h.ws.endpoint.cicqa;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TepTraLoi complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TepTraLoi">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LoaiSP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TenTepTraLoi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NoiDungTepTraLoi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TepTraLoi", propOrder = {
    "loaiSP",
    "tenTepTraLoi",
    "noiDungTepTraLoi"
})
public class TepTraLoi {

    @XmlElement(name = "LoaiSP", required = true)
    protected String loaiSP;
    @XmlElement(name = "TenTepTraLoi", required = true)
    protected String tenTepTraLoi;
    @XmlElement(name = "NoiDungTepTraLoi", required = true)
    protected String noiDungTepTraLoi;

    /**
     * Gets the value of the loaiSP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoaiSP() {
        return loaiSP;
    }

    /**
     * Sets the value of the loaiSP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoaiSP(String value) {
        this.loaiSP = value;
    }

    /**
     * Gets the value of the tenTepTraLoi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenTepTraLoi() {
        return tenTepTraLoi;
    }

    /**
     * Sets the value of the tenTepTraLoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenTepTraLoi(String value) {
        this.tenTepTraLoi = value;
    }

    /**
     * Gets the value of the noiDungTepTraLoi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoiDungTepTraLoi() {
        return noiDungTepTraLoi;
    }

    /**
     * Sets the value of the noiDungTepTraLoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoiDungTepTraLoi(String value) {
        this.noiDungTepTraLoi = value;
    }

}
