//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.19 at 03:22:32 PM ICT 
//


package vn.org.cic.h2h.ws.endpoint.cicqa;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NgayHT" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TrangThai" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ngayHT",
    "trangThai"
})
@XmlRootElement(name = "TrangThaiTepHT")
public class TrangThaiTepHT {

    @XmlElement(name = "NgayHT", required = true)
    protected String ngayHT;
    @XmlElement(name = "TrangThai", required = true)
    protected String trangThai;

    /**
     * Gets the value of the ngayHT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNgayHT() {
        return ngayHT;
    }

    /**
     * Sets the value of the ngayHT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNgayHT(String value) {
        this.ngayHT = value;
    }

    /**
     * Gets the value of the trangThai property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrangThai() {
        return trangThai;
    }

    /**
     * Sets the value of the trangThai property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrangThai(String value) {
        this.trangThai = value;
    }

}
