//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.18 at 01:37:14 PM ICT 
//


package vn.org.cic.h2h.ws.endpoint.cicqa;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TTChung complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TTChung">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LoaiSP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SLPhieu" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TTChung", propOrder = {
    "loaiSP",
    "slPhieu"
})
public class TTChung {

    @XmlElement(name = "LoaiSP", required = true)
    protected String loaiSP;
    @XmlElement(name = "SLPhieu", required = true)
    protected BigInteger slPhieu;

    /**
     * Gets the value of the loaiSP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoaiSP() {
        return loaiSP;
    }

    /**
     * Sets the value of the loaiSP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoaiSP(String value) {
        this.loaiSP = value;
    }

    /**
     * Gets the value of the slPhieu property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSLPhieu() {
        return slPhieu;
    }

    /**
     * Sets the value of the slPhieu property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSLPhieu(BigInteger value) {
        this.slPhieu = value;
    }

}
