//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.19 at 03:22:32 PM ICT 
//


package vn.org.cic.h2h.ws.endpoint.cicqaprod;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TepTraLoi complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TepTraLoi"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MaSP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TenTepTraLoi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="NoiDungTepTraLoi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TenTepLoi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="NoiDungTepLoi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TepTraLoi", propOrder = {
    "maSP",
    "tenTepTraLoi",
    "noiDungTepTraLoi",
    "tenTepLoi",
    "noiDungTepLoi"
})
public class TepTraLoi {

    @XmlElement(name = "MaSP", required = true)
    protected String maSP;
    @XmlElement(name = "TenTepTraLoi", required = true)
    protected String tenTepTraLoi;
    @XmlElement(name = "NoiDungTepTraLoi", required = true)
    protected String noiDungTepTraLoi;
    @XmlElement(name = "TenTepLoi", required = true)
    protected String tenTepLoi;
    @XmlElement(name = "NoiDungTepLoi", required = true)
    protected String noiDungTepLoi;

    /**
     * Gets the value of the maSP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaSP() {
        return maSP;
    }

    /**
     * Sets the value of the maSP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaSP(String value) {
        this.maSP = value;
    }

    /**
     * Gets the value of the tenTepTraLoi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenTepTraLoi() {
        return tenTepTraLoi;
    }

    /**
     * Sets the value of the tenTepTraLoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenTepTraLoi(String value) {
        this.tenTepTraLoi = value;
    }

    /**
     * Gets the value of the noiDungTepTraLoi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoiDungTepTraLoi() {
        return noiDungTepTraLoi;
    }

    /**
     * Sets the value of the noiDungTepTraLoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoiDungTepTraLoi(String value) {
        this.noiDungTepTraLoi = value;
    }

    /**
     * Gets the value of the tenTepLoi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenTepLoi() {
        return tenTepLoi;
    }

    /**
     * Sets the value of the tenTepLoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenTepLoi(String value) {
        this.tenTepLoi = value;
    }

    /**
     * Gets the value of the noiDungTepLoi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoiDungTepLoi() {
        return noiDungTepLoi;
    }

    /**
     * Sets the value of the noiDungTepLoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoiDungTepLoi(String value) {
        this.noiDungTepLoi = value;
    }

}
