//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.16 at 10:40:31 AM ICT 
//


package vn.org.cic.h2h.ws.endpoint.cicqr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Loi complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Loi">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MaLoi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MoTaLoi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Loi", propOrder = {
    "maLoi",
    "moTaLoi"
})
public class Loi {

    @XmlElement(name = "MaLoi", required = true)
    protected String maLoi;
    @XmlElement(name = "MoTaLoi", required = true)
    protected String moTaLoi;

    /**
     * Gets the value of the maLoi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaLoi() {
        return maLoi;
    }

    /**
     * Sets the value of the maLoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaLoi(String value) {
        this.maLoi = value;
    }

    /**
     * Gets the value of the moTaLoi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoTaLoi() {
        return moTaLoi;
    }

    /**
     * Sets the value of the moTaLoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoTaLoi(String value) {
        this.moTaLoi = value;
    }

}
