//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.16 at 10:40:31 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.endpoint.ws.h2h.cic.org.vn/cicqr", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package vn.org.cic.h2h.ws.endpoint.cicqr;
