//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.16 at 10:40:31 AM ICT 
//


package vn.org.cic.h2h.ws.endpoint.cicqr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TenKH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DiaChi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MaKH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MaCIC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LoaiKH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MSThue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DKKD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SoCMT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tenKH",
    "diaChi",
    "maKH",
    "maCIC",
    "loaiKH",
    "msThue",
    "dkkd",
    "soCMT"
})
@XmlRootElement(name = "TimKiemKH")
public class TimKiemKH {

    @XmlElement(name = "TenKH", required = true)
    protected String tenKH;
    @XmlElement(name = "DiaChi", required = true)
    protected String diaChi;
    @XmlElement(name = "MaKH", required = true)
    protected String maKH;
    @XmlElement(name = "MaCIC", required = true)
    protected String maCIC;
    @XmlElement(name = "LoaiKH", required = true)
    protected String loaiKH;
    @XmlElement(name = "MSThue", required = true)
    protected String msThue;
    @XmlElement(name = "DKKD", required = true)
    protected String dkkd;
    @XmlElement(name = "SoCMT", required = true)
    protected String soCMT;

    /**
     * Gets the value of the tenKH property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenKH() {
        return tenKH;
    }

    /**
     * Sets the value of the tenKH property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenKH(String value) {
        this.tenKH = value;
    }

    /**
     * Gets the value of the diaChi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiaChi() {
        return diaChi;
    }

    /**
     * Sets the value of the diaChi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiaChi(String value) {
        this.diaChi = value;
    }

    /**
     * Gets the value of the maKH property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaKH() {
        return maKH;
    }

    /**
     * Sets the value of the maKH property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaKH(String value) {
        this.maKH = value;
    }

    /**
     * Gets the value of the maCIC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaCIC() {
        return maCIC;
    }

    /**
     * Sets the value of the maCIC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaCIC(String value) {
        this.maCIC = value;
    }

    /**
     * Gets the value of the loaiKH property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoaiKH() {
        return loaiKH;
    }

    /**
     * Sets the value of the loaiKH property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoaiKH(String value) {
        this.loaiKH = value;
    }

    /**
     * Gets the value of the msThue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMSThue() {
        return msThue;
    }

    /**
     * Sets the value of the msThue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMSThue(String value) {
        this.msThue = value;
    }

    /**
     * Gets the value of the dkkd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDKKD() {
        return dkkd;
    }

    /**
     * Sets the value of the dkkd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDKKD(String value) {
        this.dkkd = value;
    }

    /**
     * Gets the value of the soCMT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoCMT() {
        return soCMT;
    }

    /**
     * Sets the value of the soCMT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoCMT(String value) {
        this.soCMT = value;
    }

}
