//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.16 at 10:40:31 AM ICT 
//


package vn.org.cic.h2h.ws.endpoint.cicqr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MaSP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DSTHamSo" type="{http://www.endpoint.ws.h2h.cic.org.vn/cicqr}DSTHamSo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "maSP",
    "dstHamSo"
})
@XmlRootElement(name = "VanTinChung")
public class VanTinChung {

    @XmlElement(name = "MaSP", required = true)
    protected String maSP;
    @XmlElement(name = "DSTHamSo", required = true)
    protected DSTHamSo dstHamSo;

    /**
     * Gets the value of the maSP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaSP() {
        return maSP;
    }

    /**
     * Sets the value of the maSP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaSP(String value) {
        this.maSP = value;
    }

    /**
     * Gets the value of the dstHamSo property.
     * 
     * @return
     *     possible object is
     *     {@link DSTHamSo }
     *     
     */
    public DSTHamSo getDSTHamSo() {
        return dstHamSo;
    }

    /**
     * Sets the value of the dstHamSo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DSTHamSo }
     *     
     */
    public void setDSTHamSo(DSTHamSo value) {
        this.dstHamSo = value;
    }

}
