//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.19 at 03:05:43 PM ICT 
//


package vn.org.intergration.ws.endpoint.cicqafile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DongKQ complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DongKQ">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MaSoPhieu" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LoaiSP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TrangThai" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NgayHoi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NgayTraLoi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NgayLayVe" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TenKH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MaKH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MaCIC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DiaChi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MSThue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DKKD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SoCMT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LoaiGTK" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SoGTK" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GhiChu" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MaSP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TenTep" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DongKQ", propOrder = {
    "maSoPhieu",
    "loaiSP",
    "trangThai",
    "ngayHoi",
    "ngayTraLoi",
    "ngayLayVe",
    "tenKH",
    "maKH",
    "maCIC",
    "diaChi",
    "msThue",
    "dkkd",
    "soCMT",
    "loaiGTK",
    "soGTK",
    "ghiChu",
    "maSP",
    "tenTep"
})
public class DongKQ {

    @XmlElement(name = "MaSoPhieu", required = true)
    protected String maSoPhieu;
    @XmlElement(name = "LoaiSP", required = true)
    protected String loaiSP;
    @XmlElement(name = "TrangThai", required = true)
    protected String trangThai;
    @XmlElement(name = "NgayHoi", required = true)
    protected String ngayHoi;
    @XmlElement(name = "NgayTraLoi", required = true)
    protected String ngayTraLoi;
    @XmlElement(name = "NgayLayVe", required = true)
    protected String ngayLayVe;
    @XmlElement(name = "TenKH", required = true)
    protected String tenKH;
    @XmlElement(name = "MaKH", required = true)
    protected String maKH;
    @XmlElement(name = "MaCIC", required = true)
    protected String maCIC;
    @XmlElement(name = "DiaChi", required = true)
    protected String diaChi;
    @XmlElement(name = "MSThue", required = true)
    protected String msThue;
    @XmlElement(name = "DKKD", required = true)
    protected String dkkd;
    @XmlElement(name = "SoCMT", required = true)
    protected String soCMT;
    @XmlElement(name = "LoaiGTK", required = true)
    protected String loaiGTK;
    @XmlElement(name = "SoGTK", required = true)
    protected String soGTK;
    @XmlElement(name = "GhiChu", required = true)
    protected String ghiChu;
    @XmlElement(name = "MaSP", required = true)
    protected String maSP;
    @XmlElement(name = "TenTep", required = true)
    protected String tenTep;

    /**
     * Gets the value of the maSoPhieu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaSoPhieu() {
        return maSoPhieu;
    }

    /**
     * Sets the value of the maSoPhieu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaSoPhieu(String value) {
        this.maSoPhieu = value;
    }

    /**
     * Gets the value of the loaiSP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoaiSP() {
        return loaiSP;
    }

    /**
     * Sets the value of the loaiSP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoaiSP(String value) {
        this.loaiSP = value;
    }

    /**
     * Gets the value of the trangThai property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrangThai() {
        return trangThai;
    }

    /**
     * Sets the value of the trangThai property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrangThai(String value) {
        this.trangThai = value;
    }

    /**
     * Gets the value of the ngayHoi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNgayHoi() {
        return ngayHoi;
    }

    /**
     * Sets the value of the ngayHoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNgayHoi(String value) {
        this.ngayHoi = value;
    }

    /**
     * Gets the value of the ngayTraLoi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNgayTraLoi() {
        return ngayTraLoi;
    }

    /**
     * Sets the value of the ngayTraLoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNgayTraLoi(String value) {
        this.ngayTraLoi = value;
    }

    /**
     * Gets the value of the ngayLayVe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNgayLayVe() {
        return ngayLayVe;
    }

    /**
     * Sets the value of the ngayLayVe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNgayLayVe(String value) {
        this.ngayLayVe = value;
    }

    /**
     * Gets the value of the tenKH property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenKH() {
        return tenKH;
    }

    /**
     * Sets the value of the tenKH property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenKH(String value) {
        this.tenKH = value;
    }

    /**
     * Gets the value of the maKH property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaKH() {
        return maKH;
    }

    /**
     * Sets the value of the maKH property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaKH(String value) {
        this.maKH = value;
    }

    /**
     * Gets the value of the maCIC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaCIC() {
        return maCIC;
    }

    /**
     * Sets the value of the maCIC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaCIC(String value) {
        this.maCIC = value;
    }

    /**
     * Gets the value of the diaChi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiaChi() {
        return diaChi;
    }

    /**
     * Sets the value of the diaChi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiaChi(String value) {
        this.diaChi = value;
    }

    /**
     * Gets the value of the msThue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMSThue() {
        return msThue;
    }

    /**
     * Sets the value of the msThue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMSThue(String value) {
        this.msThue = value;
    }

    /**
     * Gets the value of the dkkd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDKKD() {
        return dkkd;
    }

    /**
     * Sets the value of the dkkd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDKKD(String value) {
        this.dkkd = value;
    }

    /**
     * Gets the value of the soCMT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoCMT() {
        return soCMT;
    }

    /**
     * Sets the value of the soCMT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoCMT(String value) {
        this.soCMT = value;
    }

    /**
     * Gets the value of the loaiGTK property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoaiGTK() {
        return loaiGTK;
    }

    /**
     * Sets the value of the loaiGTK property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoaiGTK(String value) {
        this.loaiGTK = value;
    }

    /**
     * Gets the value of the soGTK property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoGTK() {
        return soGTK;
    }

    /**
     * Sets the value of the soGTK property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoGTK(String value) {
        this.soGTK = value;
    }

    /**
     * Gets the value of the ghiChu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGhiChu() {
        return ghiChu;
    }

    /**
     * Sets the value of the ghiChu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGhiChu(String value) {
        this.ghiChu = value;
    }

    /**
     * Gets the value of the maSP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaSP() {
        return maSP;
    }

    /**
     * Sets the value of the maSP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaSP(String value) {
        this.maSP = value;
    }

    /**
     * Gets the value of the tenTep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenTep() {
        return tenTep;
    }

    /**
     * Sets the value of the tenTep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenTep(String value) {
        this.tenTep = value;
    }

}
