//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.19 at 03:05:43 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.endpoint.ws.intergration.org.vn/cicqaFile", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package vn.org.intergration.ws.endpoint.cicqafile;
