//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.19 at 03:05:43 PM ICT 
//


package vn.org.intergration.ws.endpoint.cicstatisticalreport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TTPhanHoi" type="{http://www.endpoint.ws.intergration.org.vn/cicstatisticalreport}TTPhanHoi"/>
 *         &lt;element name="DongKQ" type="{http://www.endpoint.ws.intergration.org.vn/cicstatisticalreport}DongKQ"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ttPhanHoi",
    "dongKQ"
})
@XmlRootElement(name = "PHBaoCaoThongKe")
public class PHBaoCaoThongKe {

    @XmlElement(name = "TTPhanHoi", required = true)
    protected TTPhanHoi ttPhanHoi;
    @XmlElement(name = "DongKQ", required = true)
    protected DongKQ dongKQ;

    /**
     * Gets the value of the ttPhanHoi property.
     * 
     * @return
     *     possible object is
     *     {@link TTPhanHoi }
     *     
     */
    public TTPhanHoi getTTPhanHoi() {
        return ttPhanHoi;
    }

    /**
     * Sets the value of the ttPhanHoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTPhanHoi }
     *     
     */
    public void setTTPhanHoi(TTPhanHoi value) {
        this.ttPhanHoi = value;
    }

    /**
     * Gets the value of the dongKQ property.
     * 
     * @return
     *     possible object is
     *     {@link DongKQ }
     *     
     */
    public DongKQ getDongKQ() {
        return dongKQ;
    }

    /**
     * Sets the value of the dongKQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link DongKQ }
     *     
     */
    public void setDongKQ(DongKQ value) {
        this.dongKQ = value;
    }

}
