//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.04 at 01:28:05 PM ICT 
//


package vn.org.intergration.ws.endpoint.cicqr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TrangThai" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Ma" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MoTa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Data" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DSThamSoLoi" type="{http://www.endpoint.ws.intergration.org.vn/cicqr}DSThamSoLoi"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trangThai",
    "ma",
    "moTa",
    "data",
    "dsThamSoLoi"
})
@XmlRootElement(name = "PHVanTinChung")
public class PHVanTinChung {

    @XmlElement(name = "TrangThai", required = true)
    protected String trangThai;
    @XmlElement(name = "Ma", required = true)
    protected String ma;
    @XmlElement(name = "MoTa", required = true)
    protected String moTa;
    @XmlElement(name = "Data", required = true)
    protected String data;
    @XmlElement(name = "DSThamSoLoi", required = true)
    protected DSThamSoLoi dsThamSoLoi;

    /**
     * Gets the value of the trangThai property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrangThai() {
        return trangThai;
    }

    /**
     * Sets the value of the trangThai property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrangThai(String value) {
        this.trangThai = value;
    }

    /**
     * Gets the value of the ma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMa() {
        return ma;
    }

    /**
     * Sets the value of the ma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMa(String value) {
        this.ma = value;
    }

    /**
     * Gets the value of the moTa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoTa() {
        return moTa;
    }

    /**
     * Sets the value of the moTa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoTa(String value) {
        this.moTa = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setData(String value) {
        this.data = value;
    }

    /**
     * Gets the value of the dsThamSoLoi property.
     * 
     * @return
     *     possible object is
     *     {@link DSThamSoLoi }
     *     
     */
    public DSThamSoLoi getDSThamSoLoi() {
        return dsThamSoLoi;
    }

    /**
     * Sets the value of the dsThamSoLoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link DSThamSoLoi }
     *     
     */
    public void setDSThamSoLoi(DSThamSoLoi value) {
        this.dsThamSoLoi = value;
    }

}
