//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.04 at 01:28:05 PM ICT 
//


package vn.org.intergration.ws.endpoint.cicqr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ThamSoLoi complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ThamSoLoi">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TenTS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MoTaLoi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ThamSoLoi", propOrder = {
    "tenTS",
    "moTaLoi"
})
public class ThamSoLoi {

    @XmlElement(name = "TenTS", required = true)
    protected String tenTS;
    @XmlElement(name = "MoTaLoi", required = true)
    protected String moTaLoi;

    /**
     * Gets the value of the tenTS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenTS() {
        return tenTS;
    }

    /**
     * Sets the value of the tenTS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenTS(String value) {
        this.tenTS = value;
    }

    /**
     * Gets the value of the moTaLoi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoTaLoi() {
        return moTaLoi;
    }

    /**
     * Sets the value of the moTaLoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoTaLoi(String value) {
        this.moTaLoi = value;
    }

}
