//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.01 at 11:37:22 AM ICT 
//


package cic.ws.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TuNgay" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DenNgay" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TrangThai" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="NguoiYC" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tuNgay",
    "denNgay",
    "trangThai",
    "nguoiYC"
})
@XmlRootElement(name = "DanhSachTepPhanHoi")
public class DanhSachTepPhanHoi {

    @XmlElement(name = "TuNgay", required = true)
    protected String tuNgay;
    @XmlElement(name = "DenNgay", required = true)
    protected String denNgay;
    @XmlElement(name = "TrangThai", required = true)
    protected String trangThai;
    @XmlElement(name = "NguoiYC", required = true)
    protected String nguoiYC;

    /**
     * Gets the value of the tuNgay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTuNgay() {
        return tuNgay;
    }

    /**
     * Sets the value of the tuNgay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTuNgay(String value) {
        this.tuNgay = value;
    }

    /**
     * Gets the value of the denNgay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDenNgay() {
        return denNgay;
    }

    /**
     * Sets the value of the denNgay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDenNgay(String value) {
        this.denNgay = value;
    }

    /**
     * Gets the value of the trangThai property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrangThai() {
        return trangThai;
    }

    /**
     * Sets the value of the trangThai property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrangThai(String value) {
        this.trangThai = value;
    }

    /**
     * Gets the value of the nguoiYC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNguoiYC() {
        return nguoiYC;
    }

    /**
     * Sets the value of the nguoiYC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNguoiYC(String value) {
        this.nguoiYC = value;
    }

}
