//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.01 at 11:37:22 AM ICT 
//


package cic.ws.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TTPhanHoi" type="{http://www.endpoint.ws.cmc.com.vn/cicreport}TTPhanHoi"/&gt;
 *         &lt;element name="DSLoi" type="{http://www.endpoint.ws.cmc.com.vn/cicreport}DSLoi"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ttPhanHoi",
    "dsLoi"
})
@XmlRootElement(name = "PHTepPhiCauTruc")
public class PHTepPhiCauTruc {

    @XmlElement(name = "TTPhanHoi", required = true)
    protected TTPhanHoi ttPhanHoi;
    @XmlElement(name = "DSLoi", required = true)
    protected DSLoi dsLoi;

    /**
     * Gets the value of the ttPhanHoi property.
     * 
     * @return
     *     possible object is
     *     {@link TTPhanHoi }
     *     
     */
    public TTPhanHoi getTTPhanHoi() {
        return ttPhanHoi;
    }

    /**
     * Sets the value of the ttPhanHoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTPhanHoi }
     *     
     */
    public void setTTPhanHoi(TTPhanHoi value) {
        this.ttPhanHoi = value;
    }

    /**
     * Gets the value of the dsLoi property.
     * 
     * @return
     *     possible object is
     *     {@link DSLoi }
     *     
     */
    public DSLoi getDSLoi() {
        return dsLoi;
    }

    /**
     * Sets the value of the dsLoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link DSLoi }
     *     
     */
    public void setDSLoi(DSLoi value) {
        this.dsLoi = value;
    }

}
