//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.16 at 11:34:15 AM ICT 
//


package com.fpt.cic.security.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for h2HTraSoat complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="h2HTraSoat"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="diachi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="dongia" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="manh" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="manhom" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="masp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="matctd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="msphieu" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ngaytraloi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="nguoihoi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="socmt_dkkd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sophieukh" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="tenkh" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tennhom" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tensanpham" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tentctd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="thoigianphatsinh" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "h2HTraSoat", propOrder = {
    "note",
    "diachi",
    "dongia",
    "manh",
    "manhom",
    "masp",
    "matctd",
    "msphieu",
    "ngaytraloi",
    "nguoihoi",
    "socmtDkkd",
    "sophieukh",
    "status",
    "tenkh",
    "tennhom",
    "tensanpham",
    "tentctd",
    "thoigianphatsinh",
    "username"
})
public class H2HTraSoat {

    protected String note;
    protected String diachi;
    protected Integer dongia;
    protected String manh;
    protected String manhom;
    protected String masp;
    protected String matctd;
    protected String msphieu;
    protected String ngaytraloi;
    protected String nguoihoi;
    @XmlElement(name = "socmt_dkkd")
    protected String socmtDkkd;
    protected String sophieukh;
    protected Integer status;
    protected String tenkh;
    protected String tennhom;
    protected String tensanpham;
    protected String tentctd;
    protected String thoigianphatsinh;
    protected String username;

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the diachi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiachi() {
        return diachi;
    }

    /**
     * Sets the value of the diachi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiachi(String value) {
        this.diachi = value;
    }

    /**
     * Gets the value of the dongia property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDongia() {
        return dongia;
    }

    /**
     * Sets the value of the dongia property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDongia(Integer value) {
        this.dongia = value;
    }

    /**
     * Gets the value of the manh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManh() {
        return manh;
    }

    /**
     * Sets the value of the manh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManh(String value) {
        this.manh = value;
    }

    /**
     * Gets the value of the manhom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManhom() {
        return manhom;
    }

    /**
     * Sets the value of the manhom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManhom(String value) {
        this.manhom = value;
    }

    /**
     * Gets the value of the masp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasp() {
        return masp;
    }

    /**
     * Sets the value of the masp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasp(String value) {
        this.masp = value;
    }

    /**
     * Gets the value of the matctd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatctd() {
        return matctd;
    }

    /**
     * Sets the value of the matctd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatctd(String value) {
        this.matctd = value;
    }

    /**
     * Gets the value of the msphieu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsphieu() {
        return msphieu;
    }

    /**
     * Sets the value of the msphieu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsphieu(String value) {
        this.msphieu = value;
    }

    /**
     * Gets the value of the ngaytraloi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNgaytraloi() {
        return ngaytraloi;
    }

    /**
     * Sets the value of the ngaytraloi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNgaytraloi(String value) {
        this.ngaytraloi = value;
    }

    /**
     * Gets the value of the nguoihoi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNguoihoi() {
        return nguoihoi;
    }

    /**
     * Sets the value of the nguoihoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNguoihoi(String value) {
        this.nguoihoi = value;
    }

    /**
     * Gets the value of the socmtDkkd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSocmtDkkd() {
        return socmtDkkd;
    }

    /**
     * Sets the value of the socmtDkkd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSocmtDkkd(String value) {
        this.socmtDkkd = value;
    }

    /**
     * Gets the value of the sophieukh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSophieukh() {
        return sophieukh;
    }

    /**
     * Sets the value of the sophieukh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSophieukh(String value) {
        this.sophieukh = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStatus(Integer value) {
        this.status = value;
    }

    /**
     * Gets the value of the tenkh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenkh() {
        return tenkh;
    }

    /**
     * Sets the value of the tenkh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenkh(String value) {
        this.tenkh = value;
    }

    /**
     * Gets the value of the tennhom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTennhom() {
        return tennhom;
    }

    /**
     * Sets the value of the tennhom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTennhom(String value) {
        this.tennhom = value;
    }

    /**
     * Gets the value of the tensanpham property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTensanpham() {
        return tensanpham;
    }

    /**
     * Sets the value of the tensanpham property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTensanpham(String value) {
        this.tensanpham = value;
    }

    /**
     * Gets the value of the tentctd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTentctd() {
        return tentctd;
    }

    /**
     * Sets the value of the tentctd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTentctd(String value) {
        this.tentctd = value;
    }

    /**
     * Gets the value of the thoigianphatsinh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThoigianphatsinh() {
        return thoigianphatsinh;
    }

    /**
     * Sets the value of the thoigianphatsinh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThoigianphatsinh(String value) {
        this.thoigianphatsinh = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

}
