//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.16 at 11:34:15 AM ICT 
//


package com.fpt.cic.security.ws;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for listTraSoat complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="listTraSoat"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="resultTraSoatH2H" type="{http://ws.security.cic.fpt.com/}h2HTraSoat" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listTraSoat", propOrder = {
    "resultTraSoatH2H"
})
public class ListTraSoat {

    @XmlElement(nillable = true)
    protected List<H2HTraSoat> resultTraSoatH2H;

    /**
     * Gets the value of the resultTraSoatH2H property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resultTraSoatH2H property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResultTraSoatH2H().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link H2HTraSoat }
     * 
     * 
     */
    public List<H2HTraSoat> getResultTraSoatH2H() {
        if (resultTraSoatH2H == null) {
            resultTraSoatH2H = new ArrayList<H2HTraSoat>();
        }
        return this.resultTraSoatH2H;
    }

}
