//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.16 at 11:34:15 AM ICT 
//


package com.fpt.cic.security.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.fpt.cic.security.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AuthenLDAP_QNAME = new QName("http://ws.security.cic.fpt.com/", "AuthenLDAP");
    private final static QName _AuthenLDAPResponse_QNAME = new QName("http://ws.security.cic.fpt.com/", "AuthenLDAPResponse");
    private final static QName _DangNhap_QNAME = new QName("http://ws.security.cic.fpt.com/", "DangNhap");
    private final static QName _DangNhapResponse_QNAME = new QName("http://ws.security.cic.fpt.com/", "DangNhapResponse");
    private final static QName _Exception_QNAME = new QName("http://ws.security.cic.fpt.com/", "Exception");
    private final static QName _GetDataS37_QNAME = new QName("http://ws.security.cic.fpt.com/", "GetDataS37");
    private final static QName _GetDataS37Response_QNAME = new QName("http://ws.security.cic.fpt.com/", "GetDataS37Response");
    private final static QName _ShowReport_QNAME = new QName("http://ws.security.cic.fpt.com/", "showReport");
    private final static QName _ShowReportResponse_QNAME = new QName("http://ws.security.cic.fpt.com/", "showReportResponse");
    private final static QName _ShowTimKiemKH_QNAME = new QName("http://ws.security.cic.fpt.com/", "showTimKiemKH");
    private final static QName _ShowTimKiemKHResponse_QNAME = new QName("http://ws.security.cic.fpt.com/", "showTimKiemKHResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.fpt.cic.security.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AuthenLDAP }
     * 
     */
    public AuthenLDAP createAuthenLDAP() {
        return new AuthenLDAP();
    }

    /**
     * Create an instance of {@link AuthenLDAPResponse }
     * 
     */
    public AuthenLDAPResponse createAuthenLDAPResponse() {
        return new AuthenLDAPResponse();
    }

    /**
     * Create an instance of {@link DangNhap }
     * 
     */
    public DangNhap createDangNhap() {
        return new DangNhap();
    }

    /**
     * Create an instance of {@link DangNhapResponse }
     * 
     */
    public DangNhapResponse createDangNhapResponse() {
        return new DangNhapResponse();
    }

    /**
     * Create an instance of {@link Exception }
     * 
     */
    public Exception createException() {
        return new Exception();
    }

    /**
     * Create an instance of {@link GetDataS37 }
     * 
     */
    public GetDataS37 createGetDataS37() {
        return new GetDataS37();
    }

    /**
     * Create an instance of {@link GetDataS37Response }
     * 
     */
    public GetDataS37Response createGetDataS37Response() {
        return new GetDataS37Response();
    }

    /**
     * Create an instance of {@link ShowReport }
     * 
     */
    public ShowReport createShowReport() {
        return new ShowReport();
    }

    /**
     * Create an instance of {@link ShowReportResponse }
     * 
     */
    public ShowReportResponse createShowReportResponse() {
        return new ShowReportResponse();
    }

    /**
     * Create an instance of {@link ShowTimKiemKH }
     * 
     */
    public ShowTimKiemKH createShowTimKiemKH() {
        return new ShowTimKiemKH();
    }

    /**
     * Create an instance of {@link ShowTimKiemKHResponse }
     * 
     */
    public ShowTimKiemKHResponse createShowTimKiemKHResponse() {
        return new ShowTimKiemKHResponse();
    }

    /**
     * Create an instance of {@link TraSoatH2H }
     * 
     */
    public TraSoatH2H createTraSoatH2H() {
        return new TraSoatH2H();
    }

    /**
     * Create an instance of {@link ListTraSoat }
     * 
     */
    public ListTraSoat createListTraSoat() {
        return new ListTraSoat();
    }

    /**
     * Create an instance of {@link H2HTraSoat }
     * 
     */
    public H2HTraSoat createH2HTraSoat() {
        return new H2HTraSoat();
    }

    /**
     * Create an instance of {@link UserInfo }
     * 
     */
    public UserInfo createUserInfo() {
        return new UserInfo();
    }

    /**
     * Create an instance of {@link ResponseSearch }
     * 
     */
    public ResponseSearch createResponseSearch() {
        return new ResponseSearch();
    }

    /**
     * Create an instance of {@link ListCustomer }
     * 
     */
    public ListCustomer createListCustomer() {
        return new ListCustomer();
    }

    /**
     * Create an instance of {@link CustomInfor }
     * 
     */
    public CustomInfor createCustomInfor() {
        return new CustomInfor();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthenLDAP }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.security.cic.fpt.com/", name = "AuthenLDAP")
    public JAXBElement<AuthenLDAP> createAuthenLDAP(AuthenLDAP value) {
        return new JAXBElement<AuthenLDAP>(_AuthenLDAP_QNAME, AuthenLDAP.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthenLDAPResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.security.cic.fpt.com/", name = "AuthenLDAPResponse")
    public JAXBElement<AuthenLDAPResponse> createAuthenLDAPResponse(AuthenLDAPResponse value) {
        return new JAXBElement<AuthenLDAPResponse>(_AuthenLDAPResponse_QNAME, AuthenLDAPResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DangNhap }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.security.cic.fpt.com/", name = "DangNhap")
    public JAXBElement<DangNhap> createDangNhap(DangNhap value) {
        return new JAXBElement<DangNhap>(_DangNhap_QNAME, DangNhap.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DangNhapResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.security.cic.fpt.com/", name = "DangNhapResponse")
    public JAXBElement<DangNhapResponse> createDangNhapResponse(DangNhapResponse value) {
        return new JAXBElement<DangNhapResponse>(_DangNhapResponse_QNAME, DangNhapResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Exception }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.security.cic.fpt.com/", name = "Exception")
    public JAXBElement<Exception> createException(Exception value) {
        return new JAXBElement<Exception>(_Exception_QNAME, Exception.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDataS37 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.security.cic.fpt.com/", name = "GetDataS37")
    public JAXBElement<GetDataS37> createGetDataS37(GetDataS37 value) {
        return new JAXBElement<GetDataS37>(_GetDataS37_QNAME, GetDataS37 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDataS37Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.security.cic.fpt.com/", name = "GetDataS37Response")
    public JAXBElement<GetDataS37Response> createGetDataS37Response(GetDataS37Response value) {
        return new JAXBElement<GetDataS37Response>(_GetDataS37Response_QNAME, GetDataS37Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShowReport }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.security.cic.fpt.com/", name = "showReport")
    public JAXBElement<ShowReport> createShowReport(ShowReport value) {
        return new JAXBElement<ShowReport>(_ShowReport_QNAME, ShowReport.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShowReportResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.security.cic.fpt.com/", name = "showReportResponse")
    public JAXBElement<ShowReportResponse> createShowReportResponse(ShowReportResponse value) {
        return new JAXBElement<ShowReportResponse>(_ShowReportResponse_QNAME, ShowReportResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShowTimKiemKH }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.security.cic.fpt.com/", name = "showTimKiemKH")
    public JAXBElement<ShowTimKiemKH> createShowTimKiemKH(ShowTimKiemKH value) {
        return new JAXBElement<ShowTimKiemKH>(_ShowTimKiemKH_QNAME, ShowTimKiemKH.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShowTimKiemKHResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.security.cic.fpt.com/", name = "showTimKiemKHResponse")
    public JAXBElement<ShowTimKiemKHResponse> createShowTimKiemKHResponse(ShowTimKiemKHResponse value) {
        return new JAXBElement<ShowTimKiemKHResponse>(_ShowTimKiemKHResponse_QNAME, ShowTimKiemKHResponse.class, null, value);
    }

}
