//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.21 at 08:48:12 AM ICT 
//


package vn.org.cic.h2h.ws.endpoint.cicuserinfo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TenDangNhap" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MatKhauCu" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MatKhauMoi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tenDangNhap",
    "matKhauCu",
    "matKhauMoi"
})
@XmlRootElement(name = "DoiMatKhau")
public class DoiMatKhau {

    @XmlElement(name = "TenDangNhap", required = true)
    protected String tenDangNhap;
    @XmlElement(name = "MatKhauCu", required = true)
    protected String matKhauCu;
    @XmlElement(name = "MatKhauMoi", required = true)
    protected String matKhauMoi;

    /**
     * Gets the value of the tenDangNhap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenDangNhap() {
        return tenDangNhap;
    }

    /**
     * Sets the value of the tenDangNhap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenDangNhap(String value) {
        this.tenDangNhap = value;
    }

    /**
     * Gets the value of the matKhauCu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatKhauCu() {
        return matKhauCu;
    }

    /**
     * Sets the value of the matKhauCu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatKhauCu(String value) {
        this.matKhauCu = value;
    }

    /**
     * Gets the value of the matKhauMoi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatKhauMoi() {
        return matKhauMoi;
    }

    /**
     * Sets the value of the matKhauMoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatKhauMoi(String value) {
        this.matKhauMoi = value;
    }

}
