//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.19 at 03:05:43 PM ICT 
//


package vn.org.intergration.ws.endpoint.cicqafix;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DongKQ complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DongKQ">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TenTepTraLoi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TrangThai" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NgayLayVe" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DongKQ", propOrder = {
    "tenTepTraLoi",
    "trangThai",
    "ngayLayVe"
})
public class DongKQ {

    @XmlElement(name = "TenTepTraLoi", required = true)
    protected String tenTepTraLoi;
    @XmlElement(name = "TrangThai", required = true)
    protected String trangThai;
    @XmlElement(name = "NgayLayVe", required = true)
    protected String ngayLayVe;

    /**
     * Gets the value of the tenTepTraLoi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenTepTraLoi() {
        return tenTepTraLoi;
    }

    /**
     * Sets the value of the tenTepTraLoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenTepTraLoi(String value) {
        this.tenTepTraLoi = value;
    }

    /**
     * Gets the value of the trangThai property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrangThai() {
        return trangThai;
    }

    /**
     * Sets the value of the trangThai property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrangThai(String value) {
        this.trangThai = value;
    }

    /**
     * Gets the value of the ngayLayVe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNgayLayVe() {
        return ngayLayVe;
    }

    /**
     * Sets the value of the ngayLayVe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNgayLayVe(String value) {
        this.ngayLayVe = value;
    }

}
